<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="new-appl" id="main">
    <div class="parametr-top">
        <div class="parametr-bottom"><div class="parametr-middle">
                <form class="select-parametr new-appl" id="step2Form" method="post"
                      action="/incident/create/Exit">
                    <div style="padding: 0px 30px;">
                        <fieldset>
                            <p>
                                <a href="/driver/index/involved-in-incident-drivers/incident_id/new" >Please click here to chose driver from drivers list.</a>
                            </p>
                            <p class="submit-button">
                                <input type="submit" name="exitSubmit" id="nextSubmit" value="Exit">
                            </p>
                        </fieldset>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>