<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="new-appl" id="main">
    <div class="parametr-top">
        <div class="parametr-bottom">
            <div class="parametr-middle">
                <form class="select-parametr new-appl" id="step2Form" method="post"
                      action="/incident/create/exit">
                    <div style="padding: 0px 0px;">
                        <fieldset>
                            <p  align="center">
                                <?php if (isset($this->i_DOT_Regulated) && $this->i_DOT_Regulated == 'Yes') : ?>
                                    <label>
                                        <span>
                                            Incident is DOT reportable. Please contact safety coordinator immediately.
                                        </span>
                                    </label>
                                <?php else : ?>
                                    <label>
                                            Incident is not DOT reportable.
                                    </label>
                                <?php endif; ?>
                            </p>
                            
                            <p class="submit-button">
                                <input type="button" name="exitSubmit" id="exitSubmit" value="Exit">
                                <input type="button" name="chooseDriver" id="chooseDriver" value="Choose Driver">
                            </p>
                        </fieldset>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>