<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="new-appl" id="main">
    <div class="parametr-top"><div class="parametr-bottom"><div class="parametr-middle">
                <form class="select-parametr new-appl" id="step1Form" method="post"
                      action="/incident/create/step1">
                    <div style="padding: 0px 25px;">
                        <fieldset>
                            <p>
                                <label>
                                    <span>*</span>Incident Date:
                                </label>
                                <input type="text" value="" id="i_Date" name="i_Date" />
                            </p>
                            <p>
                                <label>
                                    <span>*</span>Did Incident result in human Fatality?
                                </label>
                                <span class="radio-button"><input type="radio" name="fatality" value="Yes">&nbsp;Yes</span>
                                <span class="radio-button"><input type="radio" name="fatality" value="No" checked="checked">&nbsp;No</span>
                            </p>
                            <p>
                                <label>
                                    <span>*</span>Did Incident result in injuries treated immediately away from the scene?
                                </label>
                                <span class="radio-button"><input type="radio" name="injuries" value="Yes">&nbsp;Yes</span>
                                <span class="radio-button"><input type="radio" name="injuries" value="No" checked="checked">&nbsp;No</span>
                            </p>
                            <p>
                                <label>
                                    <span>*</span>Did Incident result in any equipment being towed away from the scene?
                                </label>
                                <span class="radio-button"><input type="radio" name="towed" value="Yes">&nbsp;Yes</span>
                                <span class="radio-button"><input type="radio" name="towed" value="No" checked="checked">&nbsp;No</span>
                            </p>
                            <p>
                                <label>
                                    <span>*</span>Did the driver involved in incident receive a traffic citation?
                                </label>
                                <span class="radio-button"><input type="radio" name="citation" value="Yes">&nbsp;Yes</span>
                                <span class="radio-button"><input type="radio" name="citation" value="No" checked="checked">&nbsp;No</span>
                            </p>
                            <p class="submit-button">
                                <input type="submit" name="nextSubmit" id="nextSubmit" value="Next">
                            </p>
                        </fieldset>
                    </div>
                </form>
            </div></div></div>

</div>
