<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="driver-information" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div class="clear"></div>
                <div class="second">
                    <form class="select-parametr2" id="step2Form" method="post"
                          action="/incident/create/step2">
                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <td><a href="/driver/index/involved-in-incident-drivers/incident_id/0" >Please click here to chose driver form drivers list.</a></td>
                                </tr>
                                <tr>
                                    <td align="center" colspan="2">
                                        <input type="button" name="exitSubmit" id="exitSubmit" value="Exit">
                                        <input type="button" name="nextSubmit" id="nextSubmit" value="Next">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>