<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="driver-information" id="main">

    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <br>
                <br>
                <table class="inform">
                    <tbody>
                        <tr>
                            <td colspan="2"><h2>Accident Status:&nbsp;<span class="data">Pending</span></h2></td>
                        </tr>
                    </tbody></table>
                <div class="clear"></div>
                <div class="second">
                    <form class="select-parametr2" id="step3Form" method="post"
                          action="/incident/create/step3">
                        <table  cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">
                                        Driver Information [<a href="/driver/driver/view-driver-Information/id/<?= (isset($this->driverRow['d_ID'])) ? $this->driverRow['d_ID'] : '' ?>">EDIT</a>]
                                    </th></tr>
                                <tr>
                                    <td>Driver Name</td>
                                    <td>First:&nbsp;<span><?= (isset($this->driverRow['d_First_Name'])) ? $this->driverRow['d_First_Name'] : '' ?></span>
                                        Last:&nbsp;<span><?= (isset($this->driverRow['d_Last_Name'])) ? $this->driverRow['d_Last_Name'] : '' ?></span>
                                        Middle:&nbsp;<span><?= (isset($this->driverRow['d_Middle_Name'])) ? $this->driverRow['d_Middle_Name'] : '' ?></span>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Date Of Birth</td>
                                    <td><span><?= (isset($this->driverRow['d_Date_Of_Birth'])) ? $this->driverRow['d_Date_Of_Birth'] : '' ?></span></td>
                                </tr>
                                <tr>
                                    <td>Social Security #</td>
                                    <td><span><?= (isset($this->driverRow['d_Driver_SSN'])) ? $this->driverRow['d_Driver_SSN'] : '' ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Medical Card</td>
                                    <td>Expires:&nbsp;<span><?= (isset($this->driverRow['d_Medical_Card_Expiration_Date'])) ? $this->driverRow['d_Medical_Card_Expiration_Date'] : '' ?></span>
                                        Medical Examiner's Name:&nbsp;<span><?= (isset($this->driverRow['d_Doctor_Name'])) ? $this->driverRow['d_Doctor_Name'] : '' ?></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Phone Information</td>
                                    <td>#1 phone number:&nbsp;<span><?= (isset($this->driverRow['d_Telephone_Number1'])) ? $this->driverRow['d_Telephone_Number1'] : '' ?></span><br>
                                    </td>
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <th colspan="2">
                                        COLLISION TRAVEL DIRECTION
                                    </th>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        &nbsp;Travel Direction:&nbsp;&nbsp;
                                        <select name="i_Highway_Street_Travel_Direction">
                                            <?php
                                            foreach ($this->travelDirections as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">' . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text'] . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                        &nbsp;on Street/Highway:&nbsp;&nbsp;
                                        <input type="text" maxlength="30" value="" size="20" name="i_Highway_Street">

                                        &nbsp;Actual Speed:&nbsp;&nbsp;
                                        <input type="text" maxlength="5" value="" size="5" name="i_Actual_Speed">

                                        &nbsp;Speed Limit:&nbsp;&nbsp;
                                        <input type="text" maxlength="5" value="" size="5" name="i_Speed_Limit">

                                    </td>
                                </tr>
                                <tr>
                                    <th colspan="2">
                                        COLLISION MOVEMENT
                                    </th>
                                </tr>
                                <tr>
                                    <td colspan="2" style="padding-right: 0px;">
                                        <select id="colMovements" class="multiselect" multiple="multiple" name="colMovements[]">
                                            <option value="Stopped">Stopped</option>
                                            <option value="ProceedingStraight">Proceeding Straight</option>
                                            <option value="RunOffRoadway">Run Off Roadway</option>
                                            <option value="MakingLeftTurn">Making Left Turn</option>
                                            <option value="MakingRightTurn">Making Right Turn</option>
                                            <option value="MakingUTurn">Making UTurn</option>
                                            <option value="Backing">Backing</option>
                                            <option value="Slowing">Slowing</option>
                                            <option value="Stopping">Stopping</option>
                                            <option value="Passing">Passing</option>
                                            <option value="ChangingLanes">Changing Lanes</option>
                                            <option value="Parking">Parking</option>
                                            <option value="EnteringTraffic">Entering Traffic</option>
                                            <option value="UnsafeTurning">Unsafe Turning</option>
                                            <option value="Parked">Parked</option>
                                            <option value="Merging">Merging</option>
                                            <option value="WrongWay">WrongWay</option>
                                        </select>
                                    </td>
                                </tr>

                                <tr>
                                    <td width="20%" bgcolor="#ffffff" colspan="4" class="MainText">

                                        &nbsp;&nbsp;Other :&nbsp;&nbsp;
                                        <input type="text" maxlength="80" value="" size="80" name="colMovementsOther">


                                    </td>
                                </tr>
                                <tr>
                                    <th colspan="2">
                                        ACCIDENT IMPLICATION
                                    </th>
                                </tr>
                                <tr>
                                    <td>
                                        Injured
                                    </td>
                                    <td>
                                        <input type="radio" name="injured" value="Yes">&nbsp;Yes
                                        <input type="radio" name="injured" checked="checked" value="No">&nbsp;No
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>
                                        Deceased
                                    </td>
                                    <td>
                                        <input type="radio" name="deceased" value="Yes">&nbsp;Yes
                                        <input type="radio" name="deceased" checked="checked" value="No">&nbsp;No
                                    </td>
                                </tr>
                                <tr>
                                    <th colspan="2">
                                        POST ACCIDENT TEST
                                    </th>
                                </tr>
                                <tr>
                                    <td>Alcohol test was conducted within:</td>
                                    <td>
                                        <input type="radio" name="alcoholTest" value="Yes">&nbsp;Yes
                                        <input type="radio" name="alcoholTest" checked="checked" value="No">&nbsp;No
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>
                                        Drug test was conducted within:
                                    </td>
                                    <td>
                                        <input type="radio" name="drugTest" value="Yes">&nbsp;Yes
                                        <input type="radio" name="drugTest" checked="checked" value="No">&nbsp;No
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" colspan="2">
                                        <input type="button" id="exitSubmit" value="Exit">
                                        <input type="button" id="saveSubmit" value="Save">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                    <br><br>
                </div>
            </div>
        </div>
    </div>
</div>