<div class="driver-information" id="main">
    <div class="post-top"><div class="post-bottom"><div class="post-middle">
        <div class="clear"></div>
            <div class="second">
                <form class="select-parametr2" >
                    <table cellspacing="0" class="inform">
                        <tbody>
                            <tr><th colspan="2">VIOLATION</th></tr>
                            <tr><td colspan="2">Violation Code:</td></tr>
                            <tr><td colspan="2"><input maxlength="2" size="3" id="v_code"></td></tr>
                            <tr><td colspan="2">Violation Type:</td></tr>
                            <tr>
                                <td colspan="2">
                                    <input type="radio" class="v_type_class" name="v_type" id="v_type_driver"
                                           checked="checked" value="Driver">&nbsp;Driver
                                    <input type="radio" class="v_type_class" name="v_type" id="v_type_equipment"
                                           value="Equipment">&nbsp;Equipment
                                </td>
                            </tr>
                            <tr><td colspan="2">Violation Item:</td></tr>
                            <tr><td colspan="2"><input size="100" id="v_item"></td></tr>
                            <tr><td colspan="2">Violation Specifics:</td></tr>
                            <tr><td colspan="2"><textarea cols="80" id="v_item_specific"></textarea></td></tr>
                            <tr><td align="center" colspan="2">
                            <input type="button" id="exitCreateViolationButton" value="Exit">
                            <input type="button" id="saveCreateViolationButton" value="Save">
                            </td></tr>
                            <tr><td><br></td></tr>
                        </tbody>
                    </table>
                </form>
            </div>
    </div></div></div>
</div>