<?php
$driverAddressHistoryList = $this->layout()->driverAddressHistoryList;
$stateList = $this->layout()->stateList;
$previousAddressCount=0;
$date = new Zend_Date();
foreach($driverAddressHistoryList as $k => $v)
{
    $previousAddressCount++;
    ?>
    <tbody id="addressRecordID_<?php echo $v['dah_ID']; ?>">
    <tr class="title-dark">
        <td colspan="2">
            <?php
            if($v['dah_Current_Address']=="YES"){
                echo "Current Address";
            }
            else{
                echo "Previous Address";
            }
            ?>
            #<?php echo $previousAddressCount;?>
            [ <a onclick="editAddressHistoryRecord(<?php echo $v['dah_ID'].",".$v['dah_Driver_ID'];?>)">EDIT</a> ]
        <?php if ($this->identity['permissions']['driver_delete_driver_address_history'] === true) { ?>
            [ <a onclick="deleteAddressHistoryRecord(<?php echo $v['dah_ID'].",".$v['dah_Driver_ID'];?>)">DELETE</a> ]
            <?php
            }
                        if($previousAddressCount!=1 && $v['dah_Current_Address']=="YES"){
                echo "<font color='#ff0000'><b>Current address should be the most recent one.</b></font>";
            }
            ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            Street:&nbsp;<span><?php echo $v['dah_Address1']; ?></span>
            City:&nbsp;<span><?php echo $v['dah_City']; ?></span>
            State:&nbsp;<span><?php echo $stateList[$v['dah_State']]['s_name']; ?></span>
            Zip:&nbsp;<span><?php echo $v['dah_Postal_Code']; ?></span>
            Phone:&nbsp;<span><?php echo Custom_View_Helper_Transformation::convertNumber($v['dah_Phone']); ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            At Address:&nbsp;
            From Date:&nbsp;<span>
                <?php
                    $date->set($v['dah_Start_Date'],"MM/dd/YYYY");
                    echo $date->toString("MM/dd/YYYY");
                ?></span>
                <?php
                    if($v['dah_Current_Address']!="YES"){ ?>
                        To Date:
                <?php
                    $date->set($v['dah_End_Date'],"MM/dd/YYYY");
                    echo "<span>".$date->toString("MM/dd/YYYY")."</span>";
                ?>
                <?php
                $fromDate = explode("-",$v['dah_Start_Date']);
                $toDate = explode("-",$v['dah_End_Date']);
                echo " Year(s): <span>".($toDate[0]-$fromDate[0]);
                echo "</span> ";
                echo " Month(s): <span>".($toDate[1]-$fromDate[1])."</span>";
                }
                ?>
        </td>
    </tr>
    </tbody>
    <?php
        }
?>