<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

</div>

<div class="driver-information" id="main">

    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <br>
                <br>
                <table class="inform">
                    <tbody>
                        <tr>
                            <td colspan="2"><h2>Vehicle type:&nbsp;<span class="data">
                                        <?= (isset($this->equipmentRow['et_type'])) ? $this->equipmentRow['et_type'] : ''; ?>
                                    </span></h2></td>
                        </tr>
                        <tr><td colspan="2"><h2>VIN:&nbsp;<span class="data">
                                        <?= ((isset($this->equipmentRow['e_Number'])) ? $this->equipmentRow['e_Number'] : ''); ?>
                                    </span></h2></td></tr>
                        <tr>
                            <td colspan="2"><h2>Status:&nbsp;<span class="data">
                                        <?= (isset($this->equipmentRow['eas_type'])) ? $this->equipmentRow['eas_type'] : ''; ?>
                                    </span></h2></td>
                        </tr>
                    </tbody>
                </table>
                <div class="clear"></div>
                <div class="second">
                    <form class="select-parametr2" id="changeActiveStatusForm" method="post"
                          action="/equipment/vehicle-file/change-active-status">
                        <input type="hidden" id="e_id" name="e_id" value="<?= (isset($this->equipmentRow['e_id'])) ? $this->equipmentRow['e_id'] : ''; ?>" />
                        <input type="hidden" id="e_Active_Status" name="e_Active_Status" value="<?= (isset($this->statusToChange)) ? $this->statusToChange : ''; ?>" />
                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <td><span class="red">*</span>Date Of Status Change</td>
                                    <td>
                                        <input id="e_change_active_status_date" 
                                               name="e_change_active_status_date"
                                               value="<?= (isset($this->currentDate)) ? $this->currentDate : ''; ?>" />
                                        <br />
                                        <label for="e_change_active_status_date" generated="true" class="error" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>Action taken by:</td>
                                    <td><?= (isset($this->person)) ? $this->person : ''; ?></td>
                                </tr>
                                <tr>
                                    <td>Comment</td>
                                    <td>
                                        <textarea id="e_change_active_status_comment"
                                                  name="e_change_active_status_comment"></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" colspan="2">
                                        <input type="button" name="cancelChangeSubmit" id="cancelChangeSubmit" value="Cancel">
                                        <input type="button" name="changeSubmit" id="changeSubmit" value="<?= $this->actionLabel; ?>">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>


</div>
