<?php

$driverEquipmentOperatedList = $this->layout()->driverEquipmentOperatedRecord;
$equipmentTypeList = $this->layout()->equipmentTypeList;
$date = new Zend_Date();

        ?>
        <td>
            <a onclick="updateEquipmentOperatedRecord(<?php echo $driverEquipmentOperatedList['deo_ID'].",".$driverEquipmentOperatedList['deo_Driver_ID'];?>)"><img src="/images/icon-save.png" title="save record" alt="save record" width="15px" height="15px" /></a>&nbsp;&nbsp;&nbsp;
            <a onclick="refreshEquipmentOperatedRecords(<?php echo $driverEquipmentOperatedList['deo_Driver_ID'];?>)"><img src="/images/icon-undo.png" title="cancel edit" alt="cancel edit" width="15px" height="15px" /></a>
            <input type="hidden" name="edit_deo_Driver_ID" id="edit_deo_Driver_ID" value="<?php echo $driverEquipmentOperatedList['deo_Driver_ID'];?>" />
            <input type="hidden" name="edit_deo_ID" id="edit_deo_ID" value="<?php echo $driverEquipmentOperatedList['deo_ID'];?>" />
            <select name="edit_deo_Equipment_Type_ID">
            <?php
                for($i=0;$i<sizeof($equipmentTypeList);$i++){?>
                    <option value="<?php echo $equipmentTypeList[$i]['et_id']; ?>" <?php if($equipmentTypeList[$i]['et_id']==$driverEquipmentOperatedList['deo_Equipment_Type_ID']){echo " selected='selected' ";} ?>><?php echo $equipmentTypeList[$i]['et_type']; ?></option>
            <?php
        }
            ?>
                </select>
        </td>
        <td>
            From Date:&nbsp;
            <input name="edit_deo_From_Date"  id="edit_deo_From_Date" class="datepicker" size="7" maxlength="10" value="<?php
                    $date->set($driverEquipmentOperatedList['deo_From_Date'],"yyyy-MM-dd"); echo $date->toString("MM/dd/yyyy");
                ?>" />
&nbsp;To Date:&nbsp;<input id="edit_deo_To_Date" name="edit_deo_To_Date" class="datepicker" size="7" maxlength="10" value="<?php
                    if(isset($driverEquipmentOperatedList['deo_To_Date'])){
                        $date->set($driverEquipmentOperatedList['deo_To_Date'],"yyyy-MM-dd"); echo $date->toString("MM/dd/yyyy");
                    }
                ?>" />
&nbsp;&nbsp;Total Miles:&nbsp;<input name="edit_deo_Total_Miles" value="<?php echo $driverEquipmentOperatedList['deo_Total_Miles'];?>" maxlength="20" />
            <img src="/images/indicator.gif" id="edit_equipment_operated_indicator" style="display:none;" alt="" />
        </td>
