<?php

$driverEquipmentOperatedList = $this->layout()->driverEquipmentOperatedList;
$equipmentTypeList = $this->layout()->equipmentTypeList;
$date = new Zend_Date();
if(sizeof($driverEquipmentOperatedList)<1){?>
    <tr><td>No experience recorded yet. </td><td></td></tr>
<?php }else{
    foreach($driverEquipmentOperatedList as $k => $v){
        ?>
    <tr <?php  if(gettype($k/2) != 'double'){ echo " class='color-dark' ";} ?> id="equipmentOperatedID_<?php echo $v['deo_ID']; ?>">
        <td>
            <a onclick="editEquipmentOperatedRecord(<?php echo $v['deo_ID'].",".$v['deo_Driver_ID'];?>)"><img src="/images/icon-edit.png" alt="edit record" width="15px" height="15px" /></a>&nbsp;&nbsp;&nbsp;
            <a onclick="deleteEquipmentOperatedRecord(<?php echo $v['deo_ID'].",".$v['deo_Driver_ID'];?>)"><img src="/images/icon-delete.png" alt="delete record" width="15px" height="15px" /></a>
        <?php
            for($i=0;$i<sizeof($equipmentTypeList);$i++){
                if($equipmentTypeList[$i]['et_id']==$v['deo_Equipment_Type_ID']){
                    echo $equipmentTypeList[$i]['et_type'];
                }
            }
        ?>
        </td>
        <td>
            From Date:&nbsp;
            <span>
                <?php
                    $date->set($v['deo_From_Date'],"yyyy-MM-dd"); echo $date->toString("MM/dd/yyyy");
                ?>
            </span>
            To Date:&nbsp;
            <span>
                <?php
                    if(isset($v['deo_To_Date'])){
                        $date->set($v['deo_To_Date'],"yyyy-MM-dd"); echo $date->toString("MM/dd/yyyy");
                    }else{echo "";}
                ?>
            </span>
            Total Miles:&nbsp;<span><?php echo $v['deo_Total_Miles'];?></span>
        </td>
    </tr>
    <?php
    }

    ?>

    <?php
    }

?>