<?php
    $driverEmploymentHistoryRecord = $this->layout()->driverEmploymentHistoryRecord;
?>
    <input type="hidden" id="edit_dpe_Driver_ID" name="edit_dpe_Driver_ID" value="<?php echo $driverEmploymentHistoryRecord['dpe_Driver_ID'];?>" />
    <input type="hidden" id="edit_dpe_ID" name="edit_dpe_ID" value="<?php echo $driverEmploymentHistoryRecord['dpe_ID'];?>" />
    <input type="hidden" id="edit_emp_ID" name="edit_emp_ID" value="<?php echo $driverEmploymentHistoryRecord['emp_ID'];?>" />
    <tr class="title-dark">
        <td colspan="2">Edit Employer [ <a onclick="refreshEmploymentHistoryRecords(<?php echo $driverEmploymentHistoryRecord['dpe_Driver_ID'];?>);">CANCEL</a> ]</td></tr>
    <tr>
        <td><label for="edit_emp_Employer_Name" class="required"><span>*</span>Employer:</label></td>
        <td>
            <input type="text" onkeyup="autocomplete_custom('edit_emp_Employer_Name','edit_emp_Employer_Name_ul');" value="<?php echo $driverEmploymentHistoryRecord['emp_Employer_Name'];?>" maxlength="250" size="50" name="edit_emp_Employer_Name" id="edit_emp_Employer_Name"/><img src="/images/indicator.gif" id="edit_emp_Employer_Name_indicator" style="display:none;" alt="" />
            <div class="ac_results" id="edit_emp_Employer_Name_ul" style="display:none; position: absolute; border: 1px solid rgb(170, 170, 170); width: 324px; background: none repeat scroll 0% 0% rgb(255, 255, 255);" >
            </div>
            <script type="text/javascript">
                $().ready(function() {
                    $("#edit_emp_Employer_Name").keyup(function() {
                        autocomplete_custom('edit_emp_Employer_Name','edit_emp_Employer_Name_ul');
                    });
                });
            </script>

        </td>
    </tr>
    <tr class="color-dark">
        <td><label for="edit_emp_Address1" class="required"><span>*</span>Street:</label></td>
		<td>
            <input readonly="readonly" type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_Address1'];?>"  maxlength="250" size="50" name="edit_emp_Address1" id="edit_emp_Address1">&nbsp;<br>
            <label for="edit_emp_City" class="required"><span>*</span>City:</label>
            <input readonly="readonly" type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_City'];?>" maxlength="250" size="15" name="edit_emp_City" id="edit_emp_City"> &nbsp;
            <label for="edit_emp_State_ID" class="required"><span>*</span>State:</label>
                <select name="edit_emp_State_ID" id="edit_emp_State_ID">
                <?php
                    foreach($this->layout()->stateList as $k => $v)
                    {
                ?>
                        <option label="<?php echo $v['s_name'];?>" value="<?php echo $k;?>" <?php if($k==$driverEmploymentHistoryRecord['emp_State_ID']){echo "selected='selected'";} ?> ><?php echo $v['s_name'];?></option>
                <?php
                    }
                ?>
                </select> &nbsp;
            <label for="edit_emp_Postal_Code" class="required"><span>*</span>Zip: </label>
            <input readonly="readonly" type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_Postal_Code'];?>" maxlength="20" size="10" name="edit_emp_Postal_Code" id="edit_emp_Postal_Code">
        </td>
    </tr>
    <tr>
        <td><label for="edit_emp_Phone" class="required"><span>*</span>Phone:</label></td>
        <td>
            <input readonly="readonly" type="text" value="<?php echo Custom_View_Helper_Transformation::convertNumber($driverEmploymentHistoryRecord['emp_Phone']);?>" size="30" name="edit_emp_Phone" id="edit_emp_Phone"> &nbsp;
            <label for="edit_emp_Fax" class="required"><span>*</span>Fax:</label>&nbsp; <input readonly="readonly" type="text" value="<?php echo Custom_View_Helper_Transformation::convertNumber($driverEmploymentHistoryRecord['emp_Fax']);?>" size="30" name="edit_emp_Fax" id="edit_emp_Fax">
        </td>
    </tr>
    <tr class="color-dark">
        <td><label for="edit_dpe_Position" class="required"><span>*</span>Job Description:</label></td>
        <td>
            <input type="text" maxlength="250" value="<?php echo $driverEmploymentHistoryRecord['dpe_Position'];?>" size="50" name="edit_dpe_Position" id="edit_dpe_Position">
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <label for="edit_dpe_Employment_Start_Date" class="required"><span>*</span>From: </label>
            <input id="edit_dpe_Employment_Start_Date" type="text" value="<?php
                    $date = new Zend_Date($driverEmploymentHistoryRecord['dpe_Employment_Start_Date'],"yyyy-MM-dd");
                    echo $date->toString("MM/dd/yyyy");
                ?>" maxlength="10" size="10" name="edit_dpe_Employment_Start_Date" class="datepicker" />&nbsp;&nbsp;&nbsp;&nbsp;
            <label for="edit_dpe_Employment_Stop_Date" class="required">To: </label>
            <input id="edit_dpe_Employment_Stop_Date"  type="text" value="<?php
                    $date = new Zend_Date($driverEmploymentHistoryRecord['dpe_Employment_Stop_Date'],"yyyy-MM-dd");
                    echo $date->toString("MM/dd/yyyy");
                ?>" maxlength="10" size="10" name="edit_dpe_Employment_Stop_Date" class="datepicker"  />
        </td>
    </tr>
    <tr class="color-dark">
        <td><label class="required" for="edit_dpe_Salary"><span>*</span>Salary:</label></td>
        <td><input type="text" id="edit_dpe_Salary" name="edit_dpe_Salary"  maxlength="10"  value="<?php echo $driverEmploymentHistoryRecord['dpe_Salary'];?>"/></td></tr>
    <tr>
    <tr><td><label for="edit_dpe_Reason_for_Leaving" class="required"><span>*</span>Reason For Leaving:</label></td>
        <td>
            <input maxlength="250" name="edit_dpe_Reason_for_Leaving" id="edit_dpe_Reason_for_Leaving" type="text" value="<?php echo $driverEmploymentHistoryRecord['dpe_Reason_for_Leaving'];?>" />
        </td>
    </tr>
    <tr class="color-dark">
        <td class=""></td>
        <td class="">
            DOT Safety Sensitive:&nbsp;&nbsp;
            <select name="edit_emp_DOT_Safety_Sensitive_Function" id="edit_emp_DOT_Safety_Sensitive_Function">
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_DOT_Safety_Sensitive_Function'])=="no"){echo "selected='selected'";};?> value="NO">No</option>
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_DOT_Safety_Sensitive_Function'])=="yes"){echo "selected='selected'";};?> value="YES">Yes</option>
            </select>&nbsp;&nbsp;&nbsp;&nbsp;
            FMCSR Regulated:&nbsp;&nbsp;
            <select name="edit_emp_FMCSR" id="edit_emp_FMCSR">
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_FMCSR'])=="no"){echo "selected='selected'";};?> value="NO">No</option>
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_FMCSR'])=="yes"){echo "selected='selected'";};?> value="YES">Yes</option>
            </select>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><span class="blue-button float-left"><a id="updateEmploymentHistoryRecord" onclick="updateEmploymentHistoryRecord(<?php echo $driverEmploymentHistoryRecord['dpe_ID'];?>);">Save</a></span></td>
    </tr>
    <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
