<?php
    $driverEmploymentHistoryList = $this->layout()->driverEmploymentHistoryList;
    $stateList = $this->layout()->stateList;
    $previousEmployerCount=0;
    $date = new Zend_Date();
    foreach($driverEmploymentHistoryList as $k => $v)
    {
        $previousEmployerCount++;
?>
<tbody id="driver_pe_id_<?php echo $v['dpe_ID'];?>">
<tr class="title-dark"><td colspan="2">Previous Employer #<?php echo $previousEmployerCount;?> [ <a onclick="editEmploymentHistoryRecord(<?php echo $v['dpe_ID'].",".$v['dpe_Driver_ID'];?>)">EDIT</a> ] [ <a onclick="deleteEmploymentHistoryRecord(<?php echo $v['dpe_ID'].",".$v['dpe_Driver_ID'];?>)">DELETE</a> ]</td></tr>
<tr><td>Employer:</td><td><span><?php echo $v['emp_Employer_Name'];?></span></td></tr>
<tr class="color-dark">
    <td>Street:</td>
    <td>
        <span><?php echo $v['emp_Address1'];?></span>
        City:&nbsp;<span><?php echo $v['emp_City'];?></span>
        State:&nbsp;<span><?php echo $stateList[$v['emp_State_ID']]['s_name'];?></span>
        Zip:&nbsp;<span><?php echo $v['emp_Postal_Code'];?></span>
    </td>
</tr>
<tr><td>Telephone:</td><td><span><?php echo Custom_View_Helper_Transformation::convertNumber($v['emp_Phone']);?></span>&nbsp;Fax:&nbsp;<span><?php echo Custom_View_Helper_Transformation::convertNumber($v['emp_Fax']);?></span></td></tr>
<tr class="color-dark"><td>Job Description:</td><td><span>&nbsp;<?php echo $v['dpe_Position'];?></span></td></tr>
<tr><td></td>
    <td>
        From:&nbsp;<span><?php
        $date->set($v['dpe_Employment_Start_Date'],"YYYY-MM-dd");    
        echo $date->toString("MM/dd/YYYY");?></span>
        <?php if(isset($v['dpe_Employment_Stop_Date'])){?>
        To:&nbsp;<span><?php
        $date->set($v['dpe_Employment_Stop_Date'],"YYYY-MM-dd");    
        echo $date->toString("MM/dd/YYYY");?></span>
        <?php }else{ ?>
            <span>Current moment.</span>
        <?php } ?>
    </td>
</tr>
<tr class="color-dark"><td>Salary:</td><td><span>&nbsp;<?php echo $v['dpe_Salary'];?></span></td></tr>
<tr><td>Reason For Leaving:</td><td><span>&nbsp;<?php echo $v['dpe_Reason_for_Leaving'];?></span></td></tr>
</tbody>
<?php
    }
?>