<?php
    $driverEmploymentHistoryRecord = $this->layout()->driverEmploymentHistoryRecord;
?>
    <input type="hidden" id="edit_pe_Driver_ID" name="edit_pe_Driver_ID" value="<?php echo $driverEmploymentHistoryRecord['dpe_Driver_ID'];?>" />
    <input type="hidden" id="edit_pe_ID" name="edit_pe_ID" value="<?php echo $driverEmploymentHistoryRecord['dpe_ID'];?>" />
    <tr class="title-dark">
        <td colspan="2">Edit Employer [ <a onclick="refreshEmploymentHistoryRecords(<?php echo $driverEmploymentHistoryRecord['dpe_Driver_ID'];?>);">CANCEL</a> ]</td></tr>
    <tr>
        <td><label for="edit_pe_Employer_Name" class="required"><span>*</span>Employer:</label></td>
        <td>
            <div class="error_custom2" id="edit_error_custom_add_Employment_Table"></div>
            <input type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_Employer_Name'];?>" maxlength="250" size="50" name="edit_pe_Employer_Name" id="edit_pe_Employer_Name"></td>
    </tr>
    <tr class="color-dark">
        <td><label for="edit_pe_Address1" class="required"><span>*</span>Street:</label></td>
		<td>
            <input type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_Address1'];?>"  maxlength="250" size="50" name="edit_pe_Address1" id="edit_pe_Address1">&nbsp;<br>
            <label for="edit_pe_City" class="required"><span>*</span>City:</label>
            <input type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_City'];?>" maxlength="250" size="15" name="edit_pe_City" id="edit_pe_City"> &nbsp;
            <label for="edit_pe_State" class="required"><span>*</span>State:</label>
                <select name="edit_pe_State" id="edit_pe_State">
                <?php
                    foreach($this->layout()->stateList as $k => $v)
                    {
                ?>
                        <option label="<?php echo $v['s_name'];?>" value="<?php echo $k;?>" <?php if($k==$driverEmploymentHistoryRecord['emp_State_ID']){echo "selected='selected'";} ?> ><?php echo $v['s_name'];?></option>
                <?php
                    }
                ?>
                </select> &nbsp;
            <label for="edit_pe_Postal_Code" class="required"><span>*</span>Zip: </label>
            <input type="text" value="<?php echo $driverEmploymentHistoryRecord['emp_Postal_Code'];?>" maxlength="20" size="10" name="edit_pe_Postal_Code" id="edit_pe_Postal_Code">
        </td>
    </tr>
    <tr>
        <td><label for="edit_pe_Phone" class="required"><span>*</span>Phone:</label></td>
        <td>
            <input type="text" value="<?php echo Custom_View_Helper_Transformation::convertNumber($driverEmploymentHistoryRecord['emp_Phone']);?>" size="30" name="edit_pe_Phone" id="edit_pe_Phone"> &nbsp;
            <label for="edit_pe_Fax" class="required"><span>*</span>Fax:</label>&nbsp; <input type="text" value="<?php echo Custom_View_Helper_Transformation::convertNumber($driverEmploymentHistoryRecord['emp_Fax']);?>" size="30" name="edit_pe_Fax" id="edit_pe_Fax">
        </td>
    </tr>
    <tr class="color-dark">
        <td><label for="edit_pe_Position" class="required"><span>*</span>Job Description:</label></td>
        <td>
            <input type="text" maxlength="250" value="<?php echo $driverEmploymentHistoryRecord['dpe_Position'];?>" size="50" name="edit_pe_Position" id="edit_pe_Position">
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <label for="edit_pe_Employment_Start_Date" class="required"><span>*</span>From: </label>
            <input id="edit_pe_Employment_Start_Date" type="text" value="<?php
                    $date = new Zend_Date($driverEmploymentHistoryRecord['dpe_Employment_Start_Date'],"YYYY-MM-dd");
                    echo $date->toString("MM/dd/YYYY");
                ?>" maxlength="10" size="10" name="edit_pe_Employment_Start_Date" class="datepicker" />&nbsp;&nbsp;&nbsp;&nbsp;
            <label for="edit_pe_Employment_Stop_Date" class="required">To: </label>
            <input id="edit_pe_Employment_Stop_Date"  type="text" value="<?php
                    $date = new Zend_Date($driverEmploymentHistoryRecord['dpe_Employment_Stop_Date'],"YYYY-MM-dd");
                    echo $date->toString("MM/dd/YYYY");
                ?>" maxlength="10" size="10" name="edit_pe_Employment_Stop_Date" class="datepicker"  />
        </td>
    </tr>
    <tr class="color-dark"><td><label for="edit_pe_Reason_for_Leaving" class="required"><span>*</span>Reason For Leaving:</label></td>
        <td>
            <input maxlength="250" name="edit_pe_Reason_for_Leaving" id="edit_pe_Reason_for_Leaving" type="text" value="<?php echo $driverEmploymentHistoryRecord['dpe_Reason_for_Leaving'];?>" />
        </td>
    </tr>
    <tr>
        <td class=""></td>
        <td class="">
            DOT Safety Sensitive:&nbsp;&nbsp;
            <select name="edit_pe_DOT_Safety_Sensitive_Function">
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_DOT_Safety_Sensitive_Function'])=="no"){echo "selected='selected'";};?> value="NO">No</option>
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_DOT_Safety_Sensitive_Function'])=="yes"){echo "selected='selected'";};?> value="YES">Yes</option>
            </select>&nbsp;&nbsp;&nbsp;&nbsp;
            FMCSR Regulated:&nbsp;&nbsp;
            <select name="edit_pe_FMCSR_Regulated">
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_FMCSR'])=="no"){echo "selected='selected'";};?> value="NO">No</option>
                <option <?php if(strtolower($driverEmploymentHistoryRecord['emp_FMCSR'])=="yes"){echo "selected='selected'";};?> value="YES">Yes</option>
            </select>
        </td>
    </tr>
    <tr class="color-dark"><td colspan="2">&nbsp;</td></tr>
    <tr>
        <td></td>
        <td><span class="blue-button float-left"><a id="updateEmploymentHistoryRecord" onclick="updateEmploymentHistoryRecord(<?php echo $driverEmploymentHistoryRecord['pe_ID'];?>);">Save</a></span></td>
    </tr>
    <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
