<!--
@author Andryi Ilnytskyi 0.11.2010

Users list form.
-->

<div class="bottom-nav">
    <form class="status" action="#">
        <fieldset>
            <label>Status:</label>
            <select>
                <option selected="selected" value="Pending">Pending</option>
                <option value="Declined">Declined</option>
                <option value="All">All</option>
            </select>
        </fieldset>
    </form>

    <form class="search" action="#">
        <fieldset>
            <label>Search By:</label>
            <select name="SearchBy">
                <option selected="" value="-">-</option>
                <option value="UnitNumber">ID</option>
                <option value="VIN">VIN</option>
                <option value="VehType">Veh. Type</option>
                <option value="VendorID">Vendor Code</option>
                <option value="GVW">GVW</option>
                <option value="LicPlateNum">Lic. Plate #</option>
                <option value="NumOfAxles"># of axles</option>
            </select>
            <input type="text" value=""/>
            <input type="submit" value=""/>
        </fieldset>
    </form>
</div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span><?php echo $this->breadcrumbs; ?></span>
        </div>
    </div>
</div>


<div id="main" class="driver-profile">
    <table class="application-forms" cellspacing="0">
        <tr class="table-title">
            <td>Unit #</td>
            <td>Veh. Type</td>
            <td>VIN</td>
            <td>Lic. Plate #/State</td>
            <td>GVW</td>
            <td>#Axles</td>
            <td>Vendor Code</td>
            <td>Status</td>
            <td>Action</td>
        </tr>
        <?php
            if ($this->equipments != null) {
                echo $this->partialLoop('partials/_equipment-row.phtml', $this->equipments);
            }
        ?>
        <tr>
            <td class="page" colspan="9">
                Equipment  <?php echo $this->from; ?> to <?php echo $this->from + $this->step; ?>  ( <?php echo sizeof($this->allEquipments); ?> )
            </td>
        </tr>
        <tr>
            <td class="page" colspan="9">
                <?php
                echo $this->partial('partials/_pagignator.phtml', array(
                    'equipmentsCount' => $this->allEquipments,
                    'from' => $this->from,
                    'last' => $this->from + $this->step,
                    'step' => $this->step,
                    'status' => $this->status));
                ?>
            </td>
        </tr>
    </table>
</div>
