<!--
@author Andryi Ilnytskyi 04.11.2010

Users list form.
-->

<?php
    echo $this->navigation()->menu()->render(); ?>
<h2>Equipment List</h2>
<?php
if ($this->equipments != null) {
?>
    <table border='1' cellpadding="0" cellspacing="0" width="1100px">
        <tr>
            <th>Unit #</th>
            <th>Veh. Type</th>
            <th>VIN</th>
            <th>Lic. Plate #/State</th>
            <th>GVW</th>
            <th>#Axles</th>
            <th>Vendor Code</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        <?php echo $this->partialLoop('partials/_equipment-row.phtml', $this->equipments); ?>
    </table>
<?php
} else {
?>
    <p>You do not have any equipments yet.</p>
<?php
}
if ($this->display_search_link) {
    echo '<p><a href="/equipment/search">Create a new equipment</a></p>';
}
?>

