<h2>Company list</h2>
<?php if ($this->identity == null) {
 ?>
    <p>To log in <a href='/user/login'>click here</a></p>
<?php }?>
        <table border='1' cellpadding="0" cellspacing="0" width="1100px">
        <tr>
            <td>Company name</td>
            <td>Parent Company</td>
            <td>Home Base Name</td>
            <td>State</td>
            <td>Start Date</td>
            <td>Status</td>
            <td>Action</td>
        </tr>
</table>
