<div class="bottom-nav">
    <ul class="blue-nav">
        <li>
            <span>
                <a id="equipmentAssignmentSaveLink1" href="#">
                    Save
                </a>
            </span>
        </li>
        <li>
            <span>
                <a href="/equipment/list">
                    Exit
                </a>
            </span>
        </li>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<!--TODO hak for diz-->
</div>

<div class="driver-information vehicle" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <form id="updateAsignment" method="post" action="/equipment/information-worksheet/save-assignment/id/<?php echo $this->equipmentAssignmentRow['ea_equipment_id']; ?>">
                    <table class="first">
                        <tbody>
                            <tr>
                                <td>Equipment VIN</td>
                                <td>
                                    <input type="hidden" value="<?= (isset($this->equipmentAssignmentRow['ea_equipment_id'])) ? $this->equipmentAssignmentRow['ea_equipment_id'] : '' ; ?>" id="ea_equipment_id" name="ea_equipment_id" />
                                    <input type="hidden" value="<?= (isset($this->equipmentAssignmentRow['ea_id'])) ? $this->equipmentAssignmentRow['ea_id'] : '' ; ?>" id="ea_id" name="ea_id" />
                                    <?= $this->VIN; ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="second">
                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">Equipment Assignment Information</th>
                                </tr>
                                <tr>
                                    <td>
                                        <label><span>*</span>
                                            Homebase
                                        </label>
                                    </td>
                                    <td>
                                        <select name="ea_homebase_id" id="ea_homebase_id">
                                            <?php
                                            foreach ($this->homebases as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">' . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text'] . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Depot</td>
                                    <td>
                                        <select  class="rc10" name="ea_depot_id" id="ea_depot_id">
                                            <?php
                                            foreach ($this->depots as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">' . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text'] . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label><span>*</span>
                                             DOT Regulated
                                        </label>
                                    </td>
                                    <td>
                                        <span class="radio-button">
                                            <?php if (isset($this->equipmentAssignmentRow['ea_DOT_regulated']) && $this->equipmentAssignmentRow['ea_DOT_regulated'] == 'Yes') : ?>
                                                <input type="radio" name="ea_DOT_regulated" id="ea_DOT_Regulated" value="Yes" checked="checked">
                                            <?php else : ?>
                                                    <input type="radio" name="ea_DOT_regulated" id="ea_DOT_Regulated" value="Yes">
                                            <?php endif; ?>
                                                    &nbsp;Yes
                                        </span>
                                        <span class="radio-button">
                                            <?php if (isset($this->equipmentAssignmentRow['ea_DOT_regulated']) && $this->equipmentAssignmentRow['ea_DOT_regulated'] == 'No') : ?>
                                                        <input type="radio" name="ea_DOT_regulated" id="ea_DOT_Regulated" value="No" checked="checked">
                                            <?php else : ?>
                                                            <input type="radio" name="ea_DOT_regulated" id="ea_DOT_Regulated" value="No">
                                            <?php endif; ?>
                                                            &nbsp;No
                                        </span>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>
                                        <label><span>*</span>
                                            Owner
                                        </label>
                                    </td>
                                    <td>
                                        <select  class="rc10" name="ea_owner_id" id="ea_owner_id">
                                            <?php
                                            foreach ($this->owners as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">' . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text'] . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Driver</td>
                                    <td>
                                        <select  class="rc10" name="ea_driver_id" id="ea_driver_id">
                                            <?php
                                            foreach ($this->drivers as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">' . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text'] . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Mileage</td>
                                    <td>
                                        <input type="text" value="" id="ea_mileage" name="ea_mileage" />
                                    </td>
                                </tr>
                        </table>
                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">
                                        &nbsp;
                                    </th>
                                </tr>
                                <tr>
                                    <td>Inspection</td>
                                    <td>
                                        <span>
                                            <a href="/inspection/create/index/equipmentId/<?= (isset($this->equipmentAssignmentRow['e_id'])) ? $this->equipmentAssignmentRow['e_id'] : '' ; ?>">
                                                Add inspection
                                            </a>
                                        </span>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Maintenance</td>
                                    <td>
                                        <span>
                                            <a href="/equipmentMaintenance/create/index/equipmentId/<?= (isset($this->equipmentAssignmentRow['e_id'])) ? $this->equipmentAssignmentRow['e_id'] : '' ; ?>">
                                                Add maintenance
                                            </a>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Incident</td>
                                    <td>
                                        <span>
                                            <a href="/incident/create/index/equipmen</div>tId/<?= (isset($this->equipmentAssignmentRow['e_id'])) ? $this->equipmentAssignmentRow['e_id'] : '' ; ?>">
                                                Add incident
                                            </a>
                                        </span>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Service Provider</td>
                                    <td>
                                        <a href="/serviceProvider/create/index/equipmentId/<?= (isset($this->equipmentAssignmentRow['e_id'])) ? $this->equipmentAssignmentRow['e_id'] : '' ; ?>">
                                                Add Service Provider
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label><span>*</span>
                                            Start Date
                                        </label>
                                    </td>
                                    <td>
                                        <input type="text" value="<?= (isset($this->equipmentAssignmentRow['ea_start_date'])) ? $this->equipmentAssignmentRow['ea_start_date'] : '' ; ?>" id="ea_start_date" name="ea_start_date" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>
                                        <label><span>*</span>
                                            End Date
                                        </label>
                                    </td>
                                    <td>
                                        <input type="text" value="<?= (isset($this->equipmentAssignmentRow['ea_end_date'])) ? $this->equipmentAssignmentRow['ea_end_date'] : '' ; ?>" id="ea_end_date" name="ea_end_date" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="blue-nav">
        <ul>
            <li>
                <span>
                    <a id="equipmentAssignmentSaveLink2">
                        Save
                    </a>
                </span>
            </li>
            <li>
                <span>
                    <a href="/equipment/list">
                        Exit
                    </a>
                </span>
            </li>
        </ul>
    </div>

</div>