<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<!--TODO hak for diz-->
</div>

<div class="driver-information form" id="main">

    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div style="padding: 30px;">
                    <table class="inform">
                        <tbody>
                            <tr>
                                <td colspan="2"><h2>VIM:&nbsp;<span class="data"><?= $this->VIN; ?></span></h2></td>
                            </tr>
                            <tr>
                                <td colspan="2"><h2>Unit Number:&nbsp;<span class="data"><?= $this->UnitNumber; ?></span></h2></td>
                            </tr>
                            <tr class="color-dark">
                                <td width="400"><a href="/equipment/information-worksheet/index/VIN/<?= $this->VIN; ?>">Review Vehicle Application</a><br>
                                    <div class="warning">
                                        <?php if (isset($this->warningArray) && is_array($this->warningArray)) {
                                            foreach ($this->warningArray as $field => $title) {
                                                echo "Warning: Vehicle $title record is missing.<br /> ";
                                            }
                                        } ?>
                                    </div>
                                    <?php if (!$this->hasInspection) : ?>
                                        <div class="error_custom">
                                            Error: Record about vehicle inspection (federal or state) is missing. You can not complete application without vehicle inspection record.
                                        </div>
                                    <?php endif; ?>
                                </td>
<!--                                <td width="100" style="vertical-align: middle;"><span class="blue-button"><a href="#">Check</a></span></td>-->
                                <td></td>
                            </tr>
                            <tr>
<!--                                <td><a href="/equipment/information-worksheet/show-complete-form/id/<?= $this->ID; ?>">COMPLETE APPLICATION</a></td>-->
                                <td><a href="/equipment/information-worksheet/index/VIN/<?= $this->VIN; ?>">Vehicle Information Worksheet</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>