<div class="bottom-nav">
    <ul class="blue-nav">
        <?=
        $this->partial('partials/_view_action.phtml', array(
            'equipmentID' => $this->equipmentRow['e_id'],
            'status' => $this->equipmentRow['enes_type'],
            'identity' => $this->identity
        ));
        ?>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>


<div class="driver-information equipment" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div id="viewVIWdiv" class="VIWDiv">
                
                </div>
                <?php
                    echo $this->partial('partials/_updateVIW.phtml', array(
                            'equipmentRow' => $this->equipmentRow,
                            'equipmentTypes' => $this->equipmentTypes,
                            'states' => $this->states,
                            'equipmentStatus' => $this->equipmentStatus
                        ));
                ?>
            </div>
        </div>
    </div>

    <div class="driver-information equipment">
        <div class="post-top">
            <div class="post-bottom">
                <div class="post-middle">
                    <div id="viewAssignmentDiv" class="AssignmentDiv">
                    </div>
                    <?php echo
                        $this->partial('partials/_add-assignment.phtml', array(
                                'equipmentAssignmentRow' => $this->equipmentAssignmentRow,
                                'homebases' => $this->homebases,
                                'depots' => $this->depots,
                                'owners' => $this->owners,
                                'drivers' => $this->drivers,
                                'serviceProviders' => $this->serviceProviders,
                                'incidents' => $this->incidents
                            ));
                    ?>
                </div>
            </div>
        </div>
    </div>

    <div id="viewAssignmentDriverDiv" class="AssignmentDiv">
        
     </div>

    <div><?php
        if(isset($this->equipmentRow['e_last_modified_datetime'])){

            echo '<h3 style="padding-top: 15px; padding-left: 28px;" id="e_last_modified_datetime">Last saved: ' . $this->equipmentRow['e_last_modified_datetime'] . '</h3>';
        }

    ?></div>

    <div class="blue-nav" style="width:530px;">
        <ul>
            <li>
                <span>
                    <a id="commonSaveButton" class="saveButton">
                        Save
                    </a>
                </span>
            </li>
            <li>
                <span>
                    <a id="discardButton">
                        Discard
                    </a>
                </span>
            </li>
            <?=
                $this->partial('partials/_view_action.phtml', array(
                    'equipmentID' => $this->equipmentRow['e_id'],
                    'status' => $this->equipmentRow['enes_type'],
                    'identity' => $this->identity
                ));
            ?>
        </ul>
    </div>

</div>
