<div class="bottom-nav">
    <ul class="blue-nav">
        <?=
            $this->partial('partials/_view_action.phtml', array(
                'equipmentID' => $this->equipmentRow['e_id'],
                'status' => $this->equipmentRow['enes_type']
            ));
        ?>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<!--TODO hak for diz-->
</div>

<div class="driver-information vehicle" id="main">
    <div class="post-top"><div class="post-bottom"><div class="post-middle">
        <table class="first">
            <tbody>
                <tr>
                    <td>VIN</td>
                    <td><?php echo $this->equipmentRow['e_Number'] ?></td>
                </tr>
                <tr>
                    <td>Entry Date</td>
                    <td><?php echo $this->equipmentRow['e_Entry_Date'] ?></td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td><?php echo $this->equipmentRow['enes_type'] ?></td>
                </tr>
            </tbody>
        </table>
    <div class="second">
        <table cellspacing="0" class="inform">
            <tbody>
                <tr>
                    <th colspan="2">Vehicle Information</th>
                </tr>
                <tr>
                    <td>Unit</td>
                    <td><span><?= $this->equipmentRow['e_Unit_Number']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Owner Number</td>
                    <td><span><?= $this->equipmentRow['e_Owner_Number']; ?></span></td>
                </tr>
                <tr>
                    <td>Alternate ID</td>
                    <td><span><?= $this->equipmentRow['e_Alternate_ID']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Entry Date</td>
                    <td><span><?= $this->equipmentRow['e_Entry_Date']; ?></span></td>
                </tr>
                <tr>
                    <td>Start Mileage</td>
                    <td><span><?= $this->equipmentRow['e_Start_Mileage']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Registration State</td>
                    <td><span><?= $this->equipmentRow['e_Registration_State']; ?></span></td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td><span><?= $this->equipmentRow['e_Name']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Description</td>
                    <td><span><?= $this->equipmentRow['e_Description']; ?></span></td>
                </tr>
                <tr>
                    <td>Active Status</td>
                    <td><span><?= $this->equipmentRow['e_Active_Status']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Fee</td>
                    <td><span><?= $this->equipmentRow['e_Fee']; ?></span></td>
                </tr>
                <tr>
                    <td>Title Status</td>
                    <td><span><?= $this->equipmentRow['e_Title_Status']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Vehicle Type</td>
                    <td><span><?= $this->equipmentRow['et_type']; ?></span></td>
                </tr>
                <tr>
                    <td>DOT Regulated</td>
                    <td><span><?= $this->equipmentRow['e_DOT_Regulated']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Picture</td>
                    <td><span><?= $this->equipmentRow['e_Picture']; ?></span></td>
                </tr>
                <tr>
                    <td>Model</td>
                    <td><span><?= $this->equipmentRow['e_Model']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Year</td>
                    <td><span><?= $this->equipmentRow['e_Year']; ?></span></td>
                </tr>
                <tr>
                    <td>Make</td>
                    <td><span><?= $this->equipmentRow['e_Make']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Color</td>
                    <td><span><?= $this->equipmentRow['e_Color']; ?></span></td>
                </tr>
                <tr>
                    <td>Unladen Weight</td>
                    <td><span><?= $this->equipmentRow['e_Unladen_Weight']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Gross Vehicle Weight</td>
                    <td><span><?= $this->equipmentRow['e_Gross_Vehicle_Weight_Rating']; ?></span></td>
                </tr>
                <tr>
                    <td>Gross Vehicle Registered Weight</td>
                    <td><span><?= $this->equipmentRow['e_Gross_Vehicle_Registered_Weight']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Number Of Axles</td>
                    <td><span><?= $this->equipmentRow['e_Axles']; ?></span></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tbody></table>

        <table cellspacing="0" class="inform">
            <tbody>
                <tr>
                    <th colspan="2">
                        <span class="blue-button"><span>
                            <a href="#">Update Vehicle Information</a>
                        </span></span>
                    </th>
                </tr>
                <tr>
                    <td>License Plate Number</td>
                    <td><span><?= $this->equipmentRow['e_License_Number']; ?></span></td>
                </tr>
                <tr class="color-dark">
                    <td>License Expiration Date</td>
                    <td><span><?= $this->equipmentRow['e_License_Expiration_Date']; ?></span></td>
                </tr>
                <tr>
                    <td>Registration state</td>
                    <td><span></span></td>
                </tr>
                <tr class="color-dark">
                    <td>Radio Frequency Identify</td>
                    <td><span><?= $this->equipmentRow['e_RFID_No']; ?></span></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </div>
</div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <div class="second post">
                    <h2>Last Vehicle Inspection Information </h2>
                    <span class="blue-button"><span><a href="#">Enter New Vehicle Inspection Information</a></span></span>
                    <span class="text-red">There is no state vehicle inspection records</span>
                    <span class="text-red">There is no state vehicle inspection records</span>
                </div>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <div class="second post">
                    <h2>Vendor - Vendor Information </h2>
                    <span class="blue-button"><span><a href="#">Join The Vendor</a></span></span>
                    <p>There is no vendor joined to the truck</p>
                </div>
            </div></div></div>

    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div class="second post">
                    <h2>Driver Information </h2>
                    <span class="blue-button"><span><a href="#">Add Driver</a></span></span>
                    <p class="borderon">No drivers joined to the truck</p>
                </div>
            </div>
        </div>
    </div>

    <div class="top-nav">
        <ul class="blue-nav">
            <?=
                $this->partial('partials/_view_action.phtml', array(
                    'equipmentID' => $this->equipmentRow['e_id'],
                    'status' => $this->equipmentRow['enes_type']
                ));
            ?>
        </ul>
    </div>

</div>