<div class="bottom-nav">
    <ul class="blue-nav">
        <?=
        $this->partial('partials/_view_action.phtml', array(
            'equipmentID' => $this->equipmentRow['e_id'],
            'status' => $this->equipmentRow['enes_type'],
            'identity' => $this->identity
        ));
        ?>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>


<div class="driver-information vehicle" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div id="viewVIWdiv" class="VIWDiv">
                <table class="first">
                    <tbody>
                        <tr>
                            <td>VIN</td>
                            <td><?php echo $this->equipmentRow['e_Number'] ?></td>
                        </tr>
                        <tr>
                            <td>Entry Date</td>
                            <td><?php echo $this->equipmentRow['e_Entry_Date'] ?></td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td><?php echo $this->equipmentStatus ?></td>
                        </tr>
                    </tbody>
                </table>
                
                    <div class="second">
                        <table cellspacing="0" class="inform">
                            <tbody>
                                    <tr><th colspan="2">Vehicle Information</th></tr>
                                <tr class="color-dark">
                                    <td>Unit</td>
                                    <td><span><?= $this->equipmentRow['e_Unit_Number']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Picture</td>
                                    <td>
                                        <?php if (isset($this->equipmentRow['e_Picture']) && !empty($this->equipmentRow['e_Picture'])) : ?>
                                            <span>
                                                <a id="attachFile" href="/<?= $this->uploadPath . $this->equipmentRow['e_Picture']; ?>">
                                                    Attached file
                                                </a>
                                            </span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Vehicle Type</td>
                                    <td><span><?= $this->equipmentRow['et_type']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Start Mileage</td>
                                    <td><span><?= $this->equipmentRow['e_Start_Mileage']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Registration State</td>
                                    <td><span><?= $this->equipmentRow['s_name']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Name</td>
                                    <td><span><?= $this->equipmentRow['e_Name']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Description</td>
                                    <td><span><?= $this->equipmentRow['e_Description']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Number Of Axles</td>
                                    <td><span><?= ($this->equipmentRow['e_Axles'] == '0') ? '' : $this->equipmentRow['e_Axles']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>License Plate Number</td>
                                    <td><span><?= $this->equipmentRow['e_License_Number']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>License Expiration Date</td>
                                    <td><span><?= $this->equipmentRow['e_License_Expiration_Date']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Owner Number</td>
                                    <td><span><?= $this->equipmentRow['e_Owner_Number']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Alternate ID</td>
                                    <td><span><?= $this->equipmentRow['e_Alternate_ID']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                </tr>
                            </tbody>
                        </table>

                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">
                                        <?php if ($this->identity->permissions->equipment_create_permission === true) : ?>
                                            <span class="blue-button">
                                                <span>
                                                    <a class="VIWActionLink" id="UpdateActionLink">
                                                        Update Vehicle Information
                                                    </a>
                                                </span>
                                            </span>
                                        <?php else : ?>
                                            &nbsp;
                                        <?php endif ?>
                                    </th>
                                </tr>

                                <tr class="color-dark">
                                    <td>DOT Regulated</td>
                                    <td><span><?= $this->equipmentRow['e_DOT_Regulated']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Model</td>
                                    <td><span><?= $this->equipmentRow['e_Model']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Year</td>
                                    <td><span><?= ($this->equipmentRow['e_Year'] == '0000') ? '' : $this->equipmentRow['e_Year']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Make</td>
                                    <td><span><?= $this->equipmentRow['e_Make']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Color</td>
                                    <td><span><?= $this->equipmentRow['e_Color']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Unladen Weight</td>
                                    <td><span><?= $this->equipmentRow['e_Unladen_Weight']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Gross Vehicle Weight</td>
                                    <td><span><?= $this->equipmentRow['e_Gross_Vehicle_Weight_Rating']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Gross Vehicle Registered Weight</td>
                                    <td><span><?= $this->equipmentRow['e_Gross_Vehicle_Registered_Weight']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Title Status</td>
                                    <td><span><?= $this->equipmentRow['e_Title_Status']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>Fee</td>
                                    <td><span><?= $this->equipmentRow['e_Fee']; ?></span></td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Radio Frequency Identify</td>
                                    <td><span><?= $this->equipmentRow['e_RFID_No']; ?></span></td>
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php
                    echo $this->partial('partials/_updateVIW.phtml', array(
                            'equipmentRow' => $this->equipmentRow,
                            'equipmentTypes' => $this->equipmentTypes,
                            'states' => $this->states,
                            'equipmentStatus' => $this->equipmentStatus
                        ));
                ?>
            </div>
        </div>
    </div>

    <div class="driver-information vehicle">
        <div class="post-top">
            <div class="post-bottom">
                <div class="post-middle">
                    <div id="viewAssignmentDiv" class="AssignmentDiv">
                        <div class="second">
                            <table cellspacing="0" class="inform">
                                <tbody>
                                    <tr>
                                        <th colspan="2">
                                            Equipment Assignment
                                        </th>
                                    </tr>
                                    <?php  if(is_array($this->equipmentAssignmentRow) && count($this->equipmentAssignmentRow) > 2) : ?>
                                        <tr class="color-dark">
                                            <td>Homebase:</td>
                                            <td><span><?= isset($this->equipmentAssignmentRow['h_Name']) ? $this->equipmentAssignmentRow['h_Name'] : ''; ?></span></td>
                                        </tr>
                                        <tr class="">
                                            <td>Depot:</td>
                                            <td><span><?= isset($this->equipmentAssignmentRow['dp_Name']) ? $this->equipmentAssignmentRow['dp_Name'] : '';?></span></td>
                                        </tr>
                                        <tr class="color-dark">
                                            <td>Owner:</td>
                                            <td><span><?= isset($this->equipmentAssignmentRow['eo_name']) ? $this->equipmentAssignmentRow['eo_name'] : ''; ?></span></td>
                                        </tr>
                                    <?php else : ?>
                                        <tr class="color-dark">
                                            <td colspan="2"><span class="text-red">There is no equipment assignment </span></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr>
                                        <th colspan="2">
                                            &nbsp;
                                        </th>
                                    </tr>
                                </tbody>
                            </table>
                            <table cellspacing="0" class="inform">
                                <tbody>
                                    <tr>
                                        <th colspan="2">
                                            <?php if ($this->identity->permissions->equipment_assignment_create_permission === true) : ?>
                                                <span class="blue-button">
                                                    <span>
                                                        <a class="EquipmentAssigmentActionLink">
                                                            Update Assignment Information
                                                        </a>
                                                    </span>
                                                </span>
                                            <?php else : ?>
                                                &nbsp;
                                            <?php endif ?>
                                        </th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <?php echo
                        $this->partial('partials/_add-assignment.phtml', array(
                                'equipmentAssignmentRow' => $this->equipmentAssignmentRow,
                                'homebases' => $this->homebases,
                                'depots' => $this->depots,
                                'owners' => $this->owners,
                                'drivers' => $this->drivers,
                                'serviceProviders' => $this->serviceProviders,
                                'incidents' => $this->incidents
                            ));
                    ?>
                </div>
            </div>
        </div>
    </div>

     <div class="driver-information vehicle">
        <div class="post-top">
            <div class="post-bottom">
                <div class="post-middle">
                    <div id="viewAssignmentDiv" class="AssignmentDiv">
                        <div class="second">
                            <table cellspacing="0" class="inform">
                                <tbody>
                                    <tr>
                                        <th colspan="2">
                                            Driver Information
                                        </th>
                                    </tr>
                                    <?php  if(is_array($this->equipmentAssignmentRow) && count($this->equipmentAssignmentRow) > 2) : ?>
                                        <tr class="color-dark">
                                            <td>SSN:</td>
                                            <td><span><?= isset($this->equipmentAssignmentRow['eo_name']) ? $this->equipmentAssignmentRow['d_Driver_SSN'] : '';?></span></td>
                                        </tr>
                                        <tr>
                                            <td>First Name:</td>
                                            <td><span><?= isset($this->equipmentAssignmentRow['eo_name']) ? $this->equipmentAssignmentRow['d_First_Name'] : '';?></span></td>
                                        </tr>
                                         <tr class="color-dark">
                                            <td>Last Name:</td>
                                            <td><span><?= isset($this->equipmentAssignmentRow['eo_name']) ? $this->equipmentAssignmentRow['d_Last_Name'] : '';?></span></td>
                                        </tr>
                                    <?php else : ?>
                                        <tr class="color-dark">
                                            <td colspan="2"><span class="text-red">No drivers joined to the truck</span></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr>
                                        <th colspan="2">
                                            &nbsp;
                                        </th>
                                    </tr>
                                </tbody>
                            </table>
                             <table cellspacing="0" class="inform">
                                <tbody>
                                    <tr>
                                        <th colspan="2">
                                            &nbsp;
                                        </th>
                                    </tr>
                                </tbody>
                             </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>

    <div class="blue-nav">
        <ul>
            <?=
                $this->partial('partials/_view_action.phtml', array(
                    'equipmentID' => $this->equipmentRow['e_id'],
                    'status' => $this->equipmentRow['enes_type'],
                    'identity' => $this->identity
                ));
            ?>
        </ul>
    </div>

</div>
