<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="driver-information" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <br>
                <br>
                <table class="inform">
                    <tbody>
                        <tr>
                            <td colspan="2"><h2>VIN:&nbsp;<span class="data"><?= (isset($this->equipmentRow->e_Number)) ? $this->equipmentRow->e_Number : ''; ?></span></h2></td>
                        </tr>
                        <tr>
                            <td colspan="2"><h2>Unit Number:&nbsp;<span class="data"><?= (isset($this->equipmentRow->e_Number)) ? $this->equipmentRow->e_Unit_Number : ''; ?></span></h2></td>
                        </tr>
                    </tbody>
                </table>
                <div class="clear"></div>
                <div class="second">
                    <form class="select-parametr2" id="completeForm" method="post" action="/equipment/information-worksheet/completed/id/<?= (isset($this->equipmentRow->e_id)) ? $this->equipmentRow->e_id : ''; ?>">
                        <input type="hidden" id="e_id" name="e_id" value="<?= (isset($this->equipmentRow->e_id)) ? $this->equipmentRow->e_id : ''; ?>" />
                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">APPLICATION INFORMATION</th>
                                </tr>
                                <tr>
                                    <td>Application Date</td>
                                    <td><input disabled="disabled" id="e_Entry_Date" name="e_Entry_Date" value="<?= (isset($this->equipmentRow->e_Entry_Date)) ? $this->equipmentRow->e_Entry_Date : ''; ?>" /></td>
                                </tr>
                                <tr>
                                    <td><label><span>*</span>Date Of Vehicle Activation</label></td>
                                    <td>
                                        <input id="e_activation_date" name="e_activation_date" value="<?= (isset($this->currentDate)) ? $this->currentDate : ''; ?>" />
                                        <br />
                                        <label for="e_activation_date" generated="true" class="error" />
                                    </td>
                                </tr>
                                <tr>
                                    <th colspan="2">COMPLETION INFORMATION</th>
                                </tr>
                                <tr>
                                    <td>Name of person completing the application</td>
                                    <td><?= (isset($this->person)) ? $this->person : ''; ?></td>
                                </tr>
                                <tr class="color-dark">
                                    <td></td>
                                    <td><span><label>*</label></span>
                                        <input id="wantCopleteCheckBox"  name="wantCopleteCheckBox" type="checkbox"> <b>Yes, I want to complete application for vehicle</b>
                                        <br />
                                        <label for="wantCopleteCheckBox" generated="true" class="error" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>Comment</td>
                                    <td><textarea id="e_activation_comment" name="e_activation_comment"></textarea></td>
                                </tr>
<!--                                <tr>
                                    <td align="center" colspan="2">
                                        <input type="submit" value="Cancel">
                                        <input type="submit" value="Complete">
                                    </td>
                                </tr>-->
                            </tbody></table>
                    </form>
                    <div class="blue-nav">
                        <ul>
                            <li>
                                <span>
                                    <a id="completeLink">
                                        Save
                                    </a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="/equipment/information-worksheet/validate-completed/id/<?= (isset($this->equipmentRow->e_id)) ? $this->equipmentRow->e_id : ''; ?>">
                                        Exit
                                    </a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <br><br>
                </div>
            </div>
        </div>
    </div>
</div>