<div class="bottom-nav">
    <ul class="blue-nav">
        <li>
            <span>
                <a id="equipmentSaveLink1">
                    Save
                </a>
            </span>
        </li>
        <li>
            <span>
                <a href="/equipment/list">
                    Exit
                </a>
            </span>
        </li>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>


<div class="driver-information equipment" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <form id="updateVIM" method="post"
                      enctype="multipart/form-data"
                      action="/equipment/information-worksheet/save-vim/id/<?php echo $this->equipmentRow['e_id']; ?>">
                    <table class="first">
                        <tbody>
                            <tr>
                                <td>EIN</td>
                                <td>
                                    <input type="hidden" value="<?= $this->equipmentRow['e_id']; ?>" id="e_id" name="e_id" />
                                    <input type="text" disabled="disabled" value="<?= $this->equipmentRow['e_Number']; ?>"
                                           id="e_Number" name="e_Number" />
                                </td>
                            </tr>
                            <tr>
                                <td>Entry Date</td>
                                <td>
                                    <input type="text" disabled="disabled" value="<?= $this->equipmentRow['e_Entry_Date']; ?>"
                                           id="e_Entry_Date" name="e_Entry_Date" />
                                </td>
                            </tr>
                            <tr>
                                <td>Status</td>
                                <td>
                                    <input type="text" disabled="disabled" value="<?= $this->equipmentRow['enes_type']; ?>"
                                           id="e_New_Equipment_Status" name="e_New_Equipment_Status" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="second">
                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">Equipment Information</th>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Unit</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Unit_Number']; ?>"
                                               id="e_Unit_Number" name="e_Unit_Number" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Equipment Type</label></td>
                                    <td>
                                        <select  class="rc10" name="e_type_id" id="e_type_id">
                                            <?php
                                            foreach ($this->equipmentTypes as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">' . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text'] . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>DOT Regulated</label></td>
                                    <td>

                                        <span class="radio-button">
                                            <?php if ($this->equipmentRow['e_DOT_Regulated'] == 'Yes') : ?>
                                                <input type="radio" name="e_DOT_Regulated" id="e_DOT_Regulated" value="Yes" checked="checked">
                                            <?php else : ?>
                                                <input type="radio" name="e_DOT_Regulated" id="e_DOT_Regulated" value="Yes">
                                            <?php endif; ?>
                                            &nbsp;Yes
                                        </span>
                                        <span class="radio-button">
                                            <?php if ($this->equipmentRow['e_DOT_Regulated'] == 'Yes') : ?>
                                                <input type="radio" name="e_DOT_Regulated" id="e_DOT_Regulated" value="No" checked="checked">
                                            <?php else : ?>
                                                <input type="radio" name="e_DOT_Regulated" id="e_DOT_Regulated" value="No">
                                            <?php endif; ?>
                                            &nbsp;No
                                        </span>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Start Mileage</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Start_Mileage']; ?>"
                                               id="e_Start_Mileage" name="e_Start_Mileage" />
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Registration State</label></td>
                                    <td>
                                        <select  class="rc10" name="e_Registration_State" id="e_Registration_State">
                                            <?php
                                            foreach ($this->states as $key => $value) {
                                                if (isset($value['selected']) && $value['selected']) {
                                                    echo '<option selected="selected" value="' . $key . '">'
                                                            . $value['text'] . '</option>';
                                                } else {
                                                    echo '<option value="' . $key . '">' . $value['text']
                                                            . '</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Name</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Name']; ?>"
                                               id="e_Name" name="e_Name" />
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Description</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Description']; ?>"
                                               id="e_Description" name="e_Description" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Number Of Axles</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Axles']; ?>"
                                               id="e_Axles" name="e_Axles" />
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Title Status</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_License_Number']; ?>"
                                               id="e_License_Number" name="e_License_Number" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>License Expiration Date</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_License_Expiration_Date']; ?>" id="e_License_Expiration_Date" name="e_License_Expiration_Date" />
                                        <br />
                                        <label>(mm/dd/yyyy)</label>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Owner Number</td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Owner_Number']; ?>"
                                               id="e_Owner_Number" name="e_Owner_Number" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td>Alternate ID</td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Alternate_ID']; ?>"
                                               id="e_Alternate_ID" name="e_Alternate_ID" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>Radio Frequency Identify</td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_RFID_No']; ?>"
                                               id="e_RFID_No" name="e_RFID_No" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <table cellspacing="0" class="inform">
                            <tbody>
                                <tr>
                                    <th colspan="2">
                                        &nbsp;
                                    </th>
                                </tr>
                                <tr>
                                    <td>Picture</td>
                                    <td>
                                        <input type="file" value="<?= $this->equipmentRow['e_Picture']; ?>"
                                               id="e_Picture" name="e_Picture" />
                                        <label>Size limit is 2mb (jpeg or tiff only)</label>
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Model</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Model']; ?>"
                                               id="e_Model" name="e_Model" />
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Year</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Year']; ?>"
                                               id="e_Year" name="e_Year" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Make</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Make']; ?>"
                                               id="e_Make" name="e_Make" />
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Color</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Color']; ?>"
                                               id="e_Color" name="e_Color" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Unladen Weight</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Unladen_Weight']; ?>"
                                               id="e_Unladen_Weight" name="e_Unladen_Weight" />
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="required"><span>*</span>Gross Equipment Registered Weight</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Gross_Equipment_Registered_Weight']; ?>"
                                               id="e_Gross_Equipment_Registered_Weight" name="e_Gross_Equipment_Registered_Weight" />
                                    </td>
                                </tr>
                                <tr class="color-dark">
                                    <td><label class="required"><span>*</span>Gross Equipment Weight</label></td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Gross_Equipment_Weight_Rating']; ?>"
                                               id="e_Gross_Equipment_Weight_Rating" name="e_Gross_Equipment_Weight_Rating" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>Title Status</td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Title_Status']; ?>"
                                               id="e_Title_Status" name="e_Title_Status" />
                                    </td>
                                </tr>
                                <tr  class="color-dark">
                                    <td>Fee</td>
                                    <td>
                                        <input type="text" value="<?= $this->equipmentRow['e_Fee']; ?>"
                                               id="e_Fee" name="e_Fee" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="blue-nav">
        <ul>
            <li>
                <span>
                    <a id="equipmentSaveLink2">
                        Save
                    </a>
                </span>
            </li>
            <li>
                <span>
                    <a href="/equipment/list">
                        Exit
                    </a>
                </span>
            </li>
        </ul>
    </div>

</div>
