<table class="first">
    <tbody>
        <tr>
            <td>EIN</td>
            <td><?= $this->layout()->equipmentRow['e_Number'] ?></td>
        </tr>
        <tr>
            <td>Unit Number</td>
            <td><?= isset($this->layout()->equipmentRow['e_Unit_Number']) ? $this->layout()->equipmentRow['e_Unit_Number'] : ''; ?></td>
        </tr>
        <tr>
            <td>Entry Date</td>
            <td><?= $this->layout()->equipmentRow['e_Entry_Date'] ?></td>
        </tr>
        <tr>
            <td>Status</td>
            <td><?= $this->layout()->equipmentStatus ?></td>
        </tr>
    </tbody>
</table>

<div class="second">
    <table cellspacing="0" class="inform">
        <tbody>
                <tr><th colspan="2">Equipment Information</th></tr>
            <tr class="color-dark">
                <td>Unit Number</td>
                <td><span><?= $this->layout()->equipmentRow['e_Unit_Number']; ?></span></td>
            </tr>
            <tr>
                <td>Picture</td>
                <td>
                    <?php if (isset($this->layout()->equipmentRow['e_Picture']) && !empty($this->layout()->equipmentRow['e_Picture'])) : ?>
                        <span>
                            <a id="attachFile" href="/<?= $this->layout()->uploadPath . $this->layout()->equipmentRow['e_Picture']; ?>">
                                Attached file
                            </a>
                        </span>
                    <?php endif; ?>
                </td>
            </tr>
            <tr class="color-dark">
                <td>Type</td>
                <td><span><?= $this->layout()->equipmentRow['et_type']; ?></span></td>
            </tr>
            <tr>
                <td>Start Mileage</td>
                <td><span><?= $this->layout()->equipmentRow['e_Start_Mileage']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Registration State</td>
                <td><span><?= $this->layout()->equipmentRow['s_name']; ?></span></td>
            </tr>
            <tr>
                <td>Name</td>
                <td><span><?= $this->layout()->equipmentRow['e_Name']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Description</td>
                <td><span><?= $this->layout()->equipmentRow['e_Description']; ?></span></td>
            </tr>
            <tr>
                <td>Number Of Axles</td>
                <td><span><?= ($this->layout()->equipmentRow['e_Axles'] == '0') ? '' : $this->layout()->equipmentRow['e_Axles']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>DOT Regulated</td>
                <td><span><?= $this->layout()->equipmentRow['e_DOT_Regulated']; ?></span></td>
            </tr>
            <tr>
                <td>Fee</td>
                <td><span><?= $this->layout()->equipmentRow['e_Fee']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Alternate ID</td>
                <td><span><?= $this->layout()->equipmentRow['e_Alternate_ID']; ?></span></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>

    <table cellspacing="0" class="inform">
        <tbody>
            <tr>
                <th colspan="2">
                    <?php if ($this->identity->permissions->equipment_create_permission === true) : ?>
                        <span class="blue-button">
                            <span>
                                <a class="VIWActionLink" id="UpdateActionLink" onclick="hideViewVIW();">
                                    Update Equipment Information
                                </a>
                            </span>
                        </span>
                    <?php else : ?>
                        &nbsp;
                    <?php endif ?>
                </th>
            </tr>
            <tr class="color-dark">
                <td>License Plate Number</td>
                <td><span><?= $this->layout()->equipmentRow['e_License_Number']; ?></span></td>
            </tr>
            <tr>
                <td>License Expiration Date</td>
                <td><span><?= $this->layout()->equipmentRow['e_License_Expiration_Date']; ?></span></td>
            </tr>
            
            <tr class="color-dark">
                <td>Year</td>
                <td><span><?= ($this->layout()->equipmentRow['e_Year'] == '0000') ? '' : $this->layout()->equipmentRow['e_Year']; ?></span></td>
            </tr>
            <tr>
                <td>Make</td>
                <td><span><?= $this->layout()->equipmentRow['e_Make']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Color</td>
                <td><span><?= $this->layout()->equipmentRow['e_Color']; ?></span></td>
            </tr>
            <tr>
                <td>Unladen Weight</td>
                <td><span><?= $this->layout()->equipmentRow['e_Unladen_Weight']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Gross Equipment Registered Weight</td>
                <td><span><?= $this->layout()->equipmentRow['e_Gross_Equipment_Registered_Weight']; ?></span></td>
            </tr>
            <tr>
                <td>Gross Equipment Weight</td>
                <td><span><?= $this->layout()->equipmentRow['e_Gross_Equipment_Weight_Rating']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Model</td>
                <td><span><?= $this->layout()->equipmentRow['e_Model']; ?></span></td>
            </tr>
            <tr>
                <td>Title Status</td>
                <td><span><?= $this->layout()->equipmentRow['e_Title_Status']; ?></span></td>
            </tr>
            <tr class="color-dark">
                <td>Radio Frequency Identify</td>
                <td><span><?= $this->layout()->equipmentRow['e_RFID_No']; ?></span></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>
</div>