
          <div class="bottom-nav">
            <form class="status" name="driver_get_list_by_status" id="driver_get_list_by_status" method="GET" enctype="application/x-www-form-urlencoded" action="/driver/index/index">
              <fieldset>
                <label>Status:</label>
                <select name="status" onmousedown="">
                  <option value="0" <?php if($this->status==0){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">All</option>
                  <option value="1" <?php if($this->status==1){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">Pending</option>
                  <option value="2" <?php if($this->status==2){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">Applicant</option>
                  <option value="3" <?php if($this->status==3){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">Hired - Active</option>
                  <option value="4" <?php if($this->status==4){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">Hired - Inactive</option>
                  <option value="5" <?php if($this->status==5){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">Terminated</option>
                </select>
              </fieldset>
            </form>

            <form class="search" action="#">
              <fieldset>
                <label>Search By:</label>
                <select>
                  <option selected="selected"> - </option>
                  <option>All</option>
                  <option>Name</option>
                  <option>SSN</option>
                  <option>Date Of Birth</option>
                </select>
                <input type="text" value=""/>
                <input type="submit" value=""/>
              </fieldset>
            </form>
          </div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>
<ul class="blue-nav">
   <li><span><a href="/driver/new-driver/new-driver-search">Add New Driver</a></span></li>
</ul>
    <div id="main" class="driver-profile">

      <table class="application-forms" cellspacing="0">
      <tr class="table-title">
          <td><a href="" class="whiteLink" >First Name</a></td>
          <td><a href="" class="whiteLink" >Last Name</a></td>
          <td><a href="" class="whiteLink" >SSN</a></td>
          <td><a href="" class="whiteLink" >DOB</a></td>
          <td><a href="" class="whiteLink" >Status</a></td>
          <td><a href="" class="whiteLink" >Employment Type</a> / <a href="" class="whiteLink" >Date of Hire</a></td>
          <td><a href=""  class="whiteLink">Action</a></td>
        </tr>

<?php

      if ($this->Drivers != null) {
?>
        <?php echo $this->partialLoop('partials/_driver-row.phtml', $this->Drivers); ?>

    <?php } ?>
<tr><td class="page" colspan="7"> DQF  <?php echo $this->from;?> to <?php echo $this->from+$this->step;?>  ( <?php echo sizeof($this->allDrivers);?> )</td></tr>
<tr><td class="page" colspan="7">  <?php echo $this->partial('partials/_pagignator.phtml',array('drivers' => $this->allDrivers, 'from' => $this->from, 'last' => $this->from+$this->step, 'step' => $this->step, 'status' => $this->status)); ?></td></tr>
		</Table>


    </div>