
          <div class="bottom-nav">
            <form class="status" name="driver_get_list_by_status" id="driver_get_list_by_status" method="GET" enctype="application/x-www-form-urlencoded" action="/driver/index/index">
              <fieldset>
                <label>Status:</label>
                <select name="status" onmousedown="">
                  <option value="All" <?php if($this->statusId==0){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">All</option>
                <?php
                    foreach($this->driverStatusList as $k => $v){?>
                        <option value="<?php echo $v;?>" <?php if($v == $this->status){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();"><?php echo $v;?></option>
                <?php
                  }
                  ?>
                </select>
              </fieldset>
            </form>

            <form class="search" action="#">
              <fieldset>
                <label>Search By:</label>
                <select name="search_by" id="search_by">
                  <option selected="selected" value="all">All</option>
                  <option value="name">Name</option>
                  <option value="ssn">SSN</option>
                  <option value="dob">Date Of Birth</option>
                </select>
                <input type="text" id="search_by_value" name="search_by_value" value=""/>
                <input type="submit" value=""/>
              </fieldset>
            </form>
          </div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>
<ul class="blue-nav">
   <li><span><a href="/driver/new-driver/new-driver-search">Add New Driver</a></span></li>
</ul>
    <div id="main" class="driver-profile">

      <table class="application-forms" cellspacing="0">
      <tr class="table-title">
          <td><a href="" class="whiteLink" >First Name</a></td>
          <td><a href="" class="whiteLink" >Last Name</a></td>
          <td><a href="" class="whiteLink" >SSN</a></td>
          <td><a href="" class="whiteLink" >DOB</a></td>
          <td><a href="" class="whiteLink" >Status</a></td>
          <td><a href="" class="whiteLink" >Employment Type</a> / <a href="" class="whiteLink" >Date of Hire</a></td>
          <td><a href=""  class="whiteLink">Action</a></td>
        </tr>

<?php

      if ($this->Drivers != null) {
?>
        <?php echo $this->partialLoop('partials/_driver-row.phtml', $this->Drivers); ?>

    <?php } ?>
<tr><td class="page" colspan="7"> DQF
    <?php
        if($this->page=="1")
        {
            echo $this->page;
        }elseif($this->page>1)
        {
            echo (6*($this->page-1));
        }
    ?> to <?php
        if((6*($this->page))<sizeof($this->allDrivers)){
            echo (6*($this->page));
        }else{
            echo sizeof($this->allDrivers);
        }
    ?>  ( <?php echo sizeof($this->allDrivers);?> )</td></tr>
<tr>
    <td class="page" id="paginator" colspan="7">
        <?php echo $this->partial('partials/_paginator.phtml',array('drivers' => $this->allDrivers, 'page' => $this->page, 'status' => $this->status)); ?>
    </td></tr>
		</Table>


    </div>