          <div class="bottom-nav">
            <form class="status" name="driver_get_list_by_status" id="driver_get_list_by_status" method="GET" enctype="application/x-www-form-urlencoded" action="/driver/index/involved-in-incident-drivers/incident_id/<?php echo $this->incident_id;?>/">
              <fieldset>
                <label>Status:</label>
                <select name="status" onmousedown="">
                  <option value="All" <?php if($this->statusId==0){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();">All</option>
                <?php
                    foreach($this->driverStatusList as $k => $v){
                        if($v!="Pending"){
                ?>
                        <option value="<?php echo $v;?>" <?php if($v == $this->status){ ?> selected="selected" <?php } ?> onclick="document['driver_get_list_by_status'].submit();"><?php echo $v;?></option>
                <?php
                        }
                    }
                  ?>
                </select>
              </fieldset>
            </form>

            <form class="search" action="#">
              <fieldset>
                <label>Search By:</label>
                <select name="search_by" id="search_by">
                  <option selected="selected" value="all">All</option>
                  <option value="name">Name</option>
                  <option value="ssn">SSN</option>
                  <option value="dob">Date Of Birth</option>
                </select>
                <input type="text" id="search_by_value" name="search_by_value" value=""/>
                <input type="submit" value=""/>
              </fieldset>
            </form>
          </div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>
    <div id="main" class="driver-profile">

      <table class="application-forms" cellspacing="0">
      <tr class="table-title">
          <td><a href="<?php echo preg_replace("/[\?\&]order_by[=][a-zA-Z0-9_\-]+\-[ascdesc]+/","",$_SERVER['REQUEST_URI'])."&order_by=d_First_Name-"; if($this->orderBy[0]=="d_First_Name"){echo $this->orderBy[1];}else{echo "asc";} ?>" class="whiteLink" >First Name</a></td>
          <td><a href="<?php echo preg_replace("/[\?\&]order_by[=][a-zA-Z0-9_\-]+\-[ascdesc]+/","",$_SERVER['REQUEST_URI'])."&order_by=d_Last_Name-"; if($this->orderBy[0]=="d_Last_Name"){echo $this->orderBy[1];}else{echo "asc";} ?>" class="whiteLink" >Last Name</a></td>
          <td><a href="<?php echo preg_replace("/[\?\&]order_by[=][a-zA-Z0-9_\-]+\-[ascdesc]+/","",$_SERVER['REQUEST_URI'])."&order_by=d_Date_Of_Birth-"; if($this->orderBy[0]=="d_Date_Of_Birth"){echo $this->orderBy[1];}else{echo "asc";} ?>" class="whiteLink" >DOB</a></td>
          <td><a href="<?php echo preg_replace("/[\?\&]order_by[=][a-zA-Z0-9_\-]+\-[ascdesc]+/","",$_SERVER['REQUEST_URI'])."&order_by=d_Status-"; if($this->orderBy[0]=="d_Status"){echo $this->orderBy[1];}else{echo "asc";} ?>" class="whiteLink" >Status</a></td>
          <td><a href="<?php echo preg_replace("/[\?\&]order_by[=][a-zA-Z0-9_\-]+\-[ascdesc]+/","",$_SERVER['REQUEST_URI'])."&order_by=d_Date_Of_Hire-"; if($this->orderBy[0]=="d_Date_Of_Hire"){echo $this->orderBy[1];}else{echo "asc";} ?>" class="whiteLink" >Date Of Hire</a></td>
          <td><a class="whiteLink" >Truck Number</a></td>
          <td><a href="<?php echo preg_replace("/[\?\&]order_by[=][a-zA-Z0-9_\-]+\-[ascdesc]+/","",$_SERVER['REQUEST_URI'])."&order_by=d_DOT_Regulated-"; if($this->orderBy[0]=="d_DOT_Regulated"){echo $this->orderBy[1];}else{echo "asc";} ?>" class="whiteLink" >NSC Check</a></td>
          <td><a class="whiteLink">Action</a></td>
        </tr>

<?php

      if ($this->Drivers != null) {
?>
        <?php echo $this->partial('partials/_involved-in-incident-drivers-row.phtml', array('drivers'=>$this->Drivers,'incidentID'=>$this->incident_id)); ?>

    <?php } ?>
<tr><td class="page" colspan="8"> DQF
    <?php
        if($this->page=="1")
        {
            echo $this->page;
        }elseif($this->page>1)
        {
            echo (20*($this->page-1));
        }
    ?> to <?php
        if((20*($this->page))<sizeof($this->allDrivers)){
            echo (20*($this->page));
        }else{
            echo sizeof($this->allDrivers);
        }
    ?>  ( <?php echo sizeof($this->allDrivers);?> )</td></tr>
<tr>
    <td class="page" id="paginator" colspan="8">
        <?php echo $this->partial('partials/_paginator-dqf.phtml',array('drivers' => $this->allDrivers, 'page' => $this->page, 'status' => $this->status)); ?>
    </td></tr>
		</Table>


    </div>