          <div class="bottom-nav">
            <span class="name-driver">Driver:&nbsp;<span>Rene Del Rio</span></span>
          </div>
 
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
            <a class="show-legend" href="#" onClick="$('#legend').slideToggle();">Show legend</a>
        </div>
    </div>
</div>
          <div id="legend">
             <table>
             <tr>
                 <td><img src="/images/ico-6.gif" alt="Form is Completed" align="absmiddle" /> Form is Completed</td>
                 <td><img src="/images/ico-7.gif" alt="Form is NOT Completed" align="absmiddle" /> Form is NOT Completed</td>
                 <td><img src="/images/ico-8.gif" alt="Scan / Upload Documents" align="absmiddle" /> Scan / Upload Documents</td>
                 <td><img src="/images/ico-3.gif" alt="View PDF Document" align="absmiddle" /> View PDF Document</td>
             </tr>
             <tr>
                 <td><img src="/images/ico-4.gif" alt="View Signed Document" align="absmiddle" /> View Signed Document</td>
                 <td><img src="/images/ico-2.gif" alt="Delete Form / Document" align="absmiddle" /> Delete Form / Document</td>
                 <td><img src="/images/ico-1.gif" alt="Checked by NSC Compliant" align="absmiddle" /> Checked by NSC Compliant</td>
                 <td><img src="/images/ico-9.gif" alt="Checked by NSC Not Compliant" align="absmiddle" /> Checked by NSC Not Compliant</td>
             </tr>
             </table>
           </div>
    <div id="main" class="qualification-file">

      <table class="application-forms" cellspacing="0">
        <tr><th colspan="8">APPLICATION FORMS</th></tr>
        <tr class="table-title">
          <td>Form Name</td>
          <td>Status</td>

          <td>Date Requested</td>
          <td>Date Completed</td>
          <td>Scan</td>
          <td>View</td>
          <td>Delete</td>
          <td>NSC Check</td>

        </tr>
            <?php echo $this->partial('partials/_dqf-form-row.phtml',array('documentsFormList' => $this->documentsFormList,'driverInfo' => $this->driverInfo)); ?>

        
        <tr><td colspan="8">&nbsp;</td></tr>
      </table>

      <div class="post">
        <h2>Other Available Actions</h2>

        <div class="col">
          <ul>
            <li>Driver Actions<ul>
              <li><a href="#">View/Update Driver Profile (DIW)</a></li></ul></li>
          </ul>
          <ul>
            <li>Documents Actions<ul>

              <li><a href="#">Scan Required Documents (R/A, CDL, etc.)</a></li>
              <li><a href="#">Scan Other Documents</a></li>
              <li><a href="#">Capture Picture</a></li></ul></li>
          </ul>
          <ul>
            <li>Forms Actions<ul>
              <li><a href="#">Request New Forms</a></li>

              <li><a href="#">Re-Scan the form with barcode</a></li>
              <li><a href="#">Timestamps For Forms Faxed To Previous Employers</a></li></ul></li>
          </ul>
          <ul>
            <li>Renewal Actions<ul>
              <li><a href="#">Annual Review of Motor Vehicle Report</a></li>
              <li><a href="#">Request Record of Violations</a></li></ul></li>

          </ul>
        </div>
        <div class="col">
          <ul>
            <li>Driver Termination<ul>
              <li><a href="#">Create Federal Disqualification - Part 383 Form</a></li>
              <li><a href="#">Create Disqualification of Drivers - Part 391 Form</a></li>
              <li><a href="#">Terminate Driver</a></li></ul></li>

          </ul>
          <ul>
            <li>Print Actions<ul>
              <li><a href="#">Print All Completed Forms and Docs</a></li>
              <li><a href="#">Print This Checklist</a></li></ul></li>
          </ul>
          <ul>

            <li>Other Actions<ul>
              <li><a href="#">NSC Check</a></li></ul></li>
          </ul>
        </div>
      </div>

    </div>
