          <div class="bottom-nav">
            <span class="name-driver">Driver:&nbsp;<span>Rene Del Rio</span></span>
            <form class="status" action="#">
              <fieldset>
                <label>Status:</label>

                <select>
                  <option selected="selected">All</option>
                  <option>Applicant</option>
                  <option>Hired</option>
                  <option>Active</option>
                  <option>Inactive</option></select>

                  <input type="submit" value=""/>
              </fieldset>
            </form>
          </div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

    <div id="main" class="qualification-file">

      <table class="application-forms" cellspacing="0">
        <tr><th colspan="8">APPLICATION FORMS</th></tr>
        <tr class="table-title">
          <td>Form Name</td>
          <td>Status</td>

          <td>Date Requested</td>
          <td>Date Completed</td>
          <td>Scan</td>
          <td>View</td>
          <td>Delete</td>
          <td>NSC Check</td>

        </tr>
        <tr>
          <td>Application For Employment</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>

          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr class="color-dark">
          <td>Certification Of Compliance With Driver License Requirements</td>
          <td><img src="/images/ico-7.gif" alt=""/></td>
          <td>6/20/2008</td>

          <td></td>
          <td><img src="/images/ico-5.gif" alt=""/></td>
          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td></td>
        </tr>
        <tr>
          <td>Employment Eligibility Verification</td>

          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>

        <tr class="color-dark">
          <td>Request For Information From Previous Employer  <a href="#">Bridgestone</a> / <a href="#">Firestone</a></td>
          <td><img src="/images/ico-7.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td></td>
          <td><img src="/images/ico-5.gif" alt=""/></td>

          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td></td>
        </tr>
        <tr>
          <td>Request For Information From Previous Employer <a href="#">Pep Boys</a></td>
          <td><img src="/images/ico-7.gif" alt=""/></td>
          <td>6/20/2008</td>

          <td></td>
          <td><img src="/images/ico-5.gif" alt=""/></td>
          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td></td>
        </tr>
        <tr class="color-dark">
          <td>Request/Consent For Alcohol And Controlled Substance Information </td>

          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>

        <tr>
          <td>Request/Consent For Alcohol And Controlled Substance Information </td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>

          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr class="color-dark">
          <td>Request for Motor Vehicle Report</td>
          <td><img src="/images/ico-7.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td></td>

          <td><img src="/images/ico-5.gif" alt=""/></td>
          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td></td>
        </tr>
        <tr>
          <td>Record Of Road Test</td>
          <td><img src="/images/ico-7.gif" alt=""/></td>

          <td>6/20/2008</td>
          <td></td>
          <td><img src="/images/ico-5.gif" alt=""/></td>
          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td></td>
        </tr>
        <tr class="color-dark">

          <td>Driver Data Sheet</td>
          <td><img src="/images/ico-7.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td></td>
          <td><img src="/images/ico-5.gif" alt=""/></td>
          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td></td>

        </tr>
        <tr><td colspan="8">&nbsp;</td></tr>
      </table>

      <table class="application-forms" cellspacing="0">
        <tr><th colspan="8">RENEWAL AND TERMINATION FORMS</th></tr>
        <tr class="table-title">
          <td>Form Name</td>
          <td>Status</td>

          <td>Date Requested</td>
          <td>Date Completed</td>
          <td>Scan</td>
          <td>View</td>
          <td>Delete</td>
          <td>NSC Check</td></tr>

        <tr class="color-dark">
          <td>Certification Of Violations</td>
          <td><img src="/images/ico-7.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td></td>
          <td><img src="/images/ico-5.gif" alt=""/></td>
          <td><img src="/images/ico-4.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>

          <td></td>
        </tr>
        <tr><td colspan="8">&nbsp;</td></tr>
      </table>

      <table class="application-forms" cellspacing="0">
        <tr><th colspan="8">RENEWAL AND TERMINATION FORMS</th></tr>
        <tr class="table-title"><td>Form Name</td><td>Status</td><td>Date Requested</td><td>Date Completed</td><td>Scan</td><td>View</td><td>Delete</td><td>NSC Check</td></tr>

        <tr>
          <td>Medical Card</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>

          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr class="color-dark">
          <td>Medical Card</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>

          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr>
          <td>Commercial Driver License</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>

          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr class="color-dark">

          <td>Commercial Driver License</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>

          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr>
          <td>Social Security Card</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>

          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr class="color-dark">
          <td>Motor Vehicle Report (MVR)</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>

          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-9.gif" alt=""/></td>
        </tr>
        <tr>

          <td>Driver's Physical Examination Form</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>
          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr class="color-dark">
          <td>Driver's Physical Examination Form</td>
          <td><img src="/images/ico-6.gif" alt=""/></td>
          <td>6/20/2008</td>
          <td>6/20/2008</td>

          <td><img src="/images/ico-8.gif" alt=""/></td>
          <td><img src="/images/ico-3.gif" alt=""/></td>
          <td><img src="/images/ico-2.gif" alt=""/></td>
          <td><img src="/images/ico-1.gif" alt=""/></td>
        </tr>
        <tr><td colspan="8">&nbsp;</td></tr>
      </table>

      <div class="post">
        <h2>Other Available Actions</h2>

        <div class="col">
          <ul>
            <li>Driver Actions<ul>
              <li><a href="#">View/Update Driver Profile (DIW)</a></li></ul></li>
          </ul>
          <ul>
            <li>Documents Actions<ul>

              <li><a href="#">Scan Required Documents (R/A, CDL, etc.)</a></li>
              <li><a href="#">Scan Other Documents</a></li>
              <li><a href="#">Capture Picture</a></li></ul></li>
          </ul>
          <ul>
            <li>Forms Actions<ul>
              <li><a href="#">Request New Forms</a></li>

              <li><a href="#">Re-Scan the form with barcode</a></li>
              <li><a href="#">Timestamps For Forms Faxed To Previous Employers</a></li></ul></li>
          </ul>
          <ul>
            <li>Renewal Actions<ul>
              <li><a href="#">Annual Review of Motor Vehicle Report</a></li>
              <li><a href="#">Request Record of Violations</a></li></ul></li>

          </ul>
        </div>
        <div class="col">
          <ul>
            <li>Driver Termination<ul>
              <li><a href="#">Create Federal Disqualification - Part 383 Form</a></li>
              <li><a href="#">Create Disqualification of Drivers - Part 391 Form</a></li>
              <li><a href="#">Terminate Driver</a></li></ul></li>

          </ul>
          <ul>
            <li>Print Actions<ul>
              <li><a href="#">Print All Completed Forms and Docs</a></li>
              <li><a href="#">Print This Checklist</a></li></ul></li>
          </ul>
          <ul>

            <li>Other Actions<ul>
              <li><a href="#">NSC Check</a></li></ul></li>
          </ul>
        </div>
      </div>

    </div>
