
<div class="bottom-nav">
    <ul class="blue-nav">
        <li><span><a href="/driver/Driver/Driver-Complete/id/<?php echo $this->driverId;?>" >Complete</a></span></li>
    </ul>
    <ul class="blue-nav">
        <li><span><a href="/driver/Driver/Driver-Decline/id/<?php echo $this->driverId;?>" >Decline</a></li>
    </ul>
</div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>
<?php
    $date = new Zend_Date();
?>
<div class="driver-information" id="main">

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody>
        <tr><th colspan="2">Application Information [ <a id="toggleDriverInfoEdit">EDIT</a> ]</th></tr>
        </tbody>
    </table>
    <table cellspacing="0" class="inform" id="idDriverInfoView">
        <tbody>    
        <tr><td>Application Type</td>
            <td><span><?php echo $_SESSION['driver_info']['DriverEmploymentType_list'][$this->driverInfo['d_Employment_Type']];?></span></td>
        </tr>
        <tr class="color-dark"><td>Entry Date</td>
            <td><span>
                  <?php
                        $date->set($this->driverInfo['d_Entry_Date'],"YYYY-MM-dd");
                  echo  $date->toString("MM/dd/YYYY");
                  ?></span></td>
        </tr>
        <tr><td>Date Of Hire</td><td><span><?php echo $this->driverInfo['d_Date_Of_Hire']; ?></span></td></tr>
        <tr class="color-dark"><td>Status</td><td><span><?php echo $_SESSION['driver_info']['DriverStatus_list'][$this->driverInfo['d_Status']];?></span></td></tr>
        <tr><td>Home Base Location</td><td><?php echo $this->homebase['h_Name'];?></td></tr>
        <tr class="color-dark"><td>Depot</td><td><?php echo $this->depot['dp_Name'];?></td></tr>
        <tr><th colspan="2">Driver Information</th></tr>
        <tr>
            <td>Driver Name</td>
            <td>First:&nbsp;<span><?php echo $this->driverInfo['d_First_Name']; ?></span>
                Last:&nbsp;<span><?php echo $this->driverInfo['d_Last_Name']; ?></span>
                Middle:&nbsp;<span><?php echo $this->driverInfo['d_Middle_Name']; ?></span></td></tr>
        <tr class="color-dark"><td>Date Of Birth</td><td><span><?php
                        $date->set($this->driverInfo['d_Date_Of_Birth'],"YYYY-MM-dd");
                  echo  $date->toString("MM/dd/YYYY");
                  ?></span></td></tr>
        <tr><td>Social Security #</td><td><span><?php echo $this->driverInfo['d_Driver_SSN']; ?></span></td></tr>
        <tr class="color-dark">
            <td>Medical Card</td>
            <td>Expires:&nbsp;<span><?php
                        if(isset($this->driverInfo['d_Medical_Card_Expiration_Date'])){
                        $date->set($this->driverInfo['d_Medical_Card_Expiration_Date'],"YYYY-MM-dd");
                  echo  $date->toString("MM/dd/YYYY");}
                  ?></span>
                Medical Examiner's Name:&nbsp;<span><?php echo $this->driverInfo['d_Doctor_Name']; ?></span></td></tr>
        <tr>
            <td>Phone Information</td>
            <td>#1 phone number:&nbsp;<span><?php echo $this->driverInfo['d_Telephone_Number1']; ?></span><br/>
            <?php
                                  if($this->driverInfo['d_Telephone_Number2']!=""){
                ?>
                    #2 phone number:&nbsp;<span><?php echo $this->driverInfo['d_Telephone_Number2']; ?></span><br/>
                <?
            }
            ?>
            <?php
                                  if($this->driverInfo['d_Telephone_Number3']!=""){
                ?>
                    #3 phone number:&nbsp;<span><?php echo $this->driverInfo['d_Telephone_Number3']; ?></span><br/>
                <?
            }
            ?>
            </td></tr>
        <?php
                              if($this->driverInfo['d_Fax']!=""){
            ?>
            <tr class="color-dark"><td>Fax </td>
                <td><span><?php echo $this->driverInfo['d_Fax']; ?></span></td></tr>
            <?
        }
        ?>
        <tr class="color-dark"><td>TWIC #:</td><td><span><?php echo $this->driverInfo['d_TWIC']; ?></span></td></tr>
        <tr><td>TWIC expiration date:</td><td><span>
                  <?php
                        if(isset($this->driverInfo['d_TWIC_expiration'])){
                            $date->set($this->driverInfo['d_TWIC_expiration'],"YYYY-MM-dd");
                            echo  $date->toString("MM/dd/YYYY");
                        }
                  ?></span></td></tr>
        <tr class="color-dark"><td>R/A card #:</td><td><span><?php echo $this->driverInfo['d_R_A']; ?></span></td></tr>
        <tr><td>R/A card expiration date:</td><td><span>
                  <?php
                        if(isset($this->driverInfo['d_R_A_expiration'])){
                            $date->set($this->driverInfo['d_R_A_expiration'],"YYYY-MM-dd");
                            echo  $date->toString("MM/dd/YYYY");
                        }
                  ?></span></td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
        <?php echo $this->partial('partials/_edit-Driver-Information-Table.phtml',array('driverInfo' => $this->driverInfo,"stateList" => $this->stateList,"homebaseList" => $this->homebaseList,"depotList" => $this->depotList)); ?>
        <script type="text/javascript">
            $('#idDriverInfoEdit').hide(0);
        </script>
</div></div></div>


<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody>
        <tr>
            <th colspan="2">Driver Addresses<br><span class="red">Please fill in Addresses for the last 3 years.</span></th>
        </tr>
        </tbody>
    </table>
    <table cellspacing="0" class="inform" id="currentDriverAddressHistoryList">
    </table>
    <script type="text/javascript">
        refreshAddressHistoryRecords(<?php echo $this->driverId;?>);
    </script>
    <table cellspacing="0" class="inform">
        <tbody>
        <tr class="title-dark">
            <td>
                ADD ADDRESS [ <a id="toggleAddressAdd">SHOW</a> ]
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->partial('partials/_add-Address-History-Table.phtml',array('driverId' => $this->driverId,'stateList'=>$this->stateList)); ?>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#add_Address_Table').hide();
        });
    </script>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody>
            <tr>
                <th colspan="2">Commercial Driver's Licenses<br>
                <span class="red">Please list all Commercial Driver's Licenses held in last 3 years.</span><br>
                <span class="discr">Endorsements:&nbsp;<span class="bold">P</span>-Passenger,&nbsp;<span class="bold">T</span>-Doubles &amp; Triples,&nbsp;<span class="bold">H</span>-Hazardous Materials,&nbsp;<span class="bold">N</span>-Tankers,&nbsp;<span class="bold">X</span>-Hazardous &amp; Tankers.</span>
                </th>
            </tr>
        </tbody>
    </table>
    <table cellspacing="0" class="inform" id="driverLicensesList">
    </table>
    <table cellspacing="0"  class="inform">
        <tbody id="driverLicensesListAdd">
            <tr class="title-dark"><td colspan="2">ADD LICENSE [ <a id="toggleDriverLicenseAdd">SHOW</a> ]</td></tr>
        </tbody>
        <tbody id="add_driver_License_Table">
            <?php echo $this->partial('partials/_add-Driver-License-Table.phtml',array('driverId' => $this->driverId,"stateList" => $this->stateList)); ?>
        </tbody>
        </table>
    <script type="text/javascript">
        $(document).ready(function() {
            refreshLicenseRecords(<?php echo $this->driverId;?>);
            $('#add_driver_License_Table').hide();
        });
    </script>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody>
        <tr>
            <th colspan="2">Employment History<br>
                <span class="red">Please list all employers in the last 3 years starting from the most recent.<br>If applicant has worked as a driver, list all employers in last 10 years.</span></th>
        </tr>
        </tbody>
    </table>
    <table cellspacing="0" class="inform" id="Employment_History_List">
    </table>
    <script type="text/javascript">
        refreshEmploymentHistoryRecords(<?php echo $this->driverId;?>);
    </script>

    <table cellspacing="0" class="inform">
        <tbody>
        <tr class="title-dark">
            <td>
                ADD EMPLOYER [ <a id="toggleEmploymentHistoryAdd">SHOW</a> ]
            </td>
        </tr>
        </tbody>
    </table>
   <?php echo $this->partial('partials/_add-Employment-Table.phtml',array('driverId' => $this->driverId,"stateList" => $this->stateList)); ?>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#add_Employment_Table').hide();
        });
    </script>
</div></div></div>
<!--
<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody><tr><th colspan="2">Accidents &amp; Violations<br>
            <span class="red">Please list all Accidents and Violations.</span></th></tr>
        <tr class="title-dark"><td colspan="2">Accidents</td></tr>
        <tr><td>Driver did not have any Accidents.</td><td><span>&nbsp;</span></td></tr>
        <tr class="title-dark"><td colspan="2">Violations</td></tr>
        <tr><td>Driver did not have any Accidents.</td><td><span>&nbsp;</span></td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
</div></div></div>
-->
<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform adress">
        <tr><th colspan="7">Hours Of Service In Previous 7 Days [ <a id="toggleHoS" onclick="">EDIT</a> ]</th></tr>
        <tbody id="hos_list">
        <tr align="center">
            <td><?php echo $this->currentDriverHoSList[6]['dhos_date'];?></td>
            <td><?php echo $this->currentDriverHoSList[5]['dhos_date'];?></td>
            <td><?php echo $this->currentDriverHoSList[4]['dhos_date'];?></td>
            <td><?php echo $this->currentDriverHoSList[3]['dhos_date'];?></td>
            <td><?php echo $this->currentDriverHoSList[2]['dhos_date'];?></td>
            <td><?php echo $this->currentDriverHoSList[1]['dhos_date'];?></td>
            <td><?php echo $this->currentDriverHoSList[0]['dhos_date'];?></td>
        </tr>
        <tr class="color-dark" align="center">
            <td><?php echo $this->currentDriverHoSList[6]['dhos_hours'];?></td>
            <td><?php echo $this->currentDriverHoSList[5]['dhos_hours'];?></td>
            <td><?php echo $this->currentDriverHoSList[4]['dhos_hours'];?></td>
            <td><?php echo $this->currentDriverHoSList[3]['dhos_hours'];?></td>
            <td><?php echo $this->currentDriverHoSList[2]['dhos_hours'];?></td>
            <td><?php echo $this->currentDriverHoSList[1]['dhos_hours'];?></td>
            <td><?php echo $this->currentDriverHoSList[0]['dhos_hours'];?></td>
        </tr>
        </tbody>
        <?php echo $this->partial('partials/_edit-HoS-Table.phtml',array('currentDriverHoSList' => $this->currentDriverHoSList,"driverId" => $this->driverId)); ?>
        <tbody id="lrfw_list">
        <tr>
            <td colspan="7">Last relieved from work:&nbsp;<span></span>Date:&nbsp;
                <span><?php
                if(isset($this->currentDriverLrfwRecord[0]['dlrfw_date'])){
                    $date->set($this->currentDriverLrfwRecord[0]['dlrfw_date'],"YYYY-MM-dd");
                    echo $date->toString("MM/dd/YYYY");
                }
                ?></span>
                Time:&nbsp;<span><?php if($this->currentDriverLrfwRecord!=null){echo $this->currentDriverLrfwRecord[0]['dlrfw_from_time'];}?></span>
            </td>
        </tr>
        </tbody>
        <?php echo $this->partial('partials/_edit-lrfw-Table.phtml',array('currentDriverLrfwRecord' => $this->currentDriverLrfwRecord)); ?>
        
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
    <script type="text/javascript">
        $("#edit_hos_list").hide();
        $("#edit_lrfw_list").hide();
    </script>
</div></div></div>

<div class="blue-nav">
    <ul>
        <li><span><a href="/driver/driver/dqf/driver_id/<?php echo $this->driverId;?>">Go to DQF</a></span></li>
        <li><span><a href="/driver/index/dqf?status=All">Exit</a></span></li>
    </ul>
</div>

</div>

<script type="text/javascript">
    $(function() {
        $("#edit_lrfw_date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#d_Date_Of_Birth").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#d_Medical_Card_Expiration_Date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#d_TWIC_expiration").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#d_R_A_expiration").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#dah_Start_Date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#dah_End_Date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#l_Expiration_Date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#pe_Employment_Start_Date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
        $("#pe_Employment_Stop_Date").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
    });

</script>