
<div class="bottom-nav">
    <ul class="blue-nav">
        <li><span><a href="/driver/new-Driver/new-Driver-Complete/id/<?php echo $this->driverId;?>" >Complete</a></span></li>
    </ul>
    <ul class="blue-nav">
        <li><span><a href="/driver/new-Driver/new-Driver-Decline/id/<?php echo $this->driverId;?>" >Decline</a></li>
    </ul>
</div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>
<?php
    $date = new Zend_Date();
?>
<div class="driver-information" id="main">

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody><tr><th colspan="2">Application Information [ <a onclick="editApplicationInformation(<?php echo $this->driverId;?>)">EDIT</a> ]</th></tr>
        <tr><td>Application Type</td>
            <td><span><?php echo $_SESSION['driver_info']['DriverEmploymentType_list'][$this->driverInfo['d_Employment_Type']];?></span></td>
        </tr>
        <tr class="color-dark"><td>Entry Date</td>
            <td><span>
                  <?php
                        $date->set($this->driverInfo['d_Entry_Date']);
                  echo  $date->toString("MM/dd/YYYY H:m:s");
                  ?></span></td>
        </tr>
        <tr><td>Date Of Hire</td><td><span><?php echo $this->driverInfo['d_Date_Of_Hire']; ?></span></td></tr>
        <tr class="color-dark"><td>Status</td><td><span><?php echo $_SESSION['driver_info']['DriverStatus_list'][$this->driverInfo['d_Status']];?></span></td></tr>
        <tr><td>Home Base Location</td><td><?php echo $this->homebase['h_Name'];?></td></tr>
        <tr class="color-dark"><td>Depot</td><td><?php echo $this->depot['dp_Name'];?></td></tr>
        <tr><th colspan="2">Driver Information</th></tr>
        <tr>
            <td>Driver Name</td>
            <td>First:&nbsp;<span><?php echo $this->driverInfo['d_First_Name']; ?></span>
                Last:&nbsp;<span><?php echo $this->driverInfo['d_Last_Name']; ?></span>
                Middle:&nbsp;<span><?php echo $this->driverInfo['d_Middle_Name']; ?></span></td></tr>
        <tr class="color-dark"><td>Date Of Birth</td><td><span><?php echo $this->driverInfo['d_Date_Of_Birth']; ?></span></td></tr>
        <tr><td>Social Security #</td><td><span><?php echo $this->driverInfo['d_Driver_SSN']; ?></span></td></tr>
        <tr class="color-dark">
            <td>Medical Card</td>
            <td>Expires:&nbsp;<span><?php echo $this->driverInfo['d_Medical_Card_Expiration_Date']; ?></span>
                Medical Examiner's Name:&nbsp;<span><?php echo $this->driverInfo['d_Doctor_Name']; ?></span></td></tr>
        <tr>
            <td>Phone Information</td>
            <td>#1 phone number:&nbsp;<span><?php echo $this->driverInfo['d_Telephone_Number1']; ?></span><br/>
            <?php
                                  if($this->driverInfo['d_Telephone_Number2']!=""){
                ?>
                    #2 phone number:&nbsp;<span><?php echo $this->driverInfo['d_Telephone_Number2']; ?></span><br/>
                <?
            }
            ?>
            <?php
                                  if($this->driverInfo['d_Telephone_Number3']!=""){
                ?>
                    #3 phone number:&nbsp;<span><?php echo $this->driverInfo['d_Telephone_Number3']; ?></span><br/>
                <?
            }
            ?>
            </td></tr>
        <?php
                              if($this->driverInfo['d_Fax']!=""){
            ?>
            <tr class="color-dark"><td>Fax </td>
                <td><span><?php echo $this->driverInfo['d_Fax']; ?></span></td></tr>
            <?
        }
        ?>
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody>
        <tr>
            <th colspan="2">Driver Addresses<br><span class="red">Please fill in Addresses for the last 3 years.</span></th>
        </tr>
        </tbody>
    </table>
    <table cellspacing="0" class="inform" id="currentDriverAddressHistoryList">
    </table>
    <script type="text/javascript">
        refreshAddressHistoryRecords(<?php echo $this->driverId;?>);
    </script>
    <table cellspacing="0" class="inform">
        <tbody>
        <tr class="title-dark">
            <td>
                ADD ADDRESS [ <a id="toggleAddressAdd">Show</a> ]
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->partial('partials/_add-Address-History-Table.phtml',array('driverId' => $this->driverId,'stateList'=>$this->stateList)); ?>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#add_Address_Table').hide();
        });
    </script>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody><tr><th colspan="2">CDL &amp; Equipment Operated<br>
            <span class="red">Please list all Commercial Driver's Licenses.</span><br>
            <span class="discr">Endorsements:&nbsp;<span class="bold">P</span>-Passenger,&nbsp;<span class="bold">T</span>-Doubles &amp; Triples,&nbsp;<span class="bold">H</span>-Hazardous Materials,&nbsp;<span class="bold">N</span>-Tankers,&nbsp;<span class="bold">X</span>-Hazardous &amp; Tankers.</span></th></tr>
        <tr class="title-dark"><td colspan="2">Commercial Driver's Licenses</td></tr>
        <tr><td colspan="2">CDL#:&nbsp;<span>A7340358</span>State:&nbsp;<span>CA</span>Class:&nbsp;<span>C</span>Endorsements:&nbsp;<span>No</span>Do you have Air Brake Restrictions?&nbsp;&nbsp;&nbsp;Expires:&nbsp;<span>2/15/2015</span>Current:&nbsp;<span>Yes</span></td></tr>
        <tr class="title-dark"><td colspan="2">Equipment Operated</td></tr>
        <tr><td>Straight Truck</td><td><span>No</span>From Date:&nbsp;<span></span>From Date:&nbsp;<span></span>Total Miles:&nbsp;<span></span></td></tr>
        <tr class="color-dark"><td>Tractor/Semi Trailer</td><td><span>No</span>From Date:&nbsp;<span></span>From Date:&nbsp;<span></span>Total Miles:&nbsp;<span></span></td></tr>
        <tr><td>Doubles &amp; Triple</td><td><span>No</span>From Date:&nbsp;<span></span>From Date:&nbsp;<span></span>Total Miles:&nbsp;<span></span></td></tr>
        <tr class="color-dark"><td>Bus</td><td><span>No</span>From Date:&nbsp;<span></span>From Date:&nbsp;<span></span>Total Miles:&nbsp;<span></span></td></tr>
        <tr><td>Tankers (Hazmat)</td><td><span>No</span>From Date:&nbsp;<span></span>From Date:&nbsp;<span></span>Total Miles:&nbsp;<span></span></td></tr>
        <tr class="color-dark"><td>Other - Dump etc.</td><td><span>No</span>From Date:&nbsp;<span></span>From Date:&nbsp;<span></span>Total Miles:&nbsp;<span></span></td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody>
        <tr>
            <th colspan="2">Employment History<br>
                <span class="red">Please list all employers in the last 3 years starting from the most recent.<br>If applicant has worked as a driver, list all employers in last 10 years.</span></th>
        </tr>
        </tbody>
    </table>
    <table cellspacing="0" class="inform" id="Employment_History_List">
    </table>
    <script type="text/javascript">
        refreshEmploymentHistoryRecords(<?php echo $this->driverId;?>);
    </script>

    <table cellspacing="0" class="inform">
        <tbody>
        <tr class="title-dark">
            <td>
                ADD EMPLOYER [ <a id="toggleEmploymentHistoryAdd">Show</a> ]
            </td>
        </tr>
        </tbody>
    </table>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#add_Employment_Table').hide();
        });
    </script>
   <?php echo $this->partial('partials/_add-Employment-Table.phtml',array('driverId' => $this->driverId,"stateList" => $this->stateList)); ?>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform">
        <tbody><tr><th colspan="2">Accidents &amp; Violations<br>
            <span class="red">Please list all Accidents and Violations.</span></th></tr>
        <tr class="title-dark"><td colspan="2">Accidents</td></tr>
        <tr><td>Driver did not have any Accidents.</td><td><span>&nbsp;</span></td></tr>
        <tr class="title-dark"><td colspan="2">Violations</td></tr>
        <tr><td>Driver did not have any Accidents.</td><td><span>&nbsp;</span></td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
</div></div></div>

<div class="post-top"><div class="post-bottom"><div class="post-middle">
    <table cellspacing="0" class="inform adress">
        <tbody><tr><th colspan="7">Hours Of Service In Previous 7 Days</th></tr>
        <tr><td>6/14/2008</td><td>6/15/2008</td><td>6/16/2008</td><td>6/17/2008</td><td>6/18/2008</td><td>6/19/2008</td><td>6/20/2008</td></tr>
        <tr class="color-dark"><td> - </td><td> - </td><td> - </td><td> - </td><td> - </td><td> - </td><td> - </td></tr>
        <tr><td colspan="7">Last relieved from work:&nbsp;<span></span>Date:&nbsp;<span></span>Time:&nbsp;<span></span></td></tr>
        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody></table>
</div></div></div>

<div class="blue-nav">
    <ul>
        <li><span><a href="/DQF">Go to DQF</a></span></li>
        <li><span><a href="/exit">Exit</a></span></li>
    </ul>
</div>

</div>

<script type="text/javascript">
    $(function() {
        $("#d_Date_Of_Birth").datepicker();
        $("#dah_Start_Date").datepicker();
        $("#dah_End_Date").datepicker();
        $("#pe_Employment_Start_Date").datepicker();
        $("#pe_Employment_Stop_Date").datepicker();
    });

</script>