<tr>
    <td><a href="/company/company/edit-company/id/<?php echo $this->c_id; ?>" ><?php echo $this->c_Name; ?></a></td>
    <td><a href="/company/parent-company/edit-company/id/<?php echo $this->pc_id; ?>" ><?php echo $this->pc_Name; ?></a></td>
    <td><?php echo $this->h_Name; ?></td>
    <td><?php echo $this->ct_State; ?></td>
    <td><?php echo $this->ct_Start_Date; ?></td>
    <td> </td>
    <td><a href="#activate/company/<?php echo $this->c_id; ?>" >Activate/Deativate<a/> | <a href="#login_as/company/<?php echo $this->c_id; ?>">Login</a></td>
</tr>