<tr>
    <td><a href="/company/parent-company/view-company/id/<?php echo $this->pc_id; ?>" ><?php echo $this->pc_Name; ?></a></td>
    <td><?php echo $this->pc_EIN; ?></td>
    <td><?php echo $this->pc_Telephone_Number; ?></td>
    <td>
<a href="/company/parent-company/edit-company/id/<?php echo $this->pc_id; ?>" >EDIT</a> |
<a href="/company/parent-company/delete-company/id/<?php echo $this->pc_id; ?>" >DEL</a> | 
    </td>
</tr>