
<div class="breadcrumbs-left">
<div class="breadcrumbs-right">
<div class="breadcrumbs-middle">
<span>
    <?php
        echo $this->breadcrumbs;
    ?>
</span>
</div>
</div>
</div>
  <div id="main" class="driver-information">
    <div class="post-top"><div class="post-bottom"><div class="post-middle">
          <div style="padding:20px;">
            <div align="center" "><img src="/images/ProgressBar.gif" id="ProgressBar" /></div>
            <div id="edit_document"></div>
            <div id="document_images" style="display:none;"></div>
            <script type="text/javascript">
                getDocumentScansList(<?php echo $this->driver_id.",".$this->document_form_name_id;?>);
                clearTempImageFolder(<?php echo $this->driver_id.",".$this->document_form_name_id;?>);
            </script>
          </div>
      <br /><br />
      </div>
    </div></div></div>