
<div class="breadcrumbs-left">
<div class="breadcrumbs-right">
<div class="breadcrumbs-middle">
<span>
    <?php
        echo $this->breadcrumbs;
    ?>
</span>
</div>
</div>
</div>
  <div id="main" class="driver-information">
    <div class="post-top"><div class="post-bottom"><div class="post-middle">
          <div style="padding:20px;">
            <div id="edit_document"></div>
            <div id="document_images"></div>
            <script type="text/javascript">
                getDocumentScansList(<?php echo $this->driver_id.",".$this->document_form_name_id;?>);
            </script>
            <div id="document_images_preview_edit">
                <button class="prev"><<</button>
                <div class="anyClass">
                    <ul>
                                <?php
                                  #print_r($this->scans);
                                for($i=0;$i<sizeof($this->scans);$i++){
                              ?>
                                  <li><img onclick="alert('123');"  width="70" class="dqf-uploaded-image" alt="<?php echo $this->scans[$i]['cdfn_name'];?>"  src="/documents/dqf/driver_<?php echo $this->scans[$i]['cd_Driver_ID'];?>/document_form_<?php echo $this->scans[$i]['cd_Form_Name_ID'];?>/<?php echo $this->scans[$i]['cd_Scan'];?>"/></li>
                              <?php
                                }
                                ?>
                    </ul>
                </div>
                <button class="next">>></button>
                <script type="text/javascript">
                    $(function() {
                        $(".anyClass").jCarouselLite({
                            btnNext: ".next",
                            btnPrev: ".prev",
                            visible:6,
                            scroll: 1,
                            circular:false
                        });
                    });
                </script>
            </div>
          </div>
      <br /><br />
      </div>
    </div></div></div>
