<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=latin1" />
        <title>NSC HAL</title>
        <?php echo $this->headLink()->appendStylesheet('/css/global.css'); ?>
    </head>
    <body>
        <div id="header" style="background-color: #EEEEEE; height: 50px;">
            <div id="header-logo" style="float: left;">
                <b>NSC HAL</b>
            </div>
            <div id="header-navigation" style="float: right">
                <table border='1' cellpadding="0" cellspacing="0" width="1100px">
                    <tr>
                        <td colspan="6"></td>
                        <td><a href="/user/logout">Logout</a></td>
                    </tr>
                    <tr>
                        <td><a href="/company/index/index">Company module</a></td>
                        <td><a href="/report/index/index">Report module</a></td>
                        <td><a href="/company/parent-company/index">Parent Company module</a></td>
                        <td><a href="/equipment/index/index">Equipment module</a></td>
                        <td><a href="/user/list">user module</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <?php echo $this->layout()->content ?>
    </body>
</html>