<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/css/style.css" type="text/css" rel="stylesheet"/>
    <script src="/js//jquery-latest.js"></script>
<!--    <script type="text/javascript" src="/js/jquery.validate.js"></script>-->
    <title>National Safety Compliance, INC</title>

<?php
    $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js', 'text/javascript');
    $this->headLink()->appendStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/themes/smoothness/jquery-ui.css');
?>

<?= $this->headScript(); ?>
<?= $this->headLink(); ?>
    
</head>
<body>
        <?php
            // TODO Research about possibility to check identity in the controller side
            // Fetch the current instance of Zend_Auth
            $auth = Zend_Auth::getInstance();

            // Check whether an identity is set.
            if ($auth->hasIdentity()) {
                $this->identity = $auth->getIdentity();
            }
            if ($this->identity != null) {
           # $this->_redirect("/user/login");
        ?>
  <div id="wrapper">
      <div class="header-top">
        <div class="services">
          <span class="text"><span>Driver Qualification Services:  <?php echo $this->identity->vau_username; ?></span></span>
        </div>
        <div class="log-out">
          <ul>
            <li><a href='/user/logout'>Logout</a></li>
            <li><a href="/DQF">DQF home page</a></li>
          </ul>
        </div>
        <h1><span class="no-display">National Safety Compliance, INC</span></h1>
      </div>
      <div class="header-bottom">

          <ul class="top-menu">
            <li><span class="left"><span class="right"><a href="/driver/index/index?status=Pending"><span class="left"><span class="right">New Driver</span></span></a></span></span>
                <div class="top-pod-menu">
                    <ul>
                        <li>
                            <ul>
                                <li><a href="/driver/index/index?status=Pending">Pending Drivers</a></li>
                                <li><a href="/driver/new-driver/new-driver-search">Create New Driver</a></li>
                                <li><a href="#">Search Drivers</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </li>
            <li><span class="left"><span class="right"><a href="/driver/index/dqf?status=All"><span class="left"><span class="right">Driver Files</span></span></a></span></span></li>
            <li><span class="left"><span class="right"><a href="/driver/index/archives?status=All""><span class="left"><span class="right">Archives</span></span></a></span></span></li>
            <li><span class="left"><span class="right"><a href="reports"><span class="left"><span class="right">Reports</span></span></a></span></span>
              <div class="top-pod-menu"><ul>
              <li><a href="#">SUMMARY  REPORTS</a><ul>
                <li><a href="#">Summary Report</a></li></ul></li>
              <li><a href="#">ACTIVITY  REPORTS</a><ul>
                <li><a href="#">Activity Report</a></li>
                <li><a href="#">Email Warning Report</a></li></ul></li>
              <li><a href="#">GENERAL REPORTS</a><ul>
                <li><a href="#">Driver List - Current Status Report</a></li>
                <li><a href="#">Driver List - Active Drivers Report</a></li>
                <li><a href="#">Driver List - By CDL class</a></li>
                <li><a href="#">Driver's Expiration Report</a></li>
                <li><a href="#">Get Driver's Expiration Report Letter</a></li>
                <li><a href="#">Non-Compliant Detailed Report</a></li>
                <li><a href="#">Non-Compliant by NSC check report</a></li>
                <li><a href="#">Driver List - create your own look</a></li>
                <li><a href="#">Equipment Report</a></li></ul></li>
              </ul></div>
            </li>
            <li>
                  <span class="left">
                      <span class="right">
                          <a href="/equipment/index/index/status/Pending">
                              <span class="left">
                                  <span class="right">
                                      Equipment
                                  </span>
                              </span>
                          </a>
                      </span>
                  </span>
                <div class="top-pod-menu">
                    <ul>
                        <li>
                            <ul>
                                <li><a href="/equipment/list/index/status/Pending">Equipment List</a></li>
                                <li><a href="/equipment/truck-files/index/status/In%20Service">Truck Files</a></li>
                                <li><a href="/equipment/archives/index/status/Terminated">Archives</a></li>
                                <?php if ($this->identity->permissions->equipment_create_permission === true) : ?>
                                    <li><a href="/equipment/search/index">Create New Equipment</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
              </li>
              <li>
                  <span class="left">
                      <span class="right">
                          <a href="/incident/list/index/status/Pending">
                              <span class="left">
                                  <span class="right">
                                      Incident
                                  </span>
                              </span>
                          </a>
                      </span>
                  </span>
                <div class="top-pod-menu">
                    <ul>
                        <li>
                            <ul>
                                <li><a href="/incident/list/index/status/Pending">Incident List</a></li>
                                <?php if ($this->identity->permissions->incident_create_permission === true) : ?>
                                    <li><a href="/incident/create/step1">Add New Incident</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
              </li>
              <li>
                  <span class="left">
                      <span class="right">
                          <a href="/user/index/index/status/1">
                              <span class="left">
                                  <span class="right">
                                      Administration
                                  </span>
                              </span>
                          </a>
                      </span>
                  </span>
                <div class="top-pod-menu">
                    <ul>
                        <li>
                            <ul>
                                <li><a href="/user/list/index/status/1">User List</a></li>
                                <li><a href="/user/create/index">Create New User</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
              </li>
              <li><span class="left"><span class="right"><a href="/driver/index/index?status=1"><span class="left"><span class="right">Inspection</span></span></a></span></span>
                <div class="top-pod-menu">
                    <ul>
                        <li>
                            <ul>
                                <li><a href="/driver/index/index?status=1">Inspection List</a></li>
                                <li><a href="/driver/new-driver/new-driver-search">Create New Inspection</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </li>
              <li>
                  <span class="left">
                      <span class="right">
                          <a href="/violation/list/index" style="background:none; color:#1c357c; text-shadow:0px 1px 1px #fff;">
                              <span class="left" style="background: none;">
                                  <span class="right" style="background: none;">
                                      Violation
                                  </span>
                              </span>
                          </a>
                      </span>
                  </span>
                <div class="top-pod-menu">
                    <ul>
                        <li>
                            <ul>
                                <li><a href="/violation/list/index">Violation List</a></li>
                                <?php if ($this->identity->permissions->violation_create_permission === true) :  ?>
                                    <li><a href="/violation/index/create">Create New Violation</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
            </li>
            <li><span class="left"><span class="right"><a href="/driver/index/index"><span class="left"><span class="right">Service Provider</span></span></a></span></span></li>
          </ul>

          <?php if(isset($this->pageTitle)){ ?><h1 class="page-title"><?php echo $this->pageTitle; ?></h1><?php } ?>
          <?php echo $this->layout()->content ?>
          <?php } else {?>
    <div id="wrapper">
      <div class="header-top">
        <h1>
          <span class="no-display">National Safety Compliance, INC</span>
        </h1>
      </div>
      <div id="main" class="parametr-page">
        <div class="parametr-top">
          <div class="parametr-bottom">
            <div class="parametr-middle">
                <?php echo $this->layout()->content ?>
            </div>
          </div>
        </div>
      </div>
    </div>
        <?php }?>

    </div>
  </div>
</body>
</html>

