<table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">
    <tr height=30 valign=middle>
        <td class="MainText"><b>Previous Address #2</b>
        <td class="MainText">&nbsp;</td>
    </tr>
    <tr height=25 valign=middle>
        <td class="MainText" width="150">Street: </td>
        <td class="MainTextB"><?php echo ""; ?>&nbsp;&nbsp;&nbsp;
            <font color="#000000">City:</font> Erewe&nbsp;&nbsp;&nbsp;
            <font color="#000000">State:</font> AK&nbsp;&nbsp;&nbsp;
            <font color="#000000">Zip:</font> 23112
        </td>
    </tr>
    <tr height=25 valign=middle>
        <td class="MainText">At Address:</td>
        <td class="MainTextB">
            <font color="#000000">From Date:</font> 1/1/1980&nbsp;&nbsp;&nbsp;&nbsp;
            <font color="#000000">Years</font> 1&nbsp;&nbsp;
            <font color="#000000">Months</font> 1
        </td>
    </tr>
    <tr height=25 valign=middle>
        <td class="MainText">Is this current Address:</td>
        <td class="MainTextB">No</td>
    </tr>
    <tr height=40 valign=middle>
        <td class="MainText" align=center>&nbsp;</td>
        <td class="MainText" align=left>
            <a href='javascript:submit_GotoUpdateForm(60678)' class="MainLink2">
                <font color="#0000cc">Update this Address</font></a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
            <a href='javascript:submit_DeleteForm(60678)' class="MainLink2">
                <font color="#0000cc">Delete this Address</font></a>
        </td>
    </tr>
</table>