<?php
    $date = new Zend_Date();
?>
<div id="edit_document_form">
    <table>
        <tbody>
        <tr>
            <td>
                <input type="hidden" name="cd_ID" id="cd_ID" value="<?php echo $this->layout()->customDocument[0]['cd_ID'];?>" />
                <input type="hidden" name="cd_Driver_ID" id="cd_Driver_ID" value="<?php echo $this->layout()->customDocument[0]['cd_Driver_ID'];?>" />
                <input type="hidden" name="cd_Form_Name_ID" id="cd_Form_Name_ID" value="<?php echo $this->layout()->customDocument[0]['cd_Form_Name_ID'];?>" />            
            <a onclick="imageReverse();"><img title="Reverse Image" alt="Reverse" src="/images/rotate.png"></a> &nbsp;
            <a onclick="imageRotateClockwise();"><img title="Rotate Image Clockwise" alt="Rotate" src="/images/rotate-clockwise.png"></a> &nbsp;
            <a onclick="imageRotateContraclockwise();"><img title="Rotate Image Contraclockwise" alt="Rotate" src="/images/rotate-contraclockwise.png"></a> &nbsp;
            <a onclick="imageEmailCommentForm();"><img title="Email Comment about image" alt="Comment" src="/images/mail_forward.png"></a> &nbsp;
            <a onclick="imageEnlargeYourPicture('+');"><img title="Enlarge Image" alt="Enlarge" width="24px" height="24px" src="/images/icon-zoom_in.png"></a> &nbsp;
            <a onclick="imageEnlargeYourPicture('-');"><img title="Enlarge Image" alt="Enlarge" width="24px" height="24px" src="/images/icon-zoom_out.png"></a> &nbsp;
            <a onclick="imagePrint();"><img title="Print Image" alt="Print" src="/images/print.png"></a> &nbsp;
            <?php
        if ($this->layout()->identity->permissions->documents_delete==true){ ?>
                <a onclick="imageDelete();"><img title="Delete Image" alt="Delete" src="/images/delete-over.png"></a> &nbsp;
            <?php } ?>
                <img src="/images/ProgressBar.gif" id="ProgressBar2" style="visibility:hidden;" />
        </td>
            <td rowspan="2"></td></tr>
        <tr>
            <td width="500px">
                <div style=" max-width:500px; max-height:550px; " id="watermark_box">
                    <span id="dqf-uploaded-image-large-container">
                        <img id="dqf-uploaded-image-large" class="dqf-uploaded-image" width="500" alt="<?php echo $this->layout()->customDocument[0]['cdfn_name'];?>" src="/documents/dqf/driver_<?php echo $this->layout()->customDocument[0]['cd_Driver_ID'];?>/document_form_<?php echo $this->layout()->customDocument[0]['cd_Form_Name_ID'];?>/<?php echo $this->layout()->customDocument[0]['cd_Scan']."?".rand(0,999);?>"/>
                    </span>
                    <input type="hidden" id="dqf-uploaded-image-large-rotated" />
                    <input type="hidden" id="dqf-uploaded-image-large-origin" value="<?php echo $this->layout()->customDocument[0]['cd_Scan'];?>" />
                    <input type="hidden" id="dqf-uploaded-image-large-width" />
                    <input type="hidden" id="dqf-uploaded-image-large-height" />
                    <?php
                        if($this->layout()->customDocument[0]['ct_logo']==""){?>
                    <?php }else{ ?>
                        <img width="100" id="watermark" class="watermark" src="/system/company/company_<?php echo $this->layout()->customDocument[0]['cd_Company_ID'];?>/<?php echo $this->layout()->customDocument[0]['ct_logo'];?>" />
                    <?php } ?>
                </div>
            </td>
            <td valign="top" colspan="2">
                <table width="100%">
                    <tbody>
                    <tr>
                        <td>
                            <label for="cd_Company_ID">Company:</label>
                        </td>
                        <td><?php

                            $companyList = $this->layout()->companyList;
                                #print_r($companyList);
                        ?>
                            <select id="cd_Company_ID" name="cd_Company_ID">
                                <option value="" <?php if($this->layout()->customDocument[0]['cd_Company_ID']==""){echo " selected='selected' ";} ?>  disabled="disabled"> - Select -</option>
                            <?php

                            foreach($companyList as $k => $v){
                                echo $k. " => ".$v."<br/>";
                                ?>
                                    <option onclick="getHomebaseList(<?php echo $v['c_id'];?>)" value="<?php echo $v['c_id'];?>" <?php if($this->layout()->customDocument[0]['cd_Company_ID']==$v['c_id']){echo " selected='selected' "; }?>><?php echo $v['c_Name'].", ".$v['s_name'];?></option>
                                <?php
                                    }
                            ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Homebase_ID">HomeBase:</label>
                        </td>
                        <td><?php
                            $homebaseList = $this->layout()->homebaseList;
                        ?>
                            <select id="cd_Homebase_ID" name="cd_Homebase_ID">
                                <option value="" <?php if($this->layout()->customDocument[0]['cd_Homebase_ID']==""){echo " selected='selected' ";} ?>  disabled="disabled"> - Select company first -</option>
                            <?php

                            foreach($homebaseList as $k => $v){
                                echo $k. " => ".$v."<br/>";
                                ?>
                                    <option value="<?php echo $v['h_id'];?>" <?php if($this->layout()->customDocument[0]['cd_Homebase_ID']==$v['h_id']){echo " selected='selected' "; }?>><?php echo $v['h_Name'].", ".$v['s_name'];?></option>
                                <?php
                                    }
                            ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Description">Description:</label>
                        </td>
                        <td>
                            <textarea name="cd_Description" id="cd_Description" rows="4" cols="20"><?php echo $this->layout()->customDocument[0]['cd_Description'];?></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Logo:</label>
                        </td>
                        <td>
                        <?php
                            if($this->layout()->customDocument[0]['ct_logo']==""){?>
                            <img id="company_logo" width="100" src="/images/nologo.png" />
                        <?php }else{ ?>
                            <img id="company_logo" width="100" src="/system/company/company_<?php echo $this->layout()->customDocument[0]['cd_Company_ID'];?>/<?php echo $this->layout()->customDocument[0]['ct_logo'];?>" />
                        <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="required" for="cd_Fax_Status_id"><span>*</span>Fax Status:</label>
                        </td>
                        <td>
                            <select id="cd_Fax_Status_id" name="cd_Fax_Status_id">
                                <option <?php if($this->layout()->customDocument[0]['cd_Fax_Status_id']==""){echo " selected='selected' ";} ?>  disabled="disabled"> - Select -</option>
                            <?php
                                                                $faxStatusList = $this->layout()->faxStatusList;
                            foreach($faxStatusList as $k => $v){
                                echo $k. " => ".$v."<br/>";
                                ?>
                                    <option value="<?php echo $v['cdfs_id'];?>" <?php if($this->layout()->customDocument[0]['cd_Fax_Status_id']==$v['cdfs_id']){echo " selected='selected' "; }?>><?php echo $v['cdfs_status'];?></option>
                                <?php
                                    }
                            ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="required" for="cd_Document_Form_Status"><span>*</span>Document Form Status:</label>
                        </td>
                        <td>
                            <select id="cd_Document_Form_Status" name="cd_Document_Form_Status">
                                <option <?php if($this->layout()->customDocument[0]['cd_Document_Form_Status']==""){echo " selected='selected' ";} ?>  disabled="disabled"> - Select -</option>
                            <?php
                                                                $formStatusList = $this->layout()->formStatusList;
                            foreach($formStatusList as $k => $v){
                                echo $k. " => ".$v."<br/>";
                                ?>
                                    <option value="<?php echo $v['cdfms_id'];?>" <?php if($this->layout()->customDocument[0]['cd_Document_Form_Status']==$v['cdfms_id']){echo " selected='selected' "; }?>><?php echo $v['cdfms_status'];?></option>
                                <?php
                                    }
                            ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Date Requested:</label>
                        </td>
                        <td>
                        <?php
                                                        if(isset($this->layout()->customDocument[0]['cd_Date_Requested'])){
                            $date->set($this->layout()->customDocument[0]['cd_Date_Requested'],"yyyy-MM-dd");
                            echo $date->toString("MM/dd/yyyy");}
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Date Completed:</label>
                        </td>
                        <td>
                        <?php
                                                        if(isset($this->layout()->customDocument[0]['cd_Date_Completed'])){
                            $date->set($this->layout()->customDocument[0]['cd_Date_Completed'],"yyyy-MM-dd");
                            echo $date->toString("MM/dd/yyyy");}
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Archived">Archived:</label>
                        </td>
                        <td>
                            <select id="cd_Archived" name="cd_Archived">
                                <option value="No" <?php if(strtolower($this->layout()->customDocument[0]['cd_Archived'])=="no"){echo " selected='selected' ";} ?>  >No</option>
                                <option value="Yes" <?php if(strtolower($this->layout()->customDocument[0]['cd_Archived'])=="yes"){echo " selected='selected' ";} ?>  >Yes</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="required" for="cd_DOT_Regulated"><span>*</span>DOT Regulated:</label>
                        </td>
                        <td>
                            <select id="cd_DOT_Regulated" name="cd_DOT_Regulated">
                                <option value="" <?php if(strtolower($this->layout()->customDocument[0]['cd_DOT_Regulated'])==""){echo " selected='selected' ";} ?>  > - Select - </option>
                                <option value="No" <?php if(strtolower($this->layout()->customDocument[0]['cd_DOT_Regulated'])=="no"){echo " selected='selected' ";} ?>  >No</option>
                                <option value="Yes" <?php if(strtolower($this->layout()->customDocument[0]['cd_DOT_Regulated'])=="yes"){echo " selected='selected' ";} ?>  >Yes</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="required" for="cd_Current_Page"><span>*</span>Page #:</label>
                        </td>
                        <td>
                            <input type="text" size="3" id="cd_Current_Page" name="cd_Current_Page" value="<?php echo $this->layout()->customDocument[0]['cd_Current_Page']?>" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="blue-nav">
                                <ul>
                                    <li><span><a onclick="saveImageDocument()">Save</a></span></li>
                                    <li><span><a onclick="getDocumentScansList(<?php echo $this->layout()->customDocument[0]['cd_Driver_ID'];?>,<?php echo $this->layout()->customDocument[0]['cd_Form_Name_ID'];?>);">Close</a></span></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    </tbody></table>
            </td>
        </tr>

        </tbody></table>

</div>