<?php
    $date = new Zend_Date();
?>
<div id="edit_document_form">
    <table>
        <tbody>
        <tr><td>
            <a onclick="imageReverse();"><img title="Reverse Image" alt="Reverse" src="/images/rotate.png"></a> &nbsp;
            <a onclick="imageRotateClockwise();"><img title="Rotate Image Clockwise" alt="Rotate" src="/images/rotate-clockwise.png"></a> &nbsp;
            <a onclick="imageRotateContraclockwise();"><img title="Rotate Image Contraclockwise" alt="Rotate" src="/images/rotate-contraclockwise.png"></a> &nbsp;
            <a onclick="imageEmailComment();"><img title="Email Comment about image" alt="Comment" src="/images/mail_forward.png"></a> &nbsp;
            <a onclick="imageEnlargeYourPicture('+');"><img title="Enlarge Image" alt="Enlarge" width="24px" height="24px" src="/images/icon-zoom_in.png"></a> &nbsp;
            <a onclick="imageEnlargeYourPicture('-');"><img title="Enlarge Image" alt="Enlarge" width="24px" height="24px" src="/images/icon-zoom_out.png"></a> &nbsp;
            <a onclick="imagePrint();"><img title="Print Image" alt="Print" src="/images/print.png"></a> &nbsp;
            <?php
        if ($this->layout()->identity->permissions->documents_delete==true){ ?>
                <a onclick="imageDelete();"><img title="Delete Image" alt="Delete" src="/images/delete-over.png"></a> &nbsp;
            <?php } ?>
        </td><td rowspan="2"></td></tr>
        <tr>
            <td width="500px">
                <div style=" max-width:500px; max-height:550px; " id="watermark_box">
                    <span id="dqf-uploaded-image-large-container">
                        <img id="dqf-uploaded-image-large" class="dqf-uploaded-image" width="500" alt="<?php echo $this->layout()->customDocument[0]['cdfn_name'];?>" src="/documents/dqf/driver_<?php echo $this->layout()->customDocument[0]['cd_Driver_ID'];?>/document_form_<?php echo $this->layout()->customDocument[0]['cd_Form_Name_ID'];?>/<?php echo $this->layout()->customDocument[0]['cd_Scan']."?".rand(0,999);?>"/>
                    </span>
                    <input type="hidden" id="dqf-uploaded-image-large-rotated" />
                    <input type="hidden" id="dqf-uploaded-image-large-origin" value="<?php echo $this->layout()->customDocument[0]['cd_Scan'];?>" />
                    <input type="hidden" id="dqf-uploaded-image-large-width" />
                    <input type="hidden" id="dqf-uploaded-image-large-height" />
                    <?php
                        if($this->layout()->customDocument[0]['ct_logo']==""){?>
                    <?php }else{ ?>
                        <img width="100" id="watermark" class="watermark" src="/system/company/company_<?php echo $this->layout()->customDocument[0]['cd_Company_ID'];?>/<?php echo $this->layout()->customDocument[0]['ct_logo'];?>" />
                    <?php } ?>
                </div>
            </td>
            <td valign="top" colspan="2">
                <table width="100%">
                    <tbody>
                    <tr>
                        <td>
                            <label >Company:</label>
                        </td>
                        <td>
                            <span>
                                <?php echo $this->layout()->customDocument[0]['c_Name'];?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>HomeBase:</label>
                        </td>
                        <td>
                            <span><?php echo $this->layout()->customDocument[0]['h_Name'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Description:</label>
                        </td>
                        <td><span><?php echo $this->layout()->customDocument[0]['cd_Description'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Logo:</label>
                        </td>
                        <td>
                        <?php
                            if($this->layout()->customDocument[0]['ct_logo']==""){?>
                            <img id="company_logo" width="100" src="/images/nologo.png" />
                        <?php }else{ ?>
                            <img id="company_logo" width="100" src="/system/company/company_<?php echo $this->layout()->customDocument[0]['cd_Company_ID'];?>/<?php echo $this->layout()->customDocument[0]['ct_logo'];?>" />
                        <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Fax Status:</label>
                        </td>
                        <td>
                            <span><?php echo $this->layout()->customDocument[0]['cdfs_status'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Document Form Status:</label>
                        </td>
                        <td>
                            <span><?php echo $this->layout()->customDocument[0]['cdfms_status'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Date Requested:</label>
                        </td>
                        <td><span>
                        <?php
                         if(isset($this->layout()->customDocument[0]['cd_Date_Requested'])){
                            $date->set($this->layout()->customDocument[0]['cd_Date_Requested'],"yyyy-MM-dd");
                            echo $date->toString("MM/dd/yyyy");}
                        ?>
                        </span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Date Completed:</label>
                        </td>
                        <td><span>
                        <?php
                         if(isset($this->layout()->customDocument[0]['cd_Date_Completed'])){
                            $date->set($this->layout()->customDocument[0]['cd_Date_Completed'],"yyyy-MM-dd");
                            echo $date->toString("MM/dd/yyyy");}
                        ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Archived:</label>
                        </td>
                        <td>
                            <span><?php echo $this->layout()->customDocument[0]['cd_Archived'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>DOT Regulated:</label>
                        </td>
                        <td>
                            <span><?php echo $this->layout()->customDocument[0]['cd_DOT_Regulated'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Page #:</label>
                        </td>
                        <td>
                            <span><?php echo $this->layout()->customDocument[0]['cd_Current_Page'];?></span>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="blue-nav">
                                <ul>
                                    <li><span><a onclick="getDocumentScansList(<?php echo $this->layout()->customDocument[0]['cd_Driver_ID'];?>,<?php echo $this->layout()->customDocument[0]['cd_Form_Name_ID'];?>);">Close</a></span></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    </tbody></table>
            </td>
        </tr>

        </tbody></table>
</div>

            <div id="document_images_preview_edit">
                <div class="anyClass">
                    <ul>
                                <?php
                                for($i=0;$i<sizeof($this->layout()->scans);$i++){
                              ?>
                                  <li><img onclick="viewImageDocument(<?php echo $this->layout()->scans[$i]['cd_ID'].",".$this->layout()->scans[$i]['cd_Driver_ID'];?>);"  width="70" class="dqf-uploaded-image" alt="<?php echo $this->layout()->scans[$i]['cdfn_name'];?>"  src="/documents/dqf/driver_<?php echo $this->layout()->scans[$i]['cd_Driver_ID'];?>/document_form_<?php echo $this->layout()->scans[$i]['cd_Form_Name_ID'];?>/<?php echo $this->layout()->scans[$i]['cd_Scan']."?".rand(0,999);?>"/></li>
                              <?php
                                }
                                ?>
                    </ul>
                </div>
                <div class="blue-nav" style=" padding-left: 55px !important;">
					<ul>
						<li><span><a class="prev" >&lt;&lt;</a></span></li>
						<li><span><a class="next" >&gt;&gt;</a></span></li>
					</ul>
				</div>
                <script type="text/javascript">
                    $(function() {
                        $(".anyClass").jCarouselLite({
                            btnNext: ".next",
                            btnPrev: ".prev",
                            visible:6,
                            scroll: 1,
                            circular:false
                        });
                    });
                </script>
            </div>