<?php print_r($this->layout()->customDocument);?>
<?php print_r($this->layout()->formStatusList);?>
<?php
    $date = new Zend_Date();
?>
<div id="edit_document_form">
    <table>
        <tr>
            <td width="500px"></td>
            <td width="300px"></td>
            <td width="25px"><a><img src="/images/icon-delete.png" width="20px" alt=""/></a></td>
        </tr>
        <tr>
            <td width="500px" style="overflow:scroll;"><img width="500" class="dqf-uploaded-image" height="" alt="<?php echo $this->layout()->customDocument[0]['cdfn_name'];?>" src="/documents/dqf/driver_<?php echo $this->layout()->customDocument[0]['cd_Driver_ID'];?>/document_form_<?php echo $this->layout()->customDocument[0]['cd_Form_Name_ID'];?>/<?php echo $this->layout()->customDocument[0]['cd_Scan'];?>"/></td>
            <td colspan="2" valign="top">
                <table width="100%">
                    <tr>
                        <td>
                            <label for="cd_Description">Description:</label>
                        </td>
                        <td>
                            <textarea name="cd_Description" id="cd_Description" rows="4" cols="20"><?php echo $this->layout()->customDocument[0]['cd_Description'];?></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Logo">Logo:</label>
                        </td>
                        <td>
                            <?php
                                if($this->layout()->customDocument[0]['cd_Logo']==""){?>
                                <img src="/images/nologo.png" />
                            <?php }else{ ?>
                                <img src="/system/company/company_<?php echo $this->layout()->customDocument[0]['cd_Company_ID'];?>/<?php echo $this->layout()->customDocument[0]['cd_Logo'];?>" />
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Fax_Status_id">Logo:</label>
                        </td>
                        <td>
                            <select id="cd_Fax_Status_id" name="cd_Fax_Status_id">
                                <option <?php if($this->layout()->customDocument[0]['cd_Document_Form_Status']==""){echo " selected='selected' ";} ?>  disabled="disabled"> - Select -</option>
                                <?php
                                    $faxStatusList = $this->layout()->faxStatusList;
                                    foreach($faxStatusList as $k => $v){
                                    echo $k. " => ".$v."<br/>";
                                ?>
                                        <option value="<?php echo $v['cdfs_id'];?>" <?php if($this->layout()->customDocument[0]['cd_Fax_Status_id']==$v['cdfs_id']){echo " selected='selected' "; }?>><?php echo $v['cdfs_status'];?></option>
                                <?php
                                    }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Document_Form_Status">Document Form Status:</label>
                        </td>
                        <td>
                            <select id="cd_Document_Form_Status" name="cd_Document_Form_Status">
                                <option <?php if($this->layout()->customDocument[0]['cd_Document_Form_Status']==""){echo " selected='selected' ";} ?>  disabled="disabled"> - Select -</option>
                                <?php
                                    $formStatusList = $this->layout()->formStatusList;
                                    foreach($formStatusList as $k => $v){
                                    echo $k. " => ".$v."<br/>";
                                ?>
                                        <option value="<?php echo $v['cdfms_id'];?>" <?php if($this->layout()->customDocument[0]['cd_Document_Form_Status']==$v['cdfms_id']){echo " selected='selected' "; }?>><?php echo $v['cdfms_status'];?></option>
                                <?php
                                    }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Date Requested:</label>
                        </td>
                        <td>
                            <?php
                                if(isset($this->layout()->customDocument[0]['cd_Date_Requested'])){
                                $date->set($this->layout()->customDocument[0]['cd_Date_Requested'],"yyyy-MM-dd");
                                echo $date->toString("MM/dd/yyyy");}
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Date Completed:</label>
                        </td>
                        <td>
                            <?php
                                if(isset($this->layout()->customDocument[0]['cd_Date_Completed'])){
                                $date->set($this->layout()->customDocument[0]['cd_Date_Completed'],"yyyy-MM-dd");
                                echo $date->toString("MM/dd/yyyy");}
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Electronic_Signature">cd_Electronic_Signature:</label>
                        </td>
                        <td>
                            <input type="text" id="cd_Electronic_Signature" name="cd_Electronic_Signature" value="<?php echo $this->layout()->customDocument[0]['cd_Electronic_Signature']?>">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="cd_Electronic_Signature">cd_Electronic_Signature:</label>
                        </td>
                        <td>
                            <input type="text" id="cd_Electronic_Signature" name="cd_Electronic_Signature" value="<?php echo $this->layout()->customDocument[0]['cd_Electronic_Signature']?>">
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

    </table>
</div>