<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>


<div class="driver-information form" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div style="padding: 30px;">
                    <center>
                        <table>
                            <tbody>
                                <tr>
                                    <td align="center" colspan="2">
                                        <div class="warning">Vehicle with VIN <b><?= $this->VIN ?></b> has "<?= $this->newStatus; ?>" status with this Home Base.</div>
                                        <br><br>
                                        <p><b>Please look for the Vehicle in the "New Truck" list.</b></p>
                                        <br><br><br>
                                    </td>
                                </tr>
                                <tr>
                                    <td><span class="blue-button"><span><a href="/equipment/search">Back To Search Page</a></span></span></td>
                                    <td><span class="blue-button"><span><a href="/equipment/list">Go To New Equipment List</a></span></span></td>
                                </tr>
                            </tbody></table>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>
