<table width="80%" cellspacing="" cellpadding="0" border="0" bgcolor="#0000cc" align="center">
    <tbody>
        <tr height="30">
            <td align="center">New Application - Vehicle</td>
        </tr>
    </tbody>
</table>

<table width="80%" cellspacing="1" cellpadding="4" border="0" bgcolor="#dceddc" align="center">
    <tbody>
        <tr height="10">
            <td bgcolor="#66cdaa" align="right" colspan="3">&nbsp;</td></tr>
        <tr height="40">
            <td colspan="3">&nbsp;</td></tr>
        <tr>
            <td align="middle" colspan="3"><font color="#ff0000"><b>Vehicle
                        with VIN <?php echo $this->VIN ?> is already in service with this home base.<br>Please
                        look for the vehicle in Truck File module.</b></font> </td></tr>
        <tr height="40">
            <td colspan="3">&nbsp;</td></tr>
        <tr>
            <td width="40%" align="right">
                <a href="/equipment/search">
                    &nbsp;&nbsp;<font color="#0000cc">Back To Search</font>
                </a>
            </td>
            <td width="50">&nbsp;</td>
            <td width="40%" align="left">
                <a href="/equipment/list">
                    <font color="#0000cc">
                        Go to Truck File Module&nbsp;&nbsp;
                    </font>
                </a>
            </td>
        </tr>
        <tr height="40">
            <td colspan="3">&nbsp;</td></tr>
        <tr height="25" bgcolor="#0000cc">
            <td colspan="3">&nbsp;</td></tr>
    </tbody>
</table>