<!--
@author Andryi Ilnytskyi 07.11.2010

Search equipment form.
-->

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<!--TODO hak for diz-->
</div>

<div class="new-appl" id="main">
    <div class="parametr-top">
        <div class="parametr-bottom">
            <div class="parametr-middle">
                <form name="new-Equipment-Search" method="post" action="/equipment/search" id="new-Equipment-Search" class="select-parametr new-appl">
                    <fieldset>
                        <label>
                            Vehicle Identification Number:
                        </label>
                        <input type="text" id="VIN" value="" name="VIN">
                        <p class="submit-button">
                            <input type="submit" value="Next">
                        </p>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
