<table width="80%" cellspacing="" cellpadding="0" border="0" bgcolor="#0000cc" align="center">
    <tbody>
        <tr height="30">
            <td align="center">New Application - Vehicle</td>
        </tr>
    </tbody>
</table>

<table width="80%" cellspacing="1" cellpadding="4" border="0" bgcolor="#dceddc" align="center">
    <tbody>
        <tr height="10">
            <td bgcolor="#66cdaa" align="right" colspan="3">&nbsp;</td></tr>
        <tr height="40">
            <td colspan="3">&nbsp;</td></tr>
        <tr>
            <td align="center" colspan="3">
                <p>Truck with VIN <b><?php echo $this->VIN ?></b> does not exist.</p>
                <p>Do you really want to create new truck?</p>
            </td>
        </tr>
        <tr height="40">
            <td colspan="3">&nbsp;</td></tr>
        <tr>
            <td width="40%" align="right">
                <a href="/equipment/search">
                    &nbsp;&nbsp;<font color="#0000cc">Back To Search</font>
                </a>
            </td>
            <td width="50">&nbsp;</td>
            <td width="40%" align="left"><a href="<?php echo '/equipment/create/index/VIN/' . $this->VIN ?>" >
                    <font color="#0000cc">Go to Truck File Module&nbsp;&nbsp;</font></a> </td></tr>
        <tr height="40">
            <td colspan="3">&nbsp;</td></tr>
        <tr height="25" bgcolor="#0000cc">
            <td colspan="3">&nbsp;</td></tr></tbody>
</table>
