<!--
@author Andryi Ilnytskyi 04.11.2010
Set content for the row in the users list.
-->
<tr>
    <td><?= $this->e_Unit_Number;?></td>
    <td><?= '&nbsp;'; // TODO  Veh. Type? ?></td>
    <td><?= $this->e_Number; // VIN ?></td>
    <td>
        <?php
            if (!is_null($this->e_license_Number) || !is_null($this->s_name)) {
                echo $this->e_license_Number . ' / ' . $this->s_name; // Lic. Plate #/State
            } else {
                echo '&nbsp;';
            }
        ?>
    </td>

    <td><?= $this->e_Gross_Vehicle_Weight_Rating; //  GVW ?></td>
    <td><?= $this->e_Axles; // #Axles ?></td>
    <td><?= '&nbsp;'; // TODO  Vendor Code? ?></td>
    <td><?= $this->enes_type; // Status ?></td>
    <td><a href="/equipment/information-worksheet/index/VIN/<?= $this->e_Number; ?>">View</a></td>
    <?php if (is_null($this->ea_id)) : ?>
        <td><a href="/equipment/information-worksheet/add-assignment/equipmentId/<?= $this->e_id; ?>">Add Assign</a></td>
    <?php else : ?>
        <td><a href="/equipment/information-worksheet/view-assignment/equipmentId/<?= $this->e_id; ?>">View Assign</a></td>
    <?php   endif; ?>
</tr>
