<!--
@author Andryi Ilnytskyi 24-10-2010
Set content for the row in the users list.
-->
<tr>
    <th>Unit #</th>
            <th>Veh. Type</th>
            <th>VIN</th>
            <th>Lic. Plate #/State</th>
            <th>GVW</th>
            <th>#Axles</th>
            <th>Vendor Code</th>
            <th>Status</th>
            <th>Action</th>

    <td><?php echo $this->e_Unit_Number; // Unit # ?></td>
    <td><?php echo '&nbsp;'; // TODO  Veh. Type? ?></td>
    <td><?php echo $this->e_Number; // VIN ?></td>
    <td><?php echo '&nbsp;'; // TODO  Lic. Plate #/State? ?></td>
    <td><?php echo '&nbsp;'; // TODO  GVW? ?></td>
    <td><?php echo $this->e_Axles; // #Axles ?></td>
    <td><?php echo '&nbsp;'; // TODO  Vendor Code? ?></td>
    <td><?php echo $this->e_Active_Status; // Status ?></td>
</tr>