
<?php if ($this->status == 'Pending') : ?>
    <?php if ($this->identity->permissions->equipment_modify_permission === true) : ?>
        <li>
            <span>
                <a href="/equipment/information-worksheet/validate-completed/id/<?= $this->equipmentID ?>">
                    Complete
                </a>
            </span>
        </li>
        <li>
            <span>
                <a href="/equipment/information-worksheet/declined/id/<?= $this->equipmentID ?>">
                    Decline
                </a>
            </span>
        </li>
    <?php endif ?>
<?php elseif ($this->status == 'Declined') : ?>
    <?php if ($this->identity->permissions->equipment_modify_permission === true) : ?>
        <li>
            <span>
                <a href="/equipment/information-worksheet/reactivated/id/<?= $this->equipmentID ?>">
                    Reactivate
                </a>
            </span>
        </li>
    <?php endif ?>
<?php elseif ($this->status == 'Completed') :  ?>
    <li>
        <span>
            <a href="/equipment/equipment-file/index/id/<?= $this->equipmentID ?>">
                Go to File
            </a>
        </span>
    </li>
<?php endif ?>
<li>
    <span>
        <a class="exitButton">
            Exit
        </a>
    </span>
</li>
