<?php if ($this->status == 'Pending') : ?>
    <li>
        <span>
            <a href="/equipment/information-worksheet/completed/id/<?php echo $this->equipmentID ?>">
                Complete
            </a>
        </span>
    </li>
    <li>
        <span>
            <a href="/equipment/information-worksheet/declined/id/<?php echo $this->equipmentID ?>">
                Decline
            </a>
        </span>
    </li>
<?php elseif ($this->status == 'Declined') : ?>
    <li>
        <span>
            <a href="/equipment/information-worksheet/reactivated/id/<?php echo $this->equipmentID ?>">
                Reactivate
            </a>
        </span>
    </li>
<?php elseif ($this->status == 'Completed') :  ?>
    <li>
        <span>
            <a href="/equipment/information-worksheet/goto-file/<?php echo $this->equipmentID ?>">
                Go to File
            </a>
        </span>
    </li>
<?php endif ?>
<li>
    <span>
        <a href="/equipment/list">
            Exit
        </a>
    </span>
</li>