<?php
    echo $this->navigation()->menu()->render(); ?>
<h2>Company list</h2>
<?php if ($this->identity == null) {
 ?>
    <p>To log in <a href='/user/login'>click here</a></p>
<?php }?>
        <table border='1' cellpadding="0" cellspacing="0" width="1100px">
        <tr>
            <td>Company name</td>
            <td>EIN</td>
            <td>Phone</td>
            <td>Action</td>
        </tr>
<?php echo $this->partialLoop('partials/_parent-company-row.phtml', $this->listOfCompanies); ?>
</table>