
<div class="bottom-nav">
    <ul class="blue-nav">
        <li><span><a href="/driver/new-Driver/new-Driver-Complete/id/<?php echo $this->driverId;?>" >Complete</a></span></li>
    </ul>
    <ul class="blue-nav">
        <li><span><a href="/driver/new-Driver/new-Driver-Decline/id/<?php echo $this->driverId;?>" >Decline</a></li>
    </ul>
</div>
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>
<?php
    $date = new Zend_Date();
?>
<table border="1" width="100%">
<tr>
    <td colspan="2" bgcolor="#ccffcc"><b>Driver Information:</b></td>
</tr>
<tr>
    <td colspan="2">
        <form action="/driver/Driver/save-Driver-Information/id/<?php echo $this->driverId;?>" method="post" enctype="application/x-www-form-urlencoded" id="driver_DriverPersonalInformation_Form">
            <table width="100%" border="1" cellpadding="5" cellspacing="0">
                <tr>
                    <td>
                        <label class="required" for="d_Employment_Type"><span>*</span>Application Type</label>
                    </td>
                    <td>
                        <select id="d_Employment_Type" name="d_Employment_Type">
                        <?php
                            foreach($_SESSION['driver_info']['DriverEmploymentType_list'] as $k => $v)
                            {
                        ?>
                            <option label="<?php echo $v;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_Employment_Type']){ echo "selected='selected'";} ?>><?php echo $v;?></option>
                        <?php
                            }
                        ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="optional" for="entrydate">Entry Date</label>
                    </td>
                    <td>
                    <?php
                        $date->set($this->driverInfo['d_Entry_Date']);
                        echo  $date->toString("MM/dd/YYYY H:m:s");
                    ?>
                    </td>
                </tr>
                <tr>
                    <td><label class="optional" for="status">Status</label></td>
                    <td><input type="text" disabled="disabled" value="<?php echo $_SESSION['driver_info']['DriverStatus_list'][$this->driverInfo['d_Status']];?>" id="status" name="status"></td>
                </tr>
                <tr>
                    <td><label class="required" for="d_homebase_ID"><span>*</span>Homebase</label></td>
                    <td>
                        <select id="d_homebase_ID" name="d_homebase_ID">
                        <?php
                            foreach($this->homebaseList as $k => $v)
                            {
                        ?>
                            <option class="d_homebase_ID_item" onclick="addClickHandlers(<?php echo $k;?>)" label="<?php echo $v['h_Name'];?>" id="<?php echo $k;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_homebase_ID']){ echo "selected='selected'";} ?>   ><?php echo $v['h_Name'];?></option>
                        <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label class="optional" for="d_depot_ID">Depot</label></td>
                    <td>
                        <select id="d_depot_ID" name="d_depot_ID">
                        <?php                                
                            foreach($this->depotList as $k => $v)
                            {
                        ?>
                            <option class="d_depot_ID_item" label="<?php  echo $v['d_Name'];?>" id="<?php  echo $k;?>" value="<?php  echo $k;?>" <?php  if($k==$this->driverInfo['d_depot_ID']){ echo "selected='selected'";} ?>   ><?php  echo $v['d_Name'];?></option>
                        <?php  } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><br/><hr/></td>
                </tr>
            </table>
            <table width="100%" border="1" cellpadding="5" cellspacing="0">
                <tr>
                    <td><label class="required" for="d_First_Name"><span>*</span>First Name:</label></td>
                    <td><input type="text" value="<?php echo $this->driverInfo['d_First_Name']; ?>" id="d_First_Name" name="d_First_Name"></td>
                    <td><label class="required" for="d_Gender"><span>*</span>Sex</label></td>
                    <td>
                        <select id="d_Gender" name="d_Gender">
                        <?php                                    
                            foreach($_SESSION['driver_info']['DriverGender_list'] as $k => $v)
                            {
                        ?>
                            <option label="<?php echo $v;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_Gender']){ echo "selected='selected'";} ?>><?php echo $v;?></option>
                        <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label class="optional" for="d_Middle_Name">Middle Name:</label></td>
                    <td><input type="text" value="<?php echo $this->driverInfo['d_Middle_Name']; ?>" id="d_Middle_Name" name="d_Middle_Name"></td>
                    <td><label class="d_Hair_Color" for="d_Hair_Color">Hair Color</label></td>
                    <td>
                        <select id="d_Hair_Color" name="d_Hair_Color" class="optional">
                            <option value="" disabled="disabled"  selected="selected">- Select -</option>
                        <?php
                            foreach($_SESSION['driver_info']['DriverHairColor_list'] as $k => $v)
                            {
                        ?>
                            <option label="<?php echo $v;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_Hair_Color']){ echo "selected='selected'";} ?>><?php echo $v;?></option>
                        <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label class="required" for="d_Last_Name"><span>*</span>Last Name:</label></td>
                    <td><input type="text" value="<?php echo $this->driverInfo['d_Last_Name']; ?>" id="d_Last_Name" name="d_Last_Name"></td>
                    <td><label class="d_Eye_Color" for="d_Eye_Color">Eye Color</label></td>
                    <td>
                        <select id="d_Eye_Color" name="d_Eye_Color" class="optional">
                            <option value="" disabled="disabled" selected="selected">- Select -</option>
                        <?php
                            foreach($_SESSION['driver_info']['DriverEyeColor_list'] as $k => $v)
                            {
                        ?>
                            <option label="<?php echo $v;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_Eye_Color']){ echo "selected='selected'";} ?>><?php echo $v;?></option>
                        <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label class="required" ><span>*</span>Date Of Birth:</label></td>
                    <td>
                    <?php
                        $date->set($this->driverInfo['d_Date_Of_Birth']);
                        echo  $date->toString("MM/ddYYYY");
                    ?>
                    </td>
                    <td><label class="d_Height_Feet" for="d_Height_Feet">Height Feet</label></td>
                    <td>
                        <select id="d_Height_Feet" name="d_Height_Feet" class="optional">
                            <option value="" disabled="disabled" selected="selected">- Select -</option>
                        <?php
                            for($i=1;$i<=9;$i++)
                            {
                        ?>
                            <option label="<?php echo $i;?>" value="<?php echo $i;?>" <?php if($i==$this->driverInfo['d_Height_Feet']){ echo "selected='selected'";} ?>><?php echo $i;?></option>
                        <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label class="required" ><span>*</span>Social Security #:</label></td>
                    <td><?php echo $this->driverInfo['d_Driver_SSN']?></td>
                    <td><label class="d_Height_Inches" for="d_Height_Inches">Height Inches</label></td>
                    <td>
                        <select id="d_Height_Inches" name="d_Height_Inches" class="optional">
                            <option value="" disabled="disabled" selected="selected">- Select -</option>
                        <?php
                            for($i=1;$i<=11;$i++)
                            {
                        ?>
                            <option label="<?php echo $i;?>" value="<?php echo $i;?>" <?php if($i==$this->driverInfo['d_Height_Inches']){ echo "selected='selected'";} ?>><?php echo $i;?></option>
                        <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label class="required" for="d_Telephone_Number1"><span>*</span>#1 Telephone_Number:</label></td>
                    <td><input type="text" value="<?php echo $this->driverInfo['d_Telephone_Number1']; ?>" id="d_Telephone_Number1" name="d_Telephone_Number1"></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td><label class="optional" for="d_Telephone_Number2">#2 Telephone_Number:</label></td>
                    <td><input type="text" value="<?php echo $this->driverInfo['d_Telephone_Number2']; ?>" id="d_Telephone_Number2" name="d_Telephone_Number2"></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td><label class="optional" for="d_Telephone_Number3">#3 Telephone_Number:</label></td>
                    <td><input type="text" value="<?php echo $this->driverInfo['d_Telephone_Number3']; ?>" id="d_Telephone_Number3" name="d_Telephone_Number3"></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="4">
                        <input type="submit" value="Save" id="Driver_Personal_Information" name="Driver_Personal_Information" />
                        <br/>
                        <hr/>
                    </td>
                </tr>
            </table>
        </form>
        </td>
    </tr>
</table>
<FORM id='NewDIW_Address' name="NewDIW_Address">
    <table border="1" width="100%">
        <tr>
            <td colspan="4">
                <h3 style="color:#F00"> Please fill in Addresses for the last 3 years.</h3>
                <div id="currentDriverAddressHistoryList"></div>
                <script type="text/javascript">
                    refreshAddressHistoryRecords(<?php echo $this->driverId;?>);
                </script>
                <fieldset class="hasBorder">
                    <legend>Add Address:</legend>
                    <span id="error_custom"></span>
                    <INPUT type="hidden" id="dah_Driver_ID" name="dah_Driver_ID"	value="<?php echo $this->driverId;?>" />
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">
                        <tr height="30" valign=middle>
                            <td class="MainText" width="150"><label class="required" for="dah_Address1"><span>*</span>Street:</label></td>
                            <td class="MainTextB">
                                <Input type="text" id="dah_Address1" name="dah_Address1" size="50" maxlength="200" />
                            </td>
                        </tr>
                        <tr height="30" valign=middle>
                            <td class="MainText"><label class="required" for="dah_City"><span>*</span>City:</label></td>
                            <td class="MainText">
                                <input type="text" id="dah_City" name="dah_City" size=15 maxlength="50" />&nbsp;&nbsp;&nbsp;
                                <label class="required" for="dah_State"><span>*</span>State:</label>
                                <SELECT id='dah_State' name='dah_State'>
                                    <OPTION value='-' selected>-</OPTION>
                                <?php
                                                                        foreach($this->stateList as $k => $v)
                                {
                                    ?>
                                        <option label="<?php echo $v['s_name'];?>" value="<?php echo $k;?>" ><?php echo $v['s_name'];?></option>
                                    <?php
                                        }
                                ?>
                                </SELECT>&nbsp;&nbsp;&nbsp;
                                <label class="required" for="dah_Postal_Code"><span>*</span>Zip: </label><Input type="text" id="dah_Postal_Code" name="dah_Postal_Code" size=10 maxlength="20">
                            </td>
                        </tr>
                        <tr height=30 valign=middle>
                            <td class="MainText"><label class="required" for="dah_Phone"><span>*</span>Phone:</label></td>
                            <td class="MainText"><Input type="text" id="dah_Phone" name="dah_Phone" size=30></td>
                        </tr>
                        <tr height=30 valign=middle>
                            <td class="MainText">At Address:</td>
                            <td class="MainText">
                                <label class="required" for="dah_Start_Date"><span>*</span>From Date: </label><Input type="text" readonly="readonly" id="dah_Start_Date" name="dah_Start_Date" size=10 maxlength=10   />&nbsp;&nbsp;&nbsp;&nbsp;
                                <label class="required" for="dah_End_Date"><span>*</span>To Date: </label><Input type="text" readonly="readonly" id="dah_End_Date" name="dah_End_Date" size=10 maxlength=10 />

                            </td>
                        </tr>
                        <tr height=30 valign=middle>
                            <td class="MainText">Is this current Address:</td>
                            <td class="MainText">
                                <select name="dah_Current_Address">
                                    <option value="NO" selected>No</option>
                                    <option value="YES">Yes</option>
                                </select>
                            </td>
                        </tr>
                        <tr height=40 valign=middle>
                            <td class="MainText" align=center>&nbsp;</td>
                            <td class="MainText" align=left>
                                <a onclick="addAddressHistoryRecord();" class="MainLink2">
                                    <font color="#0000cc">Click here to Save new Address</font></a>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </td>
        </tr>
    </table>
</form>
<br/>
<hr/>

<script type="text/javascript">
    $(function() {
        $("#d_Date_Of_Birth").datepicker();
        $("#dah_Start_Date").datepicker();
        $("#dah_End_Date").datepicker();
    });

</script>
