<?php
    echo $this->navigation()->menu()->render(); ?>
<table border="1" width="100%">
    <tr>
        <td colspan="2" align="center"><h2 style="background:#00f; color:#FFF;">DRIVER INFORMATION WORKSHEET</h2></td>
    </tr>
    <tr>
        <td width="300px"><b>Driver:</b></td>
        <td width="300px" align="right">
            <a href="/driver/new-Driver/new-Driver-Complete/id/<?php echo $this->driverId;?>" >Complete</a> |
            <a href="/driver/new-Driver/new-Driver-Decline/id/<?php echo $this->driverId;?>" >Decline</a> |
        </td>
    </tr>
    <tr>
        <td colspan="2" bgcolor="#ccffcc"><b>Driver Information:</b></td>
    </tr>
    <tr>
        <td colspan="2">
                <form action="/driver/new-Driver/new-Driver-Complete/id/6" method="post" enctype="application/x-www-form-urlencoded" id="driver_DriverPersonalInformation_Form">
                    <table width="100%" border="1" cellpadding="5" cellspacing="0">
                        <tr>
                            <td>
                                <label class="required" for="d_Employment_Type">Application Type</label>
                            </td>
                            <td>
                                <select id="d_Employment_Type" name="d_Employment_Type">
                                <?php
                                    foreach($_SESSION['driver_info']['DriverEmploymentType_list'] as $k => $v)
                                    {
                                ?>
                                    <option label="<?php echo $v;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_Employment_Type']){ echo "selected='selected'";} ?>><?php echo $v;?></option>
                                <?php
                                    }
                                ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="optional" for="entrydate">Entry Date</label>
                            </td>
                            <td>
                                <?php echo $this->driverInfo['d_Entry_Date']?>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="optional" for="status">Status</label></td>
                            <td><input type="text" disabled="disabled" value="<?php echo $_SESSION['driver_info']['DriverStatus_list'][$this->driverInfo['d_Status']];?>" id="status" name="status"></td>
                        </tr>
                        <tr>
                            <td><label class="required" for="d_homebase_ID">Homebase</label></td>
                            <td>
                                <select id="d_homebase_ID" name="d_homebase_ID">
                            <?php
                                foreach($this->homebaseList as $k => $v)
                                {
                            ?>
                                    <option class="d_homebase_ID_item" onclick="addClickHandlers(<?php echo $k;?>)" label="<?php echo $v['h_Name'];?>" id="<?php echo $k;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_homebase_ID']){ echo "selected='selected'";} ?>   ><?php echo $v['h_Name'];?></option>
                            <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="optional" for="d_depot_ID">Depot</label></td>
                            <td>
                                <select id="d_depot_ID" name="d_depot_ID">
                                    <option value="">- Select HomeBase first -</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><br/><hr/></td>
                        </tr>
                    </table>
                    <table width="100%" border="1" cellpadding="5" cellspacing="0">
                        <tr>
                            <td><label class="required" for="d_First_Name">First Name:</label></td>
                            <td><input type="text" value="" id="d_First_Name" name="d_First_Name"></td>
                           <td><label class="required" for="d_Gender">Sex</label></td>
                            <td>
                                <select id="d_Gender" name="d_Gender">
                            <?php
                                foreach($_SESSION['driver_info']['DriverGender_list'] as $k => $v)
                                {
                            ?>
                                    <option label="<?php echo $v;?>" value="<?php echo $k;?>" <?php if($k==$this->driverInfo['d_Gender']){ echo "selected='selected'";} ?>><?php echo $v;?></option>
                            <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="optional" for="d_Middle_Name">Middle Name:</label></td>
                            <td><input type="text" value="" id="d_Middle_Name" name="d_Middle_Name"></td>
                            <td><label class="d_Hair_Color" for="d_Hair_Color">Hair Color</label></td>
                            <td>
                                <select id="d_Hair_Color" name="d_Hair_Color" class="optional">
                                    <option value="" disabled="disabled"  selected="selected">- Select -</option>
                            <?php
                                foreach($_SESSION['driver_info']['DriverHairColor_list'] as $k => $v)
                                {
                            ?>
                                    <option label="<?php echo $v;?>" value="<?php echo $k;?>"><?php echo $v;?></option>
                            <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="required" for="d_Last_Name">Last Name:</label></td>
                            <td><input type="text" value="" id="d_Last_Name" name="d_Last_Name"></td>
                            <td><label class="d_Eye_Color" for="d_Eye_Color">Eye Color</label></td>
                            <td>
                                <select id="d_Eye_Color" name="d_Eye_Color" class="optional">
                                    <option value="" disabled="disabled" selected="selected">- Select -</option>
                            <?php
                                foreach($_SESSION['driver_info']['DriverEyeColor_list'] as $k => $v)
                                {
                            ?>
                                    <option label="<?php echo $v;?>" value="<?php echo $k;?>"><?php echo $v;?></option>
                            <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="required" for="d_Date_Of_Birth">Date Of Birth:</label></td>
                            <td><input type="text" value="<?php echo $this->driverInfo['d_Date_Of_Birth']?>" id="d_Date_Of_Birth" name="d_Date_Of_Birth"  onfocus='showCalendar("",this,this,"","d_Date_Of_Birth",0,30,1)' readonly="readonly" style="background:#fff;" /></td>
                            <td><label class="d_Height_Feet" for="d_Height_Feet">Height Feet</label></td>
                            <td>
                                <select id="d_Height_Feet" name="d_Height_Feet" class="optional">
                                    <option value="" disabled="disabled" selected="selected">- Select -</option>
                            <?php
                                for($i=1;$i<=9;$i++)
                                {
                            ?>
                                    <option label="<?php echo $i;?>" value="<?php echo $i;?>"><?php echo $i;?></option>
                            <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="required" for="d_Driver_SSN">Social Security #:</label></td>
                            <td><?php echo $this->driverInfo['d_Driver_SSN']?></td>
                            <td><label class="d_Height_Inches" for="d_Height_Inches">Height Inches</label></td>
                            <td>
                                <select id="d_Height_Inches" name="d_Height_Inches" class="optional">
                                    <option value="" disabled="disabled" selected="selected">- Select -</option>
                            <?php
                                for($i=1;$i<=11;$i++)
                                {
                            ?>
                                    <option label="<?php echo $i;?>" value="<?php echo $i;?>"><?php echo $i;?></option>
                            <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="required" for="d_Telephone_Number1">#1 Telephone_Number:</label></td>
                            <td><input type="text" value="" id="d_Telephone_Number1" name="d_Telephone_Number1"></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><label class="optional" for="d_Telephone_Number2">#2 Telephone_Number:</label></td>
                            <td><input type="text" value="" id="d_Telephone_Number2" name="d_Telephone_Number2"></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><label class="optional" for="d_Telephone_Number3">#3 Telephone_Number:</label></td>
                            <td><input type="text" value="" id="d_Telephone_Number3" name="d_Telephone_Number3"></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><label class="required" for="d_Telephone_Number1">1 Telephone_Number:</label></td>
                            <td><input type="text" value="" id="d_Telephone_Number1" name="d_Telephone_Number1"></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td colspan="4">
                                <br/>
                                <hr/>
                                <h3 style="color:#F00"> Please fill in Addresses for the last 3 years.</h3>
                                <fieldset>
                                    <legend>Add Address:</legend>
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">
                                    <FORM id='NewDIW_Address' method="Post" name="SaveForm">
                                        <INPUT type="hidden" id="dah_Driver_ID" name="dah_Driver_ID"	value="<?php echo $this->driverId;?>">
                                        <tr height=30 valign=middle>
                                            <td class="MainText" width="150">Street:</td>
                                            <td class="MainTextB">
                                                <Input type="text" name="dah_Address1" size=50 maxlength=200>
                                            </td>
                                        </tr><tr height=30 valign=middle>
                                            <td class="MainText">City:</td>
                                            <td class="MainText">
                                                <Input type="text" name="dah_City" size=15 maxlength="50">&nbsp;&nbsp;&nbsp;
                                                State:
                                                <SELECT name='dah_State'>
                                                    <OPTION value='-' selected>-</OPTION>
                                                <?php 
                                                    foreach($this->stateList as $k => $v)
                                                    {
                                                ?>
                                                    <option label="<?php echo $v['s_name'];?>" value="<?php echo $k;?>" ><?php echo $v['s_name'];?></option>
                                                <?php
                                                    }
                                                ?>
                                                </SELECT>&nbsp;&nbsp;&nbsp;
                                                Zip: <Input type="text" name="Zip" size=10 maxlength="20">
                                            </td>
                                        </tr>
                                        <tr height=30 valign=middle>
                                            <td class="MainText">Phone:</td>
                                            <td class="MainText"><Input type="text" name="Phone" size=30></td>
                                        </tr>
                                        <tr height=30 valign=middle>
                                            <td class="MainText">At Address:</td>
                                            <td class="MainText">
                                                From Date: <Input type="text" name="FromDate" size=10 maxlength=10>&nbsp;&nbsp;&nbsp;&nbsp;
                                                To Date: <Input type="text" name="FromDate" size=10 maxlength=10>
                                                
                                            </td>
                                        </tr>
                                        <tr height=30 valign=middle>
                                            <td class="MainText">Is this current Address:</td>
                                            <td class="MainText">
                                                <select name="CurrAddress">
                                                    <option value="No" selected>No</option>
                                                    <option value="Yes">Yes</option>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr height=40 valign=middle>
                                            <td class="MainText" align=center>&nbsp;</td>
                                            <td class="MainText" align=left>
                                                <a onclick="addAddressHistoryRecord();" class="MainLink2">
                                                    <font color="#0000cc">Click here to Save new Address</font></a>
                                            </td>
                                        </tr>

                                    </FORM>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                    <br/>
                    <hr/>
                
<input type="submit" value="Save" id="Driver_Personal_Information" name="Driver_Personal_Information">
            </form>
        </td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>