
<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                    echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>

<div class="new-appl" id="main">
    <div class="parametr-top"><div class="parametr-bottom"><div class="parametr-middle">
      <form action="/driver/new-Driver/new-Driver-Search" class="select-parametr new-appl" method="post" enctype="application/x-www-form-urlencoded" id="new-Driver-Search">
        <h2>NEW APPLICATION - LOOK FOR A DRIVER</h2>
        <div style="color:#cc0000; text-align:left; margin-left:100px;">
            <?php
             if(isset($this->systemMessage)){ echo $this->systemMessage;}
            ?>
        </div>
        <span class="discr">(Select Parameters)</span>
        <fieldset>
            <label><span>*</span> Application for :</label>
              <span class="radio-button"><input type="radio" value="4" id="d_Employment_Type-4" name="d_Employment_Type" />&nbsp;Employee</span>
              <span class="radio-button"><input type="radio" value="3" id="d_Employment_Type-3" name="d_Employment_Type" />&nbsp;Contractor</span>
            <label for="d_Driver_SSN"><span>*</span>Driver SSN :</label>
                <input type="text" id="d_Driver_SSN" value="numbers only" name="d_Driver_SSN" onfocus="if(this.value=='numbers only'){this.value='';}"/>
            <label for="d_Date_Of_Birth"><span>*</span>Driver Date Of Birth:</label>
                <input type="text" id="d_Date_Of_Birth" value="mm/dd/yyyy" name="d_Date_Of_Birth" onfocus="if(this.value=='mm/dd/yyyy'){this.value='';}"  />
            <p class="link-app"><span>Application Form to be filled:</span></p>
			<div class="clear"></div>
			<br><br>
			<center>
            <table>
				<tbody><tr>
					<td><span><input class="blue_button_input" type="submit" value="By Driver" id="Driver" name="Driver"/></span></td>
					<td><span><input class="blue_button_input" type="submit" value="By Administrator" id="Administrator" name="Administrator"/></span>
				</td></tr>
			</tbody></table>
			</center>
        </fieldset>
      </form>
    </div></div></div>

<script type="text/javascript">
$(function() {
  $("#d_Date_Of_Birth").datepicker({
   changeMonth: true,
   changeYear: true,
            yearRange: '1950:2020'
  });
});

</script>
    </div>
