<h2>Current Users</h2>
<?php
if ($this->users != null) {
?>
    <table>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Role</th>
        </tr>
        <?php echo $this->partialLoop('partials/_user-row.phtml', $this->users); ?>
    </table>
<?php
} else {
?>
    <p>You do not have any users yet.</p>
<?php
}
?>
<p><a href='/user/create'>Create a new user</a></p> 