<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../application/controllers/ErrorController.php';

/**
 * Test class for ErrorController.
 * Generated by PHPUnit on 2010-10-24 at 13:10:26.
 */
class ErrorControllerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var ErrorController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ErrorController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @todo Implement testErrorAction().
     */
    public function testErrorAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetLog().
     */
    public function testGetLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testNoauthAction().
     */
    public function testNoauthAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}

?>
