    <table cellspacing="0" class="inform" id="add_Employment_Table">
        <tr height="30" valign=middle>
            <td class="" width="150"><div id="error_custom_add_Employment_Table" class="error_custom2"></div></td>
            <td class="">
                <input type="hidden" value="<?php echo $this->driverId?>" name="pe_Driver_ID" />
            </td>
        </tr>
        <tr height="30" valign=middle>
            <td width="150"><label class="required" for="pe_Employer_Name"><span>*</span>Employer:</label></td>
            <td >
                <Input type="text" id="pe_Employer_Name" name="pe_Employer_Name" size="50" maxlength="250" />
            </td>
        </tr>
        <tr height="30" valign=middle>
            <td width="150"><label class="required" for="pe_Address1"><span>*</span>Street:</label></td>
            <td >
                <Input type="text" id="pe_Address1" name="pe_Address1" size="50" maxlength="250" />
            </td>
        </tr>
        <tr height="30" valign=middle>
            <td class=""><label class="required" for="pe_City"><span>*</span>City:</label></td>
            <td class="">
                <input type="text" id="pe_City" name="pe_City" size=15 maxlength="250" />&nbsp;&nbsp;&nbsp;
                <label class="required" for="pe_State"><span>*</span>State:</label>
                <SELECT id='pe_State' name='pe_State'>
                    <OPTION value='-' selected>-</OPTION>
                    <?php
                        foreach($this->stateList as $k => $v)
                        {
                    ?>
                        <option label="<?php echo $v['s_name'];?>" value="<?php echo $k;?>" ><?php echo $v['s_name'];?></option>
                    <?php
                        }
                    ?>
                </SELECT>&nbsp;&nbsp;&nbsp;
                <label class="required" for="pe_Postal_Code"><span>*</span>Zip: </label><Input type="text" id="pe_Postal_Code" name="pe_Postal_Code" size=10 maxlength="20">
            </td>
        </tr>
        <tr height=30 valign=middle>
            <td class=""><label class="required" for="pe_Phone"><span>*</span>Phone:</label></td>
            <td class=""><Input type="text" id="pe_Phone" name="pe_Phone" size=30></td>
        </tr>
        <tr height=30 valign=middle>
            <td class=""><label class="required" for="pe_Fax">Fax:</label></td>
            <td class=""><Input type="text" id="pe_Fax" name="pe_Fax" size=30></td>
        </tr>
        <tr height="30" valign=middle>
            <td width="150"><label class="required" for="pe_Position"><span>*</span>Job Description:</label></td>
            <td >
                <Input type="text" id="pe_Position" name="pe_Position" size="50" maxlength="250" />
            </td>
        </tr>
        <tr height=30 valign=middle>
            <td class=""></td>
            <td class="">
            <label class="required" for="pe_Employment_Start_Date"><span>*</span>From: </label>
                <Input type="text" readonly="readonly" id="pe_Employment_Start_Date" name="pe_Employment_Start_Date" size=10 maxlength=10   />&nbsp;&nbsp;&nbsp;&nbsp;
            <label class="required" for="pe_Employment_Stop_Date">To: </label>
                <Input type="text" readonly="readonly" id="pe_Employment_Stop_Date" name="pe_Employment_Stop_Date" size=10 maxlength=10 />

            </td>
        </tr>
        <tr height="30" valign="top">
            <td width="150" style="vertical-align:top;">Reason for Leaving:</td>
            <td >
                <textarea type="text" id="pe_Reason_for_Leaving" name="pe_Reason_for_Leaving" cols="38" rows="7" maxlength="250" ></textarea>
            </td>
        </tr>
        <tr height=30 valign=middle>
            <td class=""></td>
            <td class="">
            DOT Safety Sensitive:&nbsp;&nbsp;
            <select name="pe_DOT_Safety_Sensitive_Function">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>&nbsp;&nbsp;&nbsp;&nbsp;
            FMCSR Regulated:&nbsp;&nbsp;
            <select name="pe_FMCSR_Regulated">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>
            </td>
        </tr>
        <tr height=30 valign=middle>
            <td class=""></td>
            <td class="">
            Interstate:&nbsp;&nbsp;
            <select name="pe_Interstate">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>&nbsp;&nbsp;&nbsp;&nbsp;
            Intrastate:&nbsp;&nbsp;
            <select name="pe_Intrastate">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>&nbsp;&nbsp;&nbsp;&nbsp;
            Intermodal:&nbsp;&nbsp;
            <select name="pe_Intermodal">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>
            </td>
        </tr>
        <tr height=40 valign=middle>
            <td class="" align=center>&nbsp;</td>
            <td class="" align=left>
            <a onclick="addEmploymentHistoryRecord();" >
                <font color="#0000cc">Click here to Add new Employer</font></a>
            </td>
        </tr>
    </table>