
    <input type="hidden" value="<?php echo $this->driverId?>" name="dpe_Driver_ID" />
<table cellspacing="0" class="inform" id="add_Employment_Table">
    <tbody>
    <tr>
        <td><label class="required" for="emp_Employer_Name"><span>*</span>Employer:</label></td>
        <td>
            <Input type="hidden" id="emp_ID" name="emp_ID" size="50" maxlength="250" />
            <Input type="text" id="emp_Employer_Name" name="emp_Employer_Name" size="50" maxlength="250" onkeyup="autocomplete_custom('emp_Employer_Name')" /> <img src="/images/indicator.gif" id="emp_Employer_Name_indicator" style="display:none;" alt="">
            <div class="ac_results" id="emp_Employer_Name_ul" style="display:none; position: absolute; border: 1px solid rgb(170, 170, 170); width: 324px; background: none repeat scroll 0% 0% rgb(255, 255, 255);" >
            </div>
        </td>
    </tr>
    <tr class="color-dark">
        <td><label class="required" for="emp_Address1"><span>*</span>Street:</label></td>
		<td>
            <Input type="text" id="emp_Address1" name="emp_Address1" size="50" maxlength="250" />&nbsp;<br/>
            <label class="required" for="emp_City"><span>*</span>City:</label><input type="text" id="emp_City" name="emp_City" size=15 maxlength="250" /> &nbsp;
            <label class="required" for="emp_State_ID"><span>*</span>State:</label>
                <SELECT id='emp_State_ID' name='emp_State_ID'>
                    <OPTION value='-' selected>-</OPTION>
                    <?php
                        foreach($this->stateList as $k => $v)
                        {
                    ?>
                        <option label="<?php echo $v['s_name'];?>" value="<?php echo $k;?>" ><?php echo $v['s_name'];?></option>
                    <?php
                        }
                    ?>
                </SELECT> &nbsp;
            <label class="required" for="emp_Postal_Code"><span>*</span>Zip: </label><Input type="text" id="emp_Postal_Code" name="emp_Postal_Code" size=10 maxlength="20" />
        </td>
    </tr>
    <tr>
        <td><label class="required" for="emp_Phone"><span>*</span>Phone:</label></td>
        <td>
            <Input type="text" id="emp_Phone" name="emp_Phone" size="30" /> &nbsp;
            <label class="required" for="emp_Fax"><span>*</span>Fax:</label>&nbsp; <Input type="text" id="emp_Fax" name="emp_Fax" size="30" />
        </td>
    </tr>
    <tr class="color-dark">
        <td><label class="required" for="dpe_Position"><span>*</span>Job Description:</label></td>
        <td>
            <Input type="text" id="dpe_Position" name="dpe_Position" size="50" maxlength="250" />
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <label class="required" for="dpe_Employment_Start_Date"><span>*</span>From: </label>
            <Input type="text" readonly="readonly" id="dpe_Employment_Start_Date" name="dpe_Employment_Start_Date" size=10 maxlength=10   />&nbsp;&nbsp;&nbsp;&nbsp;
            <label class="required" for="dpe_Employment_Stop_Date">To: </label>
            <Input type="text" readonly="readonly" id="dpe_Employment_Stop_Date" name="dpe_Employment_Stop_Date" size=10 maxlength=10 />
        </td>
    </tr>
    <tr class="color-dark">
        <td><label class="required" for="dpe_Salary"><span>*</span>Salary:</label></td>
        <td><input type="text" id="dpe_Salary" name="dpe_Salary"  maxlength="10" /></td></tr>
    <tr>
    <tr>
        <td><label class="required" for="dpe_Reason_for_Leaving"><span>*</span>Reason For Leaving:</label></td>
        <td><input type="text" id="dpe_Reason_for_Leaving" name="dpe_Reason_for_Leaving"  maxlength="250" size="50" /></td></tr>
    <tr class="color-dark">
        <td class=""></td>
        <td class="">
            DOT Safety Sensitive:&nbsp;&nbsp;
            <select name="emp_DOT_Safety_Sensitive_Function" id="emp_DOT_Safety_Sensitive_Function">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>&nbsp;&nbsp;&nbsp;&nbsp;
            FMCSR Regulated:&nbsp;&nbsp;
            <select name="emp_FMCSR_Regulated" id="emp_FMCSR_Regulated">
                <option value="NO" selected>No</option>
                <option value="YES">Yes</option>
            </select>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><span class="blue-button float-left"><a id="addEmploymentHistoryRecord" onclick="this.setAttribute('class', 'button-updating');this.innerHTML='Updating...'; addEmploymentHistoryRecord();">Add new Employer</a></span></td>
    </tr>
    <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody>
    </table>