
<?php
    $date = new Zend_Date();
    $Drivers=$this->drivers;
    for($i=0;$i<sizeof($Drivers);$i++){
?>
<tr <?php
    if(gettype($i/2) == 'double'){ echo " class='color-dark' ";}
?>>
    <td><?php echo $Drivers[$i]['d_First_Name']; ?></td>
    <td><?php echo $Drivers[$i]['d_Last_Name']; ?></td>
    <td><?php
            echo  $Drivers[$i]['d_Driver_SSN'];
         ?></td>
    <td>
    <?php
    echo  $_SESSION['driver_info']['DriverEmploymentType_list'][$Drivers[$i]['d_Employment_Type']];
    ?>
    </td>
    <td><?php echo $_SESSION['driver_info']['DriverStatus_list'][$Drivers[$i]['d_Status']]; ?></td>
    <td>
    <?php
        $date->set($Drivers[$i]['d_Entry_Date'],"yyyy-MM-dd");
        echo  $date->toString("MM/dd/yyyy");

    ?>
    </td>
    <td></td>
    <td class="link-profile"><a href="/driver/driver/view-driver-Information/id/<?php echo $Drivers[$i]['d_ID'];?>" >View</a>&nbsp;|&nbsp;<a href="#">Accounts</a></td>
</tr>
        <?php } ?>