    <tbody id="edit_hos_list">
        <tr style="display:none;">
            <td><input type="text" id="edit_dhos_Driver_ID" size="8" value="<?php echo $this->driverId;?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[6]['dhos_date'];?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[5]['dhos_date'];?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[4]['dhos_date'];?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[3]['dhos_date'];?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[2]['dhos_date'];?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[1]['dhos_date'];?>" /></td>
            <td><input type="text" name="edit_dhos_date" size="8" value="<?php echo $this->currentDriverHoSList[0]['dhos_date'];?>" /></td>
        </tr>
        <tr class="color-dark" align="center">
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[6]['dhos_hours'];?>" /></td>
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[5]['dhos_hours'];?>" /></td>
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[4]['dhos_hours'];?>" /></td>
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[3]['dhos_hours'];?>" /></td>
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[2]['dhos_hours'];?>" /></td>
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[1]['dhos_hours'];?>" /></td>
            <td><input type="text" maxlength="2" name="edit_dhos_hours" size="5" value="<?php echo $this->currentDriverHoSList[0]['dhos_hours'];?>" /></td>
        </tr>
    </tbody>