<?php
if(sizeof($this->drivers>$this->step)){
        $url = $_SERVER['REQUEST_URI'];
        if($_GET['status']==null){
            $url = $url."?status=0";
        }
        if($_GET['from']==null){
            $url = $url."&from=0";
        }
        if(!$_GET['step']){
            $url = $url."&step=".$this->step;
        }

        if($this->from>0){
            $from = $_GET['from']-$this->step;
            if($from<0){$from=0;}
            $url = preg_replace("/from[=][0-9]+/","from=".$from."",$url);
            $url = preg_replace("/step[=][0-9]+/","step=".$this->step,$url);
            ?>
<a href="<?php echo $url;?>"><< Prev <?php echo $this->step; ?> records</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <?php

        }
        if($this->last<sizeof($this->drivers)){
            $from = $_GET['from']+$this->step;
            if($from<0){$from=0;}
            $url = preg_replace("/from[=][0-9]+/","from=".$from."",$url);
            $url = preg_replace("/step[=][0-9]+/","step=".$this->step,$url);
            ?>
<a href="<?php echo $url;?>">Next <?php echo $this->step; ?> records >></a>
            <?php
        }
    }
?>