<html>
<head>
    <link rel="stylesheet" href="/css/main.css" type="text/css" />
</head>
<table border='1' cellpadding="0" cellspacing="0" width="1100px">
        <tr>
            <td colspan="6"></td>
            <td><a href="/user/logout">Logout</a></td>
        </tr>
        <tr>
            <td><a href="/company/index/index">Company module</a></td>
            <td><a href="/report/index/index">Report module</a></td>
            <td><a href="/company/parent-company/index">Parent Company module</a></td>
            <td><a href="/driver">Driver module</a></td>
            <td><a href="/equipment/index/index">Equipment module</a></td>
            <td><a href="/user/list">user module</a></td>
        </tr>
</table>
