<table border='1' cellpadding="0" cellspacing="0" width="1100px">
        <tr>
            <td colspan="6"></td>
            <td><a href="/user/logout">Logout</a></td>
        </tr>
        <tr>
            <td><a href="/company/index/index">Company module</a></td>
            <td><a href="/report/index/index">Report module</a></td>
            <td>Parent Company</td>
            <td>State</td>
            <td>Start Date</td>
            <td>Status</td>
            <td>Action</td>
        </tr>
</table>