<table cellspacing="0" class="inform addMaintenanceTableClass" style="float: none; width: 889px;">
    <tbody>
        <tr class="title-dark">
            <?php if ($this->identity->permissions->equipment_maintenance_create_permission === true) : ?>
                <td colspan="2">
                    ADD MAINTENANCE [ <a class="MaintenanceAddLinkClass" onclick="$('.addMaintenanceTableClass').toggle('slow');">VIEW</a> ]
                </td>
            <?php endif; ?>
        </tr>
    </tbody>
</table>
<table cellspacing="0" class="inform addMaintenanceTableClass" id="addMaintenanceTable" style="display : none; float: none; width: 889px;">
    <tr class="title-dark">
        <td colspan="2">
            ADD MAINTENANCE [ <a class="MaintenanceAddLinkClass" onclick="$('.addMaintenanceTableClass').toggle('slow');">HIDE</a> ]
        </td>
    </tr>
    <tr>
        <td class="" width="150">
            <div id="errorCustomAddMaintenanceTable" class="error_custom2">
            </div>
        </td>
    </tr>
    <tr  class="color-dark">
        <td width="150">
            <label class="required">
                <span>*</span>Requested Date:
            </label>
        </td>
        <td>
            <input type="text" class="RequestedDate maintenanceDate" id="em_requested_date"
                   size=12 />&nbsp;&nbsp;&nbsp;
            <label class="required">
                <span>*</span>Completed Date:
            </label>
            <input type="text" class="CompletedDate maintenanceDate" id="em_completed_date"
                   size=12 />
        </td>
    </tr>
    <tr>
        <td width="150">
            <label class="required">
                <span>*</span>Next Maintenance Date:
            </label>
        </td>
        <td>
            <input type="text" class="NextMaintenanceDate maintenanceDate" id="em_next_maintenance_date"
                   size=12 />&nbsp;&nbsp;&nbsp;
            <label class="required">
                <span>*</span>Service Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </label>
            <input type="text" class="CompletedDate maintenanceDate" id="em_service_date"
                   size=12 />
        </td>
    </tr>
    <tr  class="color-dark">
        <td width="150">
            <label>
                Service Provider:
            </label>
        </td>
        <td>
            <select id="em_service_provider_id" >
                    <?php
                        foreach ($this->spList as $sp_ind => $sp_name) {
                          echo '<option value="' . $sp_ind . '">' . $sp_name . '</option>';
                        }
                    ?>
            </select>
            &nbsp;&nbsp;&nbsp;
            <label>
                Amount:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </label>
            <input type="text" class="Amount" id="em_invoice_amount"
                   size=12 />
            <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                DOT reported:
            </label>
            <input type="radio" class="DOTreported"
                   name="em_dot_regulated" id="em_dot_regulated_yes"
                   value="Yes" />&nbsp;Yes
            <input type="radio" class="DOTreported"
                   name="em_dot_regulated" id="em_dot_regulated_no"
                   value="No" checked="checked" />&nbsp;No
        </td>
    </tr>
    <tr>
        <td width="150" style="vertical-align: top;">
            Notes :
        </td>
        <td>
            <textarea cols="40" rows="3" id="em_notes"></textarea>
        </td>
    </tr>
    <tr height=40 valign=middle>
        <td class="" align=center>&nbsp;</td>
        <td class="" align=left>
            <span class="blue-button float-left">
                <a id="addMaintenance"  class="saveBlockButtonClass" onclick="addMaintenanceClick();">
                    Add New Maintenance
                </a>
            </span>
        </td>
    </tr>
</table>