<div class="bottom-nav">
    <span class="name-driver">
        Status:&nbsp;<span id="view_i_Status"></span>
    </span>
    <ul class="blue-nav">
        <li>
            <span>
                <a href="/incident/file/create/id/<?= $this->i_ID ?>">
                    Create File
                </a>
            </span>
        </li>
        <li>
            <span>
                <a href="/incident/index/exit/id/<?= $this->i_ID ?>">
                    Exit
                </a>
            </span>
        </li>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?= $this->breadcrumbs; ?>
            </span>
        </div>
    </div>
</div>

<div class="driver-information" id="main">
    <input type="hidden" id="i_ID" value="<?= $this->i_ID; ?>"
    <input type="hidden" id="i_Driver_ID" value="<?= $this->driverId; ?>"
        
    <div id="viewDescriptionDiv" class="DescriptionDiv">
        <?= $this->partial('partials/index/_view_description.phtml'); ?>
    </div>
    <div id="updateDescriptionDiv" class="DescriptionDiv" style="display: none;">
        <?= $this->partial('partials/index/_update_description.phtml', array('states' => $this->states)); ?>
    </div>

    <div id="viewDriverInformation" class="DriverInformationDiv">
        <?= $this->partial('partials/index/_view_driver_information.phtml', array('driverId' => $this->driverId)); ?>
    </div>

<!--    This block should be hidden. But for correct building of the multiselect element its element hided in the js-->
    <div id="updateDriverInformation" class="DriverInformationDiv">
        <?= $this->partial('partials/index/_update_driver_information.phtml', array(
            'driverId' => $this->driverId,
            'travelDirections' => $this->travelDirections
                ));
        ?>
    </div>

    <input type="hidden" id="i_Equipment_ID" />
    <div id="emptyIncidentEquipmentDiv" class="IncidentEquipment">
        <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Equipment Information - involved in Incident</th></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="/equipment/truck-files/add-involved/incidentId/<?= $this->i_ID ?>">Add Equipment Information </a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody>
                </table>
        </div></div></div>
    </div>
    <?= $this->partial('partials/index/_view_equipment.phtml', array(
            'i_ID' => $this->i_ID,
                ));
        ?>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Witness/Passenger Information - involved in Incident</th></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Add Witness/Passenger Information </a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Type of Collision<br>
                            </th></tr><tr><td>Collision Type</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Vehicle involved in collision with</td><td>&nbsp;</td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Update type Of Collision </a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform adress">
                    <tbody><tr><th colspan="7">Road conditions at the time of Incident</th></tr>
                        <tr><td>Road Conditions</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Weather Conditions</td><td>&nbsp;</td></tr>
                        <tr><td>Roadway</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Traffic Condition</td><td>&nbsp;</td></tr>
                        <tr><td>Road Surface Condition</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Traffic Control Devices</td><td>&nbsp;</td></tr>
                        <tr><td>Lightning Conditions</td><td>&nbsp;</td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Update Road Condition Information</a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform adress">
                    <tbody><tr><th>DOT Incident criteria (Applies to commercial vehicles only)</th></tr>
                        <tr><td>Incident resulted in human fatality  <br>
			Incident did not result in injuries treated immediately/away from the scene   <br>
			The vehicles have been towed away from the scene   <br>
			Driver did not receive a traffic citation.   <br>
			Accident is DOT reportable.   </td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Update DOT Accident Criteria</a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="blue-nav">
        <ul>
            <li><span><a href="/DQF">Create File</a></span></li>
            <li><span><a href="/exit">Exit</a></span></li>
        </ul>
    </div>

</div>