<div class="bottom-nav">
    <span class="name-driver">
        Status:&nbsp;<span id="view_i_Status"></span>
    </span>
    <ul class="blue-nav">
        <li>
            <span>
                <a class="createIncidentFile">
                    Create File
                </a>
            </span>
        </li>
        <li>
            <span>
                <a class="exitIncidentProfile">
                    Exit
                </a>
            </span>
        </li>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?= $this->breadcrumbs; ?>
            </span>
        </div>
    </div>
</div>

<div class="driver-information" id="main">
    <input type="hidden" id="i_ID" value="<?= $this->i_ID; ?>"
    <input type="hidden" id="i_Driver_ID" value="<?= $this->driverId; ?>"
        
    <div id="viewDescriptionDiv" class="DescriptionDiv">
        <?= $this->partial('partials/index/_view_description.phtml', array('identity' => $this->identity)); ?>
    </div>
    <div id="updateDescriptionDiv" class="DescriptionDiv updateValuesClass" style="display: none;">
        <?= $this->partial('partials/index/_update_description.phtml', array('states' => $this->states)); ?>
    </div>

    <div id="viewDriverInformation" class="DriverInformationDiv">
        <?= $this->partial('partials/index/_view_driver_information.phtml', array(
            'driverId' => $this->driverId,
            'identity' => $this->identity
                )); ?>
    </div>

<!--    This block should be hidden. But for correct building of the multiselect element its element hidden in the js-->
    <div id="updateDriverInformation" class="DriverInformationDiv updateValuesClass">
        <?= $this->partial('partials/index/_update_driver_information.phtml', array(
            'driverId' => $this->driverId,
            'travelDirections' => $this->travelDirections
                ));
        ?>
    </div>

    <input type="hidden" id="i_Equipment_ID" />
    <div id="emptyIncidentEquipmentDiv" class="IncidentEquipment">
        <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Equipment Information - involved in Incident</th></tr>
                        <?php if ($this->identity->permissions->incident_involved_equipment_create_permission === true) : ?>
                        <tr>
                            <td colspan="2">
                                <span class="blue-button">
                                    <span>
                                        <a href="/equipment/truck-files/add-involved/incidentId/<?= $this->i_ID ?>">
                                            Add Equipment Information
                                        </a>
                                    </span>
                                </span>
                            </td>
                        </tr>
                        <?php endif; ?>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody>
                </table>
        </div></div></div>
    </div>
    <?= $this->partial('partials/index/_view_equipment.phtml', array(
            'i_ID' => $this->i_ID,
            'identity' => $this->identity
                ));
        ?>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <div id="currentIncidentWitnessesList">
                    
                </div>
                <table cellspacing="0" class="inform addWitnessTableClass">
                    <tbody>
                        <tr class="title-dark">
                            <?php if ($this->identity->permissions->incident_witness_create_permission === true) : ?>
                                <td colspan="2">
                                    ADD WITNESS [ <a class="WitnessAddLinkClass">VIEW</a> ]
                                </td>
                            <?php endif; ?>
                        </tr>
                    </tbody>
                </table>
                <?php echo $this->partial('partials/index/_add-witness.phtml',array('states'=>$this->states)); ?>
    </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <div id="currentIncidentPassengersList">

                </div>
                <table cellspacing="0" class="inform addPassengerTableClass">
                    <tbody>
                    <tr class="title-dark">
                        <?php if ($this->identity->permissions->incident_passenger_create_permission === true) : ?>
                            <td colspan="2">
                                ADD PASSENGER [ <a class="PassengerAddLinkClass">VIEW</a> ]
                            </td>
                        <?php endif; ?>
                    </tr>
                    </tbody>
                </table>
                <?php echo $this->partial('partials/index/_add-passenger.phtml',array('states'=>$this->states)); ?>
    </div></div></div>
    
    <div class="post-top"><div class="post-bottom"><div class="post-middle">
        <div id="dotIncidentDiv">
        </div>
        
    </div></div></div>

    <div>
        <h3 style="padding-top: 15px; padding-left: 28px;" >
            Last saved: <span id="last_modified_datetime">
            </span>
        </h3>
   </div>

    <div class="blue-nav" style="width: 500px;" align="center" >
        <ul>
            <?php if ($this->identity->permissions->incident_modify_permission === true) :  ?>
            <li>
                <span>
                    <a id="commonSaveButton" class="saveButton">
                        Save
                    </a>
                </span>
            </li>
            <li>
                <span>
                    <a id="discardButton">
                        Discard
                    </a>
                </span>
            </li>
            <?php endif; ?>
            <li><span><a class="createIncidentFile">Create File</a></span></li>
            <li><span><a class="exitIncidentProfile">Exit</a></span></li>
        </ul>
    </div>

</div>