<div class="bottom-nav">
    <span class="name-driver">
        Status:&nbsp;<span>Pending</span>
    </span>
    <ul class="blue-nav">
        <li>
            <span>
                <a href="/incident/file/create/id/<?= $this->i_ID ?>">
                    Create File
                </a>
            </span>
        </li>
        <li>
            <span>
                <a href="/incident/index/exit/id/<?= $this->i_ID ?>">
                    Exit
                </a>
            </span>
        </li>
    </ul>
</div>

<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?= $this->breadcrumbs; ?>
            </span>
        </div>
    </div>
</div>

<div class="driver-information" id="main">
    <input type="hidden" id="i_ID" value="<?= $this->i_ID; ?>"
    <input type="hidden" id="ic_ID" value="<?= $this->ic_ID; ?>"
        
    <div id="viewDescriptionDiv" class="DescriptionDiv">
        <?= $this->partial('partials/index/_view_description.phtml'); ?>
    </div>
    <div id="updateDescriptionDiv" class="DescriptionDiv" style="display: none;">
        <?= $this->partial('partials/index/_update_description.phtml', array('states' => $this->states)); ?>
    </div>
    

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Company Driver Information - involved in Incident</th></tr>
                        <tr><td colspan="2"><b>PERSONAL INFORMATION</b></td></tr>
                        <tr><td colspan="2">First Name: Charles  &nbsp;&nbsp;&nbsp;&nbsp;   Last Name:  Reed  &nbsp;&nbsp;&nbsp;&nbsp;  Middle Name: </td></tr>
                        <tr class="color-dark"><td colspan="2">DOB: 10/19/1963  &nbsp;&nbsp;&nbsp;&nbsp;  SSN #: 625068989 </td></tr>
                        <tr><td colspan="2">CDL #: A7569850  &nbsp;&nbsp;&nbsp;&nbsp;  Class: A  &nbsp;&nbsp;&nbsp;&nbsp;  Issued by State:  </td></tr>
                        <tr class="color-dark"><td colspan="2">Status: Hired  &nbsp;&nbsp;&nbsp;&nbsp;  Date Of Hire: 9/23/2010  &nbsp;&nbsp;&nbsp;&nbsp;  Termination Date: </td></tr>
                        <tr><td colspan="2">Sex: -  &nbsp;&nbsp;&nbsp;&nbsp;  Hair Color:   &nbsp;&nbsp;&nbsp;&nbsp;  Eyes Color:  &nbsp;&nbsp;&nbsp;&nbsp;   Height:  Feet   inch  &nbsp;&nbsp;&nbsp;&nbsp;  Weight: </td></tr>
                        <tr><td colspan="2"><b>ADDRESS</b></td></tr>
                        <tr><td colspan="2">Street: 856 East Ave &nbsp;&nbsp;&nbsp;&nbsp;   City: Oakland  &nbsp;&nbsp;&nbsp;&nbsp;  ZIP Code: 94609  &nbsp;&nbsp;&nbsp;&nbsp;  State: CA</td></tr>
                        <tr class="color-dark"><td colspan="2">Home Phone: 510-889-6353  &nbsp;&nbsp;&nbsp;&nbsp;  Business Phone:</td></tr>
                        <tr><td colspan="2"><b>PRE-COLLISION ACTIVITY</b></td></tr>
                        <tr><td colspan="2">Travel Direction: -    on Street/Highway: &nbsp;&nbsp;&nbsp;&nbsp;   Actual Speed:   &nbsp;&nbsp;&nbsp;&nbsp;  Speed Limit</td></tr>
                        <tr><td colspan="2"><b>PRE-COLLISION MOVEMENT</b></td></tr>
                        <tr><td colspan="2"><b>ACCIDENT IMPLICATION</b></td></tr>
                        <tr><td colspan="2">Injured:  Yes &nbsp;&nbsp;&nbsp;&nbsp;  Deceased:  Yes </td></tr>
                        <tr class="color-dark"><td colspan="2">Injury Description: </td></tr>
                        <tr><td colspan="2"><b>POST ACCIDENT TEST</b></td></tr>
                        <tr><td colspan="2">Citation issued within:   No citation </td></tr>
                        <tr class="color-dark"><td colspan="2">Alcohol test conducted within:   No alcohol test </td></tr>
                        <tr><td colspan="2">Drug test conducted within:   No drug test</td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Add Company Driver</a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Other non-company Driver Information - involved in Incident</th></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Add Non-Employee Driver</a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Witness/Passenger Information - involved in Incident</th></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Add Witness/Passenger Information </a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform">
                    <tbody><tr><th colspan="2">Type of Collision<br>
                            </th></tr><tr><td>Collision Type</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Vehicle involved in collision with</td><td>&nbsp;</td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Update type Of Collision </a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform adress">
                    <tbody><tr><th colspan="7">Road conditions at the time of Incident</th></tr>
                        <tr><td>Road Conditions</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Weather Conditions</td><td>&nbsp;</td></tr>
                        <tr><td>Roadway</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Traffic Condition</td><td>&nbsp;</td></tr>
                        <tr><td>Road Surface Condition</td><td>&nbsp;</td></tr>
                        <tr class="color-dark"><td>Traffic Control Devices</td><td>&nbsp;</td></tr>
                        <tr><td>Lightning Conditions</td><td>&nbsp;</td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Update Road Condition Information</a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="post-top"><div class="post-bottom"><div class="post-middle">
                <table cellspacing="0" class="inform adress">
                    <tbody><tr><th>DOT Incident criteria (Applies to commercial vehicles only)</th></tr>
                        <tr><td>Incident resulted in human fatality  <br>
			Incident did not result in injuries treated immediately/away from the scene   <br>
			The vehicles have been towed away from the scene   <br>
			Driver did not receive a traffic citation.   <br>
			Accident is DOT reportable.   </td></tr>
                        <tr><td colspan="2"><span class="blue-button"><span><a href="#">Update DOT Accident Criteria</a></span></span></td></tr>
                        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
                    </tbody></table>
            </div></div></div>

    <div class="blue-nav">
        <ul>
            <li><span><a href="/DQF">Create File</a></span></li>
            <li><span><a href="/exit">Exit</a></span></li>
        </ul>
    </div>

</div>