<table cellspacing="0" class="inform">
    <tbody>
    <tr>
        <th colspan="2">
            <h2><?= $this->layout()->header; ?></h2>
<!--            Witness Information - involved in Incident-->
        </th>
    </tr>
    </tbody>
</table>
<table cellspacing="0" class="inform">
    <tbody>
        <tr  class="color-dark">
            <td colspan="2">
                <?= $this->layout()->message; ?>
            </td>
        </tr>
    </tbody>
</table>
