<div class="post-top">
    <div class="post-bottom">
        <div class="post-middle">
            <table cellspacing="0" class="inform">
                <tbody>
                    <tr>
                        <th colspan="2">
                            Incident Description
                        </th>
                    </tr>
<!--                    <tr>
                        <td width="150">
                            Incident type:
                        </td>
                        <td>
                            
                        </td>
                    </tr>-->
                    <tr>
                        <td width="150">
                            Incident Number:
                        </td>
                        <td>
                            <input id="i_Number" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>LOCATION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            City: <input id="i_City" />
                            State: <input id="i_State_ID" />
                            Postal Code: <input id="i_Postal_Code" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Highway/Street: <input id="i_Highway_Street" />
                            at intersection with: <input id="i_At_Intersection" />
                        </td>
                    </tr>
<!--                    <tr>
                        <td colspan="2">

                            Or  &nbsp;&nbsp;&nbsp;&nbsp;  Feet from intersection with
                        </td>
                    </tr>-->
                    <tr class="color-dark">
                        <td colspan="2">
                            Mile Marker : <input id="i_Mile_Marker" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>DATE AND TIME</b>
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident Date : <input id="i_Date" value="<?= (isset($this->layout()->incidentRow['i_Date']) ? $this->layout()->incidentRow['i_Date'] : ''); ?>" />
                            Time: <input id="i_Time" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ACTION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Photo taken by:  <input id="i_Photo_Taken_By" />
                            Incident diagram taken:   <input id="i_Incident_Diagram_Taken" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident reported:  <input id="i_Reported" />
                            Police department:   <input id="i_Police_Department" />
                            Officer Name:   <input id="i_Officer_Name" />
                            Police report #:   <input id="i_Police_Report_Number" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>Incident Narrative:</b> <input id="i_Narrative" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            <b>Incident Preventable</b>: <input id="ic_Preventable" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="blue-button">
                                <span>
                                    <a id="saveIncidentDescription">
                                         Save
                                    </a>
                                </span>
                            </span>
                            <span class="blue-button">
                                <span>
                                    <a id="cancelIncidentDescription"  class="DescriptionActionLink">
                                         Cancel
                                    </a>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
