<div class="post-top">
    <div class="post-bottom">
        <div class="post-middle">
            <table cellspacing="0" class="inform">
                <tbody>
                    <tr>
                        <th colspan="2">
                            Incident Description
                        </th>
                    </tr>
                    <tr>
                        <td width="150">
                            Incident Number:
                        </td>
                        <td>
                            <input id="i_Number" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>LOCATION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            City: <input id="i_City" />
                            State: <select id="i_State_ID" >
                                    <?php
                                        foreach ($this->states as $key => $value) {
                                          echo '<option value="' . $key . '">' . $value . '</option>';
                                        }
                                    ?>
                                </select>
                            Postal Code: <input id="i_Postal_Code" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Highway/Street: <input id="i_Highway_Street" />
                            at intersection with: <input id="i_At_Intersection" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Mile Marker : <input id="i_Mile_Marker" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>DATE AND TIME</b>
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident Date : <input id="i_Date"/>
                            Time: <input id="i_Time" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ACTION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Photo taken by:  <input id="i_Photo_Taken_By" />
                            Incident diagram taken:   <input id="i_Incident_Diagram_Taken" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident reported:
                            <input type="radio" name="i_Reported" id="i_Reported_Yes" value="Yes">&nbsp;Yes
                            <input type="radio" name="i_Reported" id="i_Reported_No" checked="checked" value="No">&nbsp;No&nbsp;&nbsp;
                            Police department:<input id="i_Police_Department" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Officer Name:<input id="i_Officer_Name" />
                            Police report #:<input id="i_Police_Report_Number" />
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td>
                            <b>Incident Narrative:</b>
                        </td>
                        <td>
                            <input id="i_Narrative" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Incident Preventable</b>:
                        </td>
                        <td>
                            <input type="radio" name="ic_Preventable" id="ic_Preventable_Yes" value="Yes">&nbsp;Yes
                            <input type="radio" name="ic_Preventable" id="ic_Preventable_No" value="No">&nbsp;No
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="blue-button">
                                <span>
                                    <a id="saveIncidentDescription">
                                         Save
                                    </a>
                                </span>
                            </span>
                            <span class="blue-button">
                                <span>
                                    <a id="cancelIncidentDescription"  class="DescriptionActionLink">
                                         Cancel
                                    </a>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
