<div class="post-top">
    <div class="post-bottom">
        <div class="post-middle">
            <table cellspacing="0" class="inform">
                <tbody>
                    <tr>
                        <th colspan="2">
                            Incident Description
                        </th>
                    </tr>
                    <tr>
                        <td width="150">
                            Accident type:
                        </td>
                        <td>
                            Test Test
                        </td>
                    </tr>
                    <tr>
                        <td width="150">
                            Accident Number:</td>
                        <td>
                            3498328
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>LOCATION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            City: Test Test &nbsp;&nbsp;&nbsp;&nbsp; County: Test Test State: &nbsp;&nbsp;&nbsp;&nbsp; Test Test
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Highway/Street: &nbsp;&nbsp;&nbsp;&nbsp;  at intersection with: &nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Or  &nbsp;&nbsp;&nbsp;&nbsp;  Feet from intersection with
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Describe accident allocation to the nearest Mile Marker :
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>DATE AND TIME</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ACTION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Photo taken by:  &nbsp;&nbsp;&nbsp;&nbsp;      Accident diagram taken:   &nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Accident reported:  &nbsp;&nbsp;&nbsp;&nbsp;      Police department:   &nbsp;&nbsp;&nbsp;&nbsp;      Officer Name:   &nbsp;&nbsp;&nbsp;&nbsp;      Police report #:   &nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>ACCIDENT NARRATIVE</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Hazardous material (other than fuel) spilled :  No       Fuel spilled:   No
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Accident Preventable:
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="blue-button">
                                <span>
                                    <a href="#">
                                        Update Accident Description
                                    </a>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
