<div class="post-top"><div class="post-bottom"><div class="post-middle">
<table cellspacing="0" class="inform">
    <tbody>
        <tr>
            <th colspan="2">
                Company Driver Information - involved in Incident
            </th>
        </tr>
        <tr>
            <th colspan="2">
                PERSONAL INFORMATION [<a id="editDriverLink">VIEW FULL DRIVER INFORMATION</a>]
            </th></tr>
        <tr>
            <td>Driver Name</td>
            <td>First:&nbsp;<span id="view_d_First_Name"></span>
                Last:&nbsp;<span id="view_d_Last_Name"></span>
                Middle:&nbsp;<span id="view_d_Middle_Name"></span>
            </td>
        </tr>
        <tr class="color-dark">
            <td>Date Of Birth</td>
            <td><span id="view_d_Date_Of_Birth"></span></td>
        </tr>
        <tr>
            <td>Social Security #</td>
            <td><span id="view_d_Driver_SSN"></span></td>
        </tr>
        <tr class="color-dark">
            <td>Medical Card</td>
            <td>Expires:&nbsp;<span id="view_d_Medical_Card_Expiration_Date"></span>
                Medical Examiner's Name:&nbsp;<span id="view_d_Doctor_Name"></span>
            </td>
        </tr>
        <tr>
            <td>Phone Information</td>
            <td>#1 phone number:&nbsp;<span id="view_d_Telephone_Number1"></span><br>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>

        <tr>
            <td colspan="2">
                <b>COLLISION ACTIVITY</b>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                Travel Direction:&nbsp;&nbsp;<span id="view_i_Travel_Direction_ID"></span>&nbsp;
                on Street/Highway:&nbsp;&nbsp;<span id="view_i_Collision_Highway_Street"></span>&nbsp;
                &nbsp;&nbsp;&nbsp;Actual Speed: &nbsp;&nbsp;<span id="view_i_Actual_Speed"></span>&nbsp;
                &nbsp;Speed Limit &nbsp;&nbsp;<span id="view_i_Speed_Limit"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <b>COLLISION MOVEMENT</b><br />
                <span id="view_i_Collision_Movement"></span>
            </td>
        </tr>
        <tr class="color-dark">
            <td colspan="2">
                &nbsp;&nbsp;Other:&nbsp;&nbsp;<br />
                <span id="view_i_Collision_Movement_Other"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <b>ACCIDENT IMPLICATION</b>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                Injured:  <span id="view_i_Injured"></span> &nbsp;&nbsp;&nbsp;&nbsp;
                Deceased: <span id="view_i_Deceased"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <b>POST ACCIDENT TEST</b>
            </td>
        </tr>
        <tr class="color-dark">
            <td colspan="2">
                Alcohol test conducted within:&nbsp;&nbsp;<span id="view_i_Alcohol_Test"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                Drug test conducted within:&nbsp;&nbsp;<span id="view_i_Drug_Test"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <span class="blue-button">
                    <span>
                        <a id="updateIncidentDriverInformation" class="DriverInformationActionLink">
                            Update Driver Information
                        </a>
                    </span>
                    <span>
                        <a id="changeDriverButton">
                            Change Driver
                        </a>
                    </span>
                </span>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>
</div></div></div>