<div class="post-top">
    <div class="post-bottom">
        <div class="post-middle">
            <table cellspacing="0" class="inform">
                <tbody>
                    <tr>
                        <th colspan="2">
                            Incident Description
                        </th>
                    </tr>
<!--                    <tr>
                        <td width="150">
                            Incident type:
                        </td>
                        <td>
                            
                        </td>
                    </tr>-->
                    <tr>
                        <td width="150">
                            Incident Number:
                        </td>
                        <td>
                            <?= (isset($this->layout()->incidentRow['i_Number']) ? $this->layout()->incidentRow['i_Number'] : ''); ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>LOCATION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            City: &nbsp;&nbsp; <?= (isset($this->layout()->incidentRow['i_City']) ? $this->layout()->incidentRow['i_City'] : ''); ?> &nbsp;&nbsp;
                            State: &nbsp;&nbsp; <?= (isset($this->layout()->incidentRow['s_name']) ? $this->layout()->incidentRow['s_name'] : ''); ?>&nbsp;&nbsp;
                            Postal Code: &nbsp;&nbsp; <?= (isset($this->layout()->incidentRow['i_Postal_Code']) ? $this->layout()->incidentRow['i_Postal_Code'] : ''); ?> &nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Highway/Street: &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Highway_Street']) ? $this->layout()->incidentRow['i_Highway_Street'] : ''); ?>&nbsp;&nbsp;
                            at intersection with: &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_At_Intersection']) ? $this->layout()->incidentRow['i_At_Intersection'] : ''); ?>&nbsp;&nbsp;
                        </td>
                    </tr>
<!--                    <tr>
                        <td colspan="2">

                            Or  &nbsp;&nbsp;&nbsp;&nbsp;  Feet from intersection with
                        </td>
                    </tr>-->
                    <tr class="color-dark">
                        <td colspan="2">
                            Mile Marker : <?= (isset($this->layout()->incidentRow['i_Mile_Marker']) ? $this->layout()->incidentRow['i_Mile_Marker'] : ''); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>DATE AND TIME</b>
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident Date : &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Date']) ? $this->layout()->incidentRow['i_Date'] : ''); ?>&nbsp;&nbsp;
                            Time: &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Time']) ? $this->layout()->incidentRow['i_Time'] : ''); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ACTION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Photo taken by:  &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Photo_Taken_By']) ? $this->layout()->incidentRow['i_Photo_Taken_By'] : ''); ?>&nbsp;&nbsp;
                            Incident diagram taken:   &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Incident_Diagram_Taken']) ? $this->layout()->incidentRow['i_Incident_Diagram_Taken'] : ''); ?>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident reported:  &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Reported']) ? $this->layout()->incidentRow['i_Reported'] : ''); ?>&nbsp;&nbsp;
                            Police department:   &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Police_Department']) ? $this->layout()->incidentRow['i_Police_Department'] : ''); ?>&nbsp;&nbsp;
                            Officer Name:   &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Officer_Name']) ? $this->layout()->incidentRow['i_Officer_Name'] : ''); ?>&nbsp;&nbsp;
                            Police report #:   &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Police_Report_Number']) ? $this->layout()->incidentRow['i_Police_Report_Number'] : ''); ?>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>Incident Narrative:</b> &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['i_Narrative']) ? $this->layout()->incidentRow['i_Narrative'] : ''); ?>&nbsp;&nbsp;
                        </td>
                    </tr>
<!--                    <tr>
                        <td colspan="2">
                            Hazardous material (other than fuel) spilled :  No       Fuel spilled:   No
                        </td>
                    </tr>-->
                    <tr class="color-dark">
                        <td colspan="2">
                            <b>Incident Preventable</b>: &nbsp;&nbsp;<?= (isset($this->layout()->incidentRow['ic_Preventable']) ? $this->layout()->incidentRow['ic_Preventable'] : ''); ?>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="blue-button">
                                <span>
                                    <a id="updateIncidentDescription" class="DescriptionActionLink" onclick="hideDescription();">
                                        Update Accident Description
                                    </a>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
