<div class="post-top">
    <div class="post-bottom">
        <div class="post-middle">
            <table cellspacing="0" class="inform">
                <tbody>
                    <tr>
                        <th colspan="2">
                            Incident Description
                        </th>
                    </tr>
<!--                    <tr>
                        <td width="150">
                            Incident type:
                        </td>
                        <td>
                            
                        </td>
                    </tr>-->
                    <tr>
                        <td width="150">
                            Incident Number:
                        </td>
                        <td>
                            <div id="view_i_Number"></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>LOCATION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            City: &nbsp;&nbsp; <div id="view_i_City"></div>&nbsp;&nbsp;
                            State: &nbsp;&nbsp; <div id="view_s_name""></div>&nbsp;&nbsp;
                            Postal Code: &nbsp;&nbsp; <div id="view_i_Postal_Code"></div>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Highway/Street: &nbsp;&nbsp;<div id="view_i_Highway_Street"></div>&nbsp;&nbsp;
                            at intersection with: &nbsp;&nbsp;<div id="view_i_At_Intersection"></div>&nbsp;&nbsp;
                        </td>
                    </tr>
<!--                    <tr>
                        <td colspan="2">

                            Or  &nbsp;&nbsp;&nbsp;&nbsp;  Feet from intersection with
                        </td>
                    </tr>-->
                    <tr class="color-dark">
                        <td colspan="2">
                            Mile Marker : <div id="view_i_Mile_Marker"></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>DATE AND TIME</b>
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident Date : &nbsp;&nbsp;<div id="view_i_Date"></div>&nbsp;&nbsp;
                            Time: &nbsp;&nbsp;<div id="view_i_Time"></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ACTION</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Photo taken by:  &nbsp;&nbsp;<div id="view_i_Photo_Taken_By"></div>&nbsp;&nbsp;
                            Incident diagram taken:   &nbsp;&nbsp;<div id="view_i_Incident_Diagram_Taken"></div>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr class="color-dark">
                        <td colspan="2">
                            Incident reported:  &nbsp;&nbsp;<div id="view_i_Reported"></div>&nbsp;&nbsp;
                            Police department:   &nbsp;&nbsp;<div id="view_i_Police_Department"></div>&nbsp;&nbsp;
                            Officer Name:   &nbsp;&nbsp;<div id="view_i_Officer_Name"></div>&nbsp;&nbsp;
                            Police report #:   &nbsp;&nbsp;<div id="view_i_Police_Report_Number"></div>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <b>Incident Narrative:</b> &nbsp;&nbsp;<div id="view_i_Narrative"></div>&nbsp;&nbsp;
                        </td>
                    </tr>
<!--                    <tr>
                        <td colspan="2">
                            Hazardous material (other than fuel) spilled :  No       Fuel spilled:   No
                        </td>
                    </tr>-->
                    <tr class="color-dark">
                        <td colspan="2">
                            <b>Incident Preventable</b>: &nbsp;&nbsp;<div id="view_ic_Preventable"></div>&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="blue-button">
                                <span>
                                    <a id="updateIncidentDescription" class="DescriptionActionLink" onclick="hideDescription();">
                                        Update Accident Description
                                    </a>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
