<?php

?>
        <tr align="center">
            <td><?php echo $this->layout()->currentDriverHoSList[6]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[5]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[4]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[3]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[2]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[1]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[0]['dhos_date'];?></td>
        </tr>
        <tr class="color-dark" align="center">
            <td><?php echo $this->layout()->currentDriverHoSList[6]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[5]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[4]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[3]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[2]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[1]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[0]['dhos_hours'];?></td>