<?php $date=new Zend_Date(); ?>    
<tbody id="hos_list">
        <tr align="center">
            <td><?php echo $this->layout()->currentDriverHoSList[6]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[5]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[4]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[3]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[2]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[1]['dhos_date'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[0]['dhos_date'];?></td>
        </tr>
        <tr class="color-dark" align="center">
            <td><?php echo $this->layout()->currentDriverHoSList[6]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[5]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[4]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[3]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[2]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[1]['dhos_hours'];?></td>
            <td><?php echo $this->layout()->currentDriverHoSList[0]['dhos_hours'];?></td>
        </tr>
        </tbody>
        <?php echo $this->partial('partials/_edit-HoS-Table.phtml',array('currentDriverHoSList' => $this->layout()->currentDriverHoSList,"driverId" => $this->layout()->driverId)); ?>

        <tbody id="lrfw_list">
        <tr>
            <td colspan="7">Last relieved from work:&nbsp;<span></span>Date:&nbsp;
                <span><?php
                if(isset($this->layout()->currentDriverLrfwRecord[0]['dlrfw_date'])){
                    $date->set($this->layout()->currentDriverLrfwRecord[0]['dlrfw_date'],"yyyy-MM-dd");
                    echo $date->toString("MM/dd/yyyy");
                }
                ?></span>
                Time:&nbsp;<span><?php if($this->layout()->currentDriverLrfwRecord!=null){echo $this->layout()->currentDriverLrfwRecord[0]['dlrfw_from_time'];}?></span>
            </td>
        </tr>
        </tbody>
        <?php echo $this->partial('partials/_edit-lrfw-Table.phtml',array('currentDriverLrfwRecord' => $this->layout()->currentDriverLrfwRecord)); ?>

        <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
        </tbody>